ethereum/trin

.circleci/config.yml

Based on instructions from:
https://circleci.com/developer/orbs/orb/circleci/rust

Start running CircleCI tests

---

Cargo.lock
Cargo.toml

Update discv5 to 0.1.0-beta.4

---

Cargo.lock
Cargo.toml
src/main.rs
src/portalnet/protocol.rs
src/portalnet/types.rs

I'm not particularly familiar with SSZ, so I hacked together the implementations for the `Nodes` and `FindNodes` methods, but it does seem compatible with ddht now.

Spawn a new task for processing events; fix ssz for Nodes/FindNodes

---

src/portalnet/discovery.rs

Hello, I'm part of the apprenticeship program and new to Rust. Happy to learn and get feedback from you guys.
This PR sorts nodes by distance.
Fixes https://github.com/carver/trin/issues/42.

Sort closest nodes by distance

---

README.md

Lists several of the RPC methods exposed by trin (especially the `discv5_nodeInfo` one that gives the all important ENR!!!)

Add some of the RPC methods to the readme

---

Cargo.lock
trin-core/Cargo.toml
trin-core/src/portalnet/discovery.rs
trin-core/src/portalnet/mod.rs
trin-core/src/portalnet/overlay.rs
trin-core/src/portalnet/protocol.rs

- Add Overlay struct to manage node state for overlay network.
- Add APIs to Overlay to query node state.

Add overlay node state to manage overlay routing table

---

Cargo.lock
trin-core/src/portalnet/overlay.rs

Update discv5 in Cargo.lock

---

src/main.rs
trin-core/src/portalnet/discovery.rs
trin-core/src/portalnet/protocol.rs
trin-history/src/lib.rs
trin-state/src/lib.rs

Initialize Discovery protocol outside of PortalProtocol struct and pass it as parameter.

Decouple Discovery struct from PortalProtocol

---

Cargo.lock
trin-core/Cargo.toml
trin-core/src/portalnet/mod.rs
trin-core/src/portalnet/overlay.rs
trin-core/src/portalnet/protocol.rs
trin-core/src/portalnet/utp.rs

So I think I have a 95ish% done base viable implementation of uTP as a sub-protocol over Discv5. This will be a draft PR where I am looking to get recommendations on how I should implement certain parts which will be used by the other parts of Trin so I want some of your feedback.
~~So from my stance, it looks like it might be cleaner to just refactor UtpListener impl into PortalnetEvents impl. I made it into a separate impl because well initially implementing it that was easier.~~
~~So would you guys want me to refactor it into PortalnetEvents, I think it would be better as it would be cleaner in a sense, but separation might be good too~~
~~So this might be the most important thing we chat about, How should we expose the byte stream. I have talked to Piper about this a fair bit, but I …

Implemented uTP sub-protocol

---

trin-core/src/portalnet/overlay.rs
trin-core/src/portalnet/utp.rs

@ogenev I *think* this change should leave behavior unchanged, and all the tests pass, but I don't know how comprehensive the tests are. I'm hoping you have time to run this and make sure it still works for you, tagging you because it seems like you wrote most of this code.

refactor - use RwLock::read() when possible

---

CONTRIBUTING.md
README.md
contributor_guidelines.md
trin-core/Cargo.toml

Just the beginning of a contributor guidelines section, a document outlining the various code hygiene and style tips that pr's should follow. The majority of this was lifted from the [snake charmers tactical manual](https://github.com/ethereum/snake-charmers-tactical-manual/). This is by no means a final version of these guidelines, and contributors are encouraged to update this document as the project grows and we recognize new guidelines that we want the project to follow.

Contributor guidelines

---

CONTRIBUTING.md

Add guideline on cloning

---

trin-core/src/portalnet/types.rs

Handle message decode errors.
Extracted from https://github.com/ethereum/trin/pull/143

Better message decode error handling

---

trin-core/src/portalnet/utp.rs

@KonradStaniec notified me of issues he found during his testing of the interop between fluffy and trin.
Here is a PR of the changes he requested and a few other spots I found the same issues he pointed out.

Fixed two issues found in uTP impl

---

trin-core/src/portalnet/utp.rs

I added the test vectors Konrad's detailed in his PR https://github.com/ethereum/portal-network-specs/pull/127

Add Konrad's test vectors for uTP

---

trin-core/src/portalnet/overlay_service.rs

Fix #216
Use content ID instead of content key to perform local lookup for nodes closest to some content.

Fix local closest nodes lookup to use content ID

---

.circleci/config.yml
Cargo.toml
ethportal-peertest/Cargo.toml
trin-core/Cargo.toml
trin-history/Cargo.toml
trin-state/Cargo.toml

https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html

Update rust version to v1.58.0

---

trin-core/src/portalnet/overlay_service.rs

This is a fairly minor bugfix, basically the fix that was needed in #216 is also required for direct db fetches. Data is stored under its `content_id` - looking it up directly via its `content_key` will return nothing.
But this brings up another question... Right now, we're in a bit of a limbo between two db paradigms (a simple rocksdb / `PortalStorage`). The script (`trin-core/src/bin/generate-data.rs`) I'm using to seed the database uses `PortalStorage`. `trin-core` currently uses a simple rocksdb strategy. 
The weird thing about this bugfix is that it's currently needed, but once `PortalStorage` is integrated, it's no longer needed (since `PortalStorage` handles the content id derivation).
I've talked with @mrferris about this recently. The decision to hold off on `PortalStorage` …

Fix content lookup

---

README.md
docs/getting_started.md
newsfragments/252.doc.md

Update getting started to include trin-cli instructions

---

trin-core/src/portalnet/storage.rs
trin-core/src/portalnet/types/content_key.rs

Improve unit tests for PortalStorage

---

trin-core/src/portalnet/find/query_pool.rs

With the `Query` trait setup, there had become no way to get a query's ID when calling `poll` on the `QueryPool` and receiving a `QueryPoolState`. Having the ID is necessary in `OverlayService` for keeping track of which request corresponds to a given query, as well as for logging query completion/timeout.
A field for the query's `QueryId` was added to each `QueryPoolState` enum variant.
An alternative would have been to add a `fn id() -> QueryId` method to the `Query` trait (like previously existed on the `FindNodeQuery` type in #265), but this would also require that the trait have a `fn set_id(query_id: QueryId)` method because the query is now already created by the time the `QueryId` generated in the `QueryPool`'s `add_query` method.
With the taken approach, only the `QueryPool` …

Include QueryId in QueryPoolState enum variants

---

ethportal-peertest/src/jsonrpc.rs
ethportal-peertest/src/lib.rs
ethportal-peertest/src/scenarios.rs
newsfragments/359.added.md
tests/self_peertest.rs
trin-core/src/portalnet/overlay_service.rs
trin-core/src/utils/db.rs
trin-history/src/jsonrpc.rs
trin-state/src/jsonrpc.rs

Integration tests for offer/accept flow are missing.
Add offer/accept scenario as part of `ethportal-peertest`

Add OFFER/ACCEPT test

---

docs/getting_started.md

Minor update to docs to complete a task in #311 . Will go into more detail on how to use web3 as general purpose rpc server in upcoming blog post.

Update web3 docs

---

trin-core/src/portalnet/overlay_service.rs

Method param `source` is non-nullable but has type `Option<&NodeId>`.
Change param `source` to have type `&NodeId`.

cleanup: remove Option for non-nullable param

---

Cargo.lock
newsfragments/455.added.md
trin-core/src/types/accumulator.rs
trin-history/Cargo.toml
trin-history/src/validation.rs

No validation for epoch accumulators received over network.

Validate pre-merge headers via master acc.

---

docs/jsonrpc_api.md
ethportal-peertest/src/scenarios/eth_rpc.rs
ethportal-peertest/src/scenarios/mod.rs
ethportal-peertest/src/scenarios/offer_accept.rs
ethportal-peertest/src/scenarios/paginate.rs
newsfragments/474.added.md
tests/self_peertest.rs
trin-core/src/jsonrpc/endpoints.rs
trin-core/src/jsonrpc/types.rs
trin-core/src/portalnet/storage.rs
trin-history/src/jsonrpc.rs

- fixes #470
- Rearrange ethportal-peertest scenarios

Paginate local content keys

---

README.md
docs/contributing.md
docs/ubuntu_guide.md

Fix: typos in docs

---

docker/Dockerfile.bridge
ethportal-api/src/types/content_item.rs
trin-core/src/types/bridge.rs

Add some linting to `bridge` code & gossip epoch accumulators if available locally

Lint bridge code

---

trin-core/src/portalnet/overlay.rs

Per piece of content to gossip, Trin currently gossips to 5-7 random nodes from the entire routing table. This results in data mostly being gossiped to nodes where the data won't reasonably be looked for during queries.
Before selecting gossip recipients for a given piece of content, the routing table is sorted by proximity to that content. The content is then gossiped to (at most) the 4 closest nodes, and 4 other random nodes.

Gossip to combination of closest nodes and random nodes, rather than just random nodes

---

trin-core/src/cli.rs
trin-core/src/types/bridge.rs

Add start from epoch arg to bridge mode

---

trin-utils/src/version.rs

Shortening version hash bugfix

---

trin-core/src/portalnet/overlay.rs
trin-history/src/lib.rs

Related to #530 
Added heartbeat log that shows radius as a percentage of data covered

Add simple heartbeat log to history network

---

portalnet/src/storage.rs

Show number of storage items in heartbeat log

---

portalnet/src/storage.rs

Second attempt to fix #624 
Following Piper's suggestion:
https://github.com/ethereum/trin/issues/624#issuecomment-1495106383
We leave DB slightly overfull to detect that we are at capacity. Then we set the radius there.
On `trin` reboot, we either end up with 100% radius, or we are full, and set the radius to exactly the furthest content id.

Only prune until DB is slightly overfull

---

portalnet/src/overlay_service.rs
portalnet/src/types/messages.rs

fixes #523
* move constants for portal wire message limits to `portalnet::types::messages.rs`
* renaming:
* from `MAX_NODES_SIZE` to `MAX_PORTAL_NODES_ENRS_SIZE`
* from `MAX_CONTENT_NODES_SIZE` to `MAX_PORTAL_CONTENT_PAYLOAD_SIZE`
* use `MAX_PORTAL_CONTENT_PAYLOAD_SIZE` when constructing a portal content response to determine whether uTP transmission is necessary
* the following values were changed:
* `discv5` talk request overhead: from `103` to `109`
* `portal` nodes `enrs` overhead: from `2` to `6`
* `portal` content `enrs` overhead: from `5` to `6`

refactor constants for portal wire message limits

---

Cargo.lock
ethportal-api/src/history.rs
ethportal-peertest/src/scenarios/find.rs
newsfragments/657.added.md
portalnet/src/overlay.rs
portalnet/src/overlay_service.rs
rpc/src/history.rs
tests/self_peertest.rs
trin-history/src/jsonrpc.rs
trin-types/Cargo.toml
trin-types/src/jsonrpc/endpoints.rs
trin-types/src/lib.rs
trin-types/src/node_id.rs

Recursive find nodes jsonrpc api endpoint

---

Cargo.lock
newsfragments/681.fixed.md
trin-bridge/src/main.rs
trin-types/Cargo.toml
trin-types/src/cli.rs
trin-validation/Cargo.toml
trin-validation/src/accumulator.rs

fixes https://github.com/ethereum/trin/issues/466
by utilizing the [rust-embed](https://crates.io/crates/rust-embed) crate

embed pre-merge master accumulator

---

trin-bridge/src/bridge.rs

A primary motivation behind #733 was to improve error handling when gossiping a single block. Currently, if there is an error in any of the 3 gossip steps for a single block (header / bb / receipts), we return early. The ideal behavior would be to continue and attempt to gossip every type of content for a single block, regardless of whether a single content failed or not. 
Don't return on errors for gossiping a type of content.

Improve bridge gossip error handling

---

Cargo.lock
Cargo.toml
portalnet/Cargo.toml
portalnet/src/overlay_service.rs
trin-beacon/Cargo.toml
trin-history/Cargo.toml
trin-state/Cargo.toml

Bump utp dependency version

---

ethportal-api/src/dashboard/grafana.rs

A couple minor bugfixes to the grafana dashboard creation logic.

Bugfix grafana dashboard creation

---

ethportal-api/src/types/jsonrpc/endpoints.rs
ethportal-api/src/types/jsonrpc/params.rs
ethportal-api/src/types/jsonrpc/request.rs

fixes issue 1 in tracking pr https://github.com/ethereum/trin/issues/759
by looking for unused code and removing it

Cleaning up unsupported/used jsonrpc utils

---

ethportal-api/src/types/content_value.rs
newsfragments/776.added.md
trin-bridge/src/bridge.rs
trin-bridge/src/cli.rs
trin-bridge/src/constants.rs
trin-bridge/src/main.rs
trin-history/src/validation.rs
trin-validation/src/oracle.rs

Add support for bridge mode to construct & gossip a single block

Single block mode support inside bridge

---

book/src/introduction/portal_network.md
book/src/users/installation.md

@njgheorghita Perelyn 1 - Git 0

Fix typos and add list to installation page

---

portalnet/src/overlay_service.rs

Queries were timing out when no nodes were available for the query. This was always the case, but having no nodes available  became something that started happening when #802 was merged, which only considers connected nodes.
1. Use closest nodes regardless of connectivity if all nodes are in a disconnected state
2. If no nodes whatsoever are in our routing table, send a "no content found" response immediately instead of never responding. Currently change 1 makes it so that this should never happen, but better safe than sorry.

Respond to query if no nodes available

---

Cargo.lock
utp-testing/Cargo.toml
utp-testing/src/bin/test_app.rs
utp-testing/src/cli.rs

Remove structopt from utp-testing

---

trin-utils/src/lib.rs
trin-validation/src/lib.rs

Add unwrap_used lint to trin-utils and trin-validation

---

book/src/developers/quick_setup.md

fix broken link in book

---

book/src/developers/contributing/releases/deployment.md

book: Fix sops link

---

book/src/developers/core_concepts/cryptographic_accumulator.md

fix typos in cryptographic_accumlator.md

---

Cargo.lock
ethportal-api/Cargo.toml
trin-state/Cargo.toml

chore: bump eth_trie

---

portal-bridge/src/constants.rs

Update pandoaps url

---

book/src/developers/contributing/releases/deployment.md

When I was flamingo I ran into a few issues.
By adding addition instructions for the things I missed.

Add improvements to deployment.md

---

.circleci/config.yml
.github/workflows/stale.yml
book/src/developers/contributing/releases/deployment.md
book/src/developers/contributing/releases/prerelease_checklist.md
book/src/developers/contributing/releases/release_checklist.md
book/src/developers/contributing/rotation/index.md

Little tweaks that probably don't deserve their own PRs

Batch of flamingo updates for the week

---

portal-bridge/src/bridge.rs

Small bug (due to bad variable naming) resulted in a bug when using the epoch selector in bridge mode.  This should fix the problem we're seeing in our backfill bridge nodes that loop over to start at epoch #1 after completing their initial epoch.
Also fixed another small bug to correctly set `end_block` to `latest_block` in instances when it would be a value greater than the head of the chain.
Also fixed another small bug that skips all gossip if user sets start block in current epoch.
🐛  🥾 

Fix broken bridge mode loop with epoch selector

---

book/src/developers/architecture/database.md

docs: fix typo in database.md

---

.github/workflows/ci.yml

Add conventional commit lint github action

---

portal-bridge/src/beacon_bridge.rs

Pushing `LightClientUpdate` data at the beginning of the current sync committee period prevents Trin from syncing when it is using those updates in future periods. Light client specs expect the `LightClientUpdate` data to have finality, i.e. the finalized header slot is within the current expected period.
Update the beacon bridge to push `LightClientUpdate` content only when the finalized header slot is within the current expected period.

fix(portal-bridge): push `LightClientUpdate` if finalized header is within the current expected period

---

book/src/developers/contributing/releases/deployment.md

In case a deployment fails / breaks everything (which happened to me this week), I added rollback steps to deployment docs.

Add rollback steps to deployment docs

---

.github/workflows/dependencies.yml

there was an empty line at the top of this file
removed the line

style: remove empty first line of dependencies.yml

---

portalnet/src/overlay_service.rs

fixes https://github.com/ethereum/trin/pull/1051#pullrequestreview-1760194362
fixes the grammar

style: fix grammar in add_bootnodes docstring

---

portalnet/src/storage.rs

Light client finality and optimistic updates are transient data for the beacon network and we don't need to store those values in the main DB.
Implemented a cache for the beacon storage and updated the put and get methods to retrieve those updates from the cache.

feat: add beacon storage cache for light client updates

---

portal-bridge/src/bridge/history.rs

fixes https://github.com/ethereum/trin/pull/1082#discussion_r1446375882
clones what is needed instead of self itself

refactor: history bridge remove self from calls

---

Cargo.lock
light-client/Cargo.toml
light-client/README.md
light-client/src/client.rs
light-client/src/config/checkpoints.rs
light-client/src/config/utils.rs
light-client/src/consensus/consensus_client.rs
light-client/src/consensus/rpc/mock_rpc.rs
light-client/src/consensus/rpc/mod.rs
light-client/src/consensus/rpc/nimbus_rpc.rs
light-client/src/consensus/rpc/portal_rpc.rs
light-client/src/consensus/types.rs
light-client/src/consensus/utils.rs
light-client/src/database.rs
light-client/src/errors.rs
light-client/src/main.rs
light-client/src/node.rs
light-client/src/rpc.rs
light-client/src/utils.rs
trin-beacon/Cargo.toml

fix: https://github.com/ethereum/trin/issues/1047
migrate eyre to anyhow equivalents

feat: migrate from eyre to anyhow

---

light-client/src/config/checkpoints.rs

A `light-client` test recently started failing breaking our ci. I'm not sure I 100% grasp the problem, but believe I have all the important parts covered.
There seems to have been some issues with a fork on goerli yesterday (from ACD discord channel). It seems like the checkpoint fallback data providers we were using "probably" haven't made whatever fixes were necessary to track the head of the chain. Therefore they were not able to find a "finalized block_root". 
So... the data providers we were using could not track the head of the chain, but some of the other checkpoint providers did implement the changes necessary to track the head of the chain. The problem is that we are unable to deserialize the json from these providers. So the json responses (containing a finalized block root) …

fix: light-client goerli source data broken

---

portal-bridge/src/bridge/history.rs
portal-bridge/src/types/mode.rs

Fixes #1100
Extracted the logic and wrote unit tests

refactor: extract gossip range calculation into BridgeMode

---

portal-bridge/src/api/execution.rs
portal-bridge/src/bridge/history.rs

Noticed an opportunity to refactor while working on some scripts to test providers. Decided to split it out into its own pr to minimize the diff in the other pr. 
Some logic was located in the `HistoryBridge` to construct a block body. In fact, this logic is much more "relationally adjacent" to the logic inside the `ExecutionApi` so it belongs there.

refactor(bridge): extract logic from history bridge into execution api

---

portal-bridge/src/bridge/history.rs

The error handling in the bridge isn't great. Lack of clearly outputting errors led to a change (#1104) which turns out to not be as performant as previously expected.
- When launching a thread w/ a timeout to gossip a full block, we should still handle the error case and output the error message in the situation when the thread does not timeout but an error occurs. If there is a timeout, then a timeout error message will be displayed.
- There's no reason not to attempt gossiping receipts when there is a failure gossiping bodies. Instead of returning an error, simply displaying the error should be sufficient to communicate that something's wrong.

refactor(bridge): improve error handling in bridge

---

.github/workflows/release.yml

chore: fix release github action

---

portal-bridge/src/bridge/history.rs

With the non-blocking changes to backfill, we weren't waiting till all blocks finished gossiping before closing the bridge. I noticed this running kurtosis in single mode, but this will happen for in all modes when it is about to stop.
Solution after we are done creating all the gossipping threads. Await the thread handles. This won't deadlock, because the tokio:spawn has a timeout.
Another solution could be sleeping the tokio::spawn timeout, I don't like that solution as much because then we can keep the application running longer then it has to.

fix: prevent history backfill bridge from closing before block is gossiped

---

light-client/src/config/checkpoints.rs

Fix #1132
Fetching checkpoint could get stuck indefinitely. See #1132 for more details.
I added timeout to our requests.
I'm not sure if this should fix and close #1132, because ideally we should use mock servers for testing (not to spam real ones), but that might not be so easy to do.
I'm fine with either way.

fix: add timeout to checkpoint requests

---

portal-bridge/src/api/consensus.rs
portal-bridge/src/api/execution.rs

we didn't print the EL providers response in the error messages
by adding them

refactor(bridge): print EL provider response on error

---

ethportal-api/src/types/state_trie/nibbles.rs

Nibbles encoding/decoding was no longer up to spec. Spec was updated in ethereum/portal-network-specs/pull/275
Wrote encoding/decoding and updated the `portal-spec-tests` submodule (it has updated test vectors).

feat(state_network): update Nibbles encoding according to spec

---

Cargo.lock
trin-history/src/storage.rs
trin-storage/Cargo.toml
trin-storage/src/lib.rs
trin-storage/src/utils.rs

Just a small refactoring of the storage crate.
I want to isolate changes that I make to the old code base the new storage design. This PR should cover most of them.

refactor(storage): refactor ContentId, DistanceFunction and byte_vector_to_u32

---

trin-storage/src/sql.rs
trin-storage/src/utils.rs

fix: use execute_batch for multi sql statement

---

docker/Dockerfile.bridge

fix: cache portal-accumulators in bridge dockerfile

---

portal-bridge/src/bridge/era1.rs
src/bin/sample_range.rs

Minor improvements to the logs & some refactoring in the `sample_range` script

refactor: sample range script cleanup

---

Cargo.lock
Cargo.toml
ethportal-api/Cargo.toml
ethportal-api/src/types/content_key/overlay.rs
ethportal-api/src/types/content_key/state.rs
ethportal-peertest/Cargo.toml
light-client/Cargo.toml
trin-beacon/Cargo.toml
trin-beacon/src/storage.rs
trin-history/Cargo.toml
trin-history/src/storage.rs
trin-metrics/src/storage.rs
trin-state/Cargo.toml
trin-state/src/storage.rs
trin-storage/Cargo.toml
trin-storage/src/error.rs
trin-storage/src/lib.rs
trin-storage/src/test_utils.rs
trin-storage/src/versioned/id_indexed_v1/mod.rs
trin-storage/src/versioned/id_indexed_v1/sql.rs
trin-storage/src/versioned/id_indexed_v1/store.rs
trin-storage/src/versioned/id_indexed_v1/usage_stats.rs
trin-storage/src/versioned/mod.rs
trin-storage/src/versioned/store.rs
trin-storage/src/versioned/utils.rs
trin-utils/src/lib.rs
trin-utils/src/submodules.rs

Our storage could be improved with proposals #1157.
The safest way to do it is to:
- implement new store (that is compatible with versioning)
- test it separately (firstly on state and later on history network)
- migrate history network to it as well
This PR implements the store and provides minimal usage from the `StateStorage`.
**NOTE:** I plan further improvements in the `StateStorage` in followup PR, together with better tests. I'm also fine with removing `StateStorage` completely from this PR, but I left it as an example of how store will be used.
Also, some additional refactoring (extracting common functions and such) and crate updates across the codebase. Probably more code can be refactored to use all this properly, but I didn't want to make this PR even bigger (and I think it …

feat(storage): new store implementation

---

Cargo.lock
Cargo.toml
portalnet/Cargo.toml
trin-beacon/Cargo.toml
trin-history/Cargo.toml
utp-testing/Cargo.toml
utp-testing/src/bin/test_suite.rs
utp-testing/src/lib.rs

old utp version
bumping it up :sunglasses:

chore: bump uTP version to v0.1.0-alpha.10

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2024-0021
https://rustsec.org/advisories/RUSTSEC-2024-0003
https://rustsec.org/advisories/RUSTSEC-2024-0019
https://rustsec.org/advisories/RUSTSEC-2024-0006

fix: fix crate vulnerabilities

---

trin-state/src/storage.rs

We had only few and the most basic tests for the StateStorage
Added more tests.

feat: improve StateStorage tests

---

Cargo.lock
ethportal-peertest/Cargo.toml
ethportal-peertest/src/scenarios/mod.rs
ethportal-peertest/src/scenarios/state.rs
ethportal-peertest/src/utils.rs
tests/self_peertest.rs

The state network didn't have any peer tests.
Added peer tests for the state network

feat: add state peertests

---

Cargo.lock
Cargo.toml
portalnet/Cargo.toml
trin-beacon/Cargo.toml
trin-history/Cargo.toml
trin-state/Cargo.toml
utp-testing/Cargo.toml

old version of uTP filled with bugs
update to version with some bugs fixed

chore: bump uTP version to v0.1.0-alpha.12

---

portal-bridge/src/bridge/history.rs

Latest bridge was randomly deadlocking. How do we know this?
- The program isn't panicing or it would exit and docker would restart it so the bridge would begin gossiping new blocks again and showing logs
```nim            
loop {
sleep(Duration::from_secs(LATEST_BLOCK_POLL_RATE)).await;
let latest_block = match self.execution_api.get_latest_block_number().await {
Ok(val) => val,
Err(msg) => {
warn!("error getting latest block, skipping iteration: {msg:?}");
continue;
}
};
```
- ^ since we get no logs, and nothing else in the loop can deadlock. `get_latest_block_number()` is the only conceivable thing that can deadlock. I am not sure why but what we know is. Nick has been running a latest bridge from infura for months without a deadlock. Which indicates this problem is specific to when we …

feat: add timeout to get_latest_block_number to prevent deadlock

---

portalnet/src/overlay/service.rs
portalnet/src/utp_controller.rs

chore: fix typo in comment

---

portal-bridge/src/bridge/history.rs

For latest content getting on the network as fast as possible is critical.
Currently we use a sequential model where we gossip: header -> block body -> receipt. But this means gossiping block body's blocks receipts from getting gossiped, which could be (not always) the difference in glados reporting a success or not
Instead of gossiping receipts after block bodies we can gossip them at the same time
**old model**
header -> block body -> receipt
**new model**
header -> block body
||||||||||||||-> receipt

feat(bridge): gossip latest block-body/receipt at the same time

---

trin-beacon/src/network.rs
trin-beacon/src/sync.rs

Beacon was trying to sync forever in an infinite loop.
Add a counter and limit beacon sync attempts to 10 with 10-sec intervals.

feat: limit beacon sync attempts

---

portal-bridge/src/gossip.rs
portal-bridge/src/stats.rs

Update gossip report logs to include a `found` field, indicating whether or not the gossip attempt aborted b/c it located the content on the network.
added `found` field to gossip report

feat(bridge): add found to gossip reports

---

portalnet/src/accept_queue.rs

This log is actually very noisy when it's being run. Turning down the log level to reduce log bloat, created issue to track investigation of the cause log noisiness (#1221)
- reduced log level

refactor: reduce noisy log level

---

portal-bridge/src/api/execution.rs

#1254 output the response from a provider for debugging purposes, but the resulting log is very noisy and clogs the logs.
reverted the change in the previous commit

refactor(bridge): remove noisy receipts response from logs

---

portal-bridge/src/cli.rs

I'm having a hard time explaining this, but our bridges are experiencing a persistent error.
```
2024-04-25T13:39:05.565172Z  WARN portal_bridge::api::execution: Failed to send request to primary provider, retrying with fallback provider: Unable to request execution payload from provider: Broken pipe (os error 32)
```
However, it's mostly on one "latest" bridge, periodically on another "latest" bridge, never on the third "latest" bridge. I've been unable to reproduce this locally, making this problem difficult to debug.
What's strange is that our bridges had never experienced this bug until #1260, when we removed the `Retry` middleware and introduced a `fallback_provider` instead. 
Yesterday, I deployed this pr to the network bridges, and didn't see any of "Broken pipe" errors for at …

bridge(fix): reintroduce retry middleware

---

portal-bridge/src/bridge/state.rs
portal-bridge/src/gossip.rs
portal-bridge/src/main.rs

Not sure how this snuck through, but `master` was broken due to conflicting pr changes

fix(bridge): broken compilation issue with bridge

---

docker/Dockerfile.bridge

fix(bridge): fix broken bridge dockerfile

---

trin-history/src/storage.rs

The history storage still uses `LegacyHistoryStore`. This will migrate it to `IdIndexedV1Store`.
Change to the `IdIndexedV1Store` implementation.
On the startup, this will perform the migration which can take few minutes (depending on the db size):
- rename table
- drop old indices
- create new indices
- Delete `LegacyHistoryStore` and related code, but leave migration code
- Delete migration code

feat: use id_indexed_v1 store for history network

---

ethportal-api/src/types/cli.rs
portal-bridge/src/cli.rs
portal-bridge/src/client_handles.rs
portal-bridge/src/main.rs

We couldn't specify which network the bridge would connect to mainnet/testnet
by adding the flag, we need this so we can launch a testnet

feat: add network flag for portal-bridge

---

book/src/developers/architecture/testing.md

chore(book): fix typo

---

book/src/developers/contributing/releases/deployment.md
book/src/developers/quick_setup.md
ethportal-api/src/types/bootnodes.rs
ethportal-api/src/types/cli.rs
ethportal-api/src/types/portal_wire.rs
ethportal-peertest/src/scenarios/basic.rs
portal-bridge/src/cli.rs
portalnet/src/discovery.rs
portalnet/src/events.rs
portalnet/src/socket.rs
tests/self_peertest.rs

we were using the wrong name (aka made one up during portal summit
by using it

feat: update testnet name to angelfood

---

Cargo.lock
portal-bridge/src/bridge/state.rs
trin-execution/Cargo.toml
trin-execution/README.md
trin-execution/src/block_reward.rs
trin-execution/src/cli.rs
trin-execution/src/config.rs
trin-execution/src/dao_fork.rs
trin-execution/src/execution.rs
trin-execution/src/lib.rs
trin-execution/src/main.rs
trin-execution/src/storage/account.rs
trin-execution/src/storage/account_db.rs
trin-execution/src/storage/evm_db.rs
trin-execution/src/storage/utils.rs
trin-execution/src/types/block_to_trace.rs
trin-execution/src/types/mod.rs

Our state execution didn't support the DAO fork. Which caused us to generate an incorrect state root and the client to crash
Our code wasn't setup to easily provide traces to debug with
By draining all the specified accounts and moving the balances to the specified account as specified in EIP-779
also by adding a cli config for tracing blocks

feat(trin execution): added support for dao fork + evm tracer

---

portal-bridge/src/client_handles.rs

Missing flags for fluffy
Added the flags

portal-bridge: Add updated network and subnetworks flags for fluffy

---

portal-bridge/README.md
portal-bridge/src/bridge/era1.rs
portal-bridge/src/types/mode.rs

Add single hunter mode so it can be more effectively deployed in our deployment scripts.

feat(portal-bridge): add single hunter mode

---

trin-execution/src/trie_walker.rs

If storage was empty we would still attempt to parse the partial storage trie, but of course that isn't possible
by adding if statements if the storage is empty skip trying to parse the trie

fix(state-bridge): if there is no storage diff to gossip continue

---

trin-execution/src/block_reward.rs
trin-execution/src/era/beacon.rs
trin-execution/src/era/types.rs
trin-execution/src/era/utils.rs
trin-execution/src/evm/block_executor.rs
trin-execution/src/evm/mod.rs
trin-execution/src/evm/post_block_beneficiaries.rs
trin-execution/src/lib.rs

trin-execution didn't support withdrawals
by implementing them

feat(trin-execution): add withdrawal support

---

portal-bridge/README.md
portal-bridge/src/bridge/state.rs
portal-bridge/src/cli.rs
portal-bridge/src/main.rs
portal-bridge/src/types/network.rs

Updated docs & minor nitpicks for running state bridge

refactor(bridge): subnetwork configuration docs

---

portal-bridge/src/bridge/beacon.rs

When a new beacon block root is finalized, we generate and gossip to the beacon network `LightClientBootstraps` and `LightClientFinalityUpdates`. Usually, bootstraps are generated first and propagated to the network. 
The problem is that the bootstrap validation is anchored to the header in the `LightClientFinalityUpdate` so to verify `LightClientBootstrap` content, we first must ensure the clients are synched and the latest `LightClientUpdate` is propagated **before** the bootstrap.
- add a 2 slots delay to `LightClientBootstrap` gossip. This should be enough for all clients to receive the finality update first and validate the bootstrap later.

feat(beacon-bridge): delay `LightClientBootstrap` gossip with 2 slots

---

src/bin/purge_invalid_history_content.rs

Broken master ci
Updated script to use correct `Subnetwork` type

fix: broken master ci

---

rpc/src/eth_rpc.rs

The `eth_call` doesn't properly handle the case when execution returns the error. Currently, it only returns empty byte array.
Transforms execution result into proper json response.

feat: eth_call should return if execution fails

---

ethportal-api/src/types/execution/header.rs

The `Header` doesn't implement the [`length`](https://docs.rs/alloy-rlp/0.3.8/alloy_rlp/trait.Encodable.html#method.length) function of the [`alloy::rlp::Encodable`](https://docs.rs/alloy-rlp/0.3.8/alloy_rlp/trait.Encodable.html) trait.
This function has default implementation, so explicit implementation is not required.
However, the [default implementation](https://docs.rs/alloy-rlp/0.3.8/src/alloy_rlp/encode.rs.html#25-29) is not optimized (it encodes the object and returns the length of the byte vector), and even the [documentation](https://docs.rs/alloy-rlp/0.3.8/alloy_rlp/trait.Encodable.html#method.length) says that it's recommended to override it.
Added private `rlp_payload_length` that calculates the length of the rlp payload (encoding without rlp header),
and use it in `encode` …

feat: implement rlp::Encodable::length for Header

---

.dockerignore

CI on master is failing
whitelisting the bin folder

fix(ci): forgot to add bin folder whitelisted in .dockerignore

---

crates/subnetworks/state/src/validation/trie.rs
crates/subnetworks/state/src/validation/validator.rs

We are in a transition period of enabling full validation for headers on the history network https://github.com/ethereum/trin/issues/1666
Since the bridges for the History network will be shutdown during this transition period, we will be disabling the State Networks requirement for History Network headers until the transition period is done
add a constant

feat: disable state network history header validation

---

crates/ethportal-api/src/types/execution/header_with_proof_new.rs

The naming scheme we used for the `HeaderWithProof` types doesn't match the [spec](https://github.com/ethereum/portal-network-specs/blob/master/history/history-network.md#block-header) and it can get very confusing. 
- Updated the names (only in the "new" `HeaderWithProof` type, don't think this is necessary for the old type we're about to sunset) and docs to match the spec.

refactor: update names to be spec compliant for new hwp

---

Cargo.lock
crates/metrics/src/history_migration.rs
crates/metrics/src/lib.rs
crates/metrics/src/portalnet.rs
crates/subnetworks/history/Cargo.toml
crates/subnetworks/history/src/storage_migration.rs

**Note**: This is built on top of #1688. That PR should be reviewed first.
We don't have good way of monitoring history migration and knowing if everything went as expected with migration. 
Added metrics and logging statements.

feat(history_migration): add history migration metrics

---

crates/portalnet/src/discovery.rs
crates/portalnet/src/events.rs
crates/storage/src/config.rs
crates/subnetworks/history/src/storage_migration.rs

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in comments

---

bin/portal-bridge/src/cli.rs
crates/ethportal-api/src/types/network.rs
crates/ethportal-api/src/types/network_spec.rs
crates/portalnet/src/bootnodes.rs
crates/utils/src/cli.rs

We didn't have a network specification for Sepolia
By adding one
- add sepolia accumulator-hashes
- calculate fork digest properly, instead of using hard coded value

feat: add sepolia network specification

---

.circleci/config.yml
docker/Dockerfile.e2hs-writer

I am going to deploy e2hs-writer so that we can maintain and always keep the list up to date https://e2hs.ethportal.net/index.html
By adding a docker image for e2hs-writer

feat: add docker image for e2hs-writer
