ethereum/trin

- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/jsonrpc.rs
- src/main.rs
Ready for review after #2 is merged
- Fixes #7 (extract jsonrpc logic into separate module)
- Fixes #5 (support custom ipc paths)
- Updated `DEFAULT_HTTP_PORT` and `DEFAULT_IPC_PATH` to be constants
> Support custom ipc paths

- README.md
- src/cli.rs
- src/jsonrpc.rs
There will be ports used on both the p2p endpoint and the json-rpc
endpoint. It's too ambiguous to have a CLI argument of simply "http
port".
Also, single-letter flags are too short to handle the argument
complexity that's coming. Not to mention that we should not overwrite
the -h (help) arg.
> Rename CLI arguments for disambiguation

- src/alexandria/discovery.rs
- src/alexandria/protocol.rs
- src/alexandria/types.rs
- src/main.rs
This makes for an easier cross-client ping test. Once the handshake is working, the intention would be to immediately start populating the buckets for the overlay network.
Also, fix bug where ENR sequence was only 32 bit.
It should be 64-bit according to discv5 and the spec: 
https://github.com/ethereum/devp2p/blob/6eddaf50298d551a83bcc242e7ce7024c6cc8590/enr.md
> Try to ping the bootnodes on the overlay network, at launch time

- src/cli.rs
- src/main.rs
Bonus: switch the http port to `uint16`, which is sufficient for network ports.
> Configure p2p port and bootnode ENRs via command line

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/main.rs
The `tracing` package doesn't use `env_logger` rules by default. We need to initialize it.
Includes two bonus fixes:
- when `--bootnodes` is empty, or includes empty entries, don't crash
- run until ctrl-c properly, instead of just a very long sleep
> Log discv5 to stderr

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/portalnet/discovery.rs
- src/portalnet/mod.rs
- src/portalnet/protocol.rs
- src/portalnet/socket.rs
Closes #23 
- Bind against 0.0.0.0 instead of loopback: Binding to 127.0.0.1 prevents messages from properly sending to a non-loopback address
- Use external STUN server to populate IP & port in the initial ENR
- If STUN check fails, pick a local IP addr for the ENR. That way, you can use the encoded ENR immediately from another (local network) peer
> STUN support

- src/portalnet/protocol.rs
> I probably missed something dumb when I ported to the beta, let me take a look.
Yes, I did something really dumb.
> Fix startup order for discv5 event stream (closes #37)

- Cargo.lock
- Cargo.toml
- src/jsonrpc.rs
- src/main.rs
- src/portalnet/protocol.rs
Added a [message channel](https://tokio.rs/tokio/tutorial/channels) to serve portal protocol requests over jsonrpc. My first time implementing something like this in rust, so hopefully it's not too clunky.
Added support for a couple basic admin endpoints `discv5_nodeInfo` and `discv5_routingTableInfo`
> Add message channel to serve portal jsonrpc requests

- .circleci/config.yml
- Cargo.toml
- src/jsonrpc.rs
- src/portalnet/socket.rs
So currently two parts of the code only support Unix. Most notably is the interfaces library and currently, the std::net library doesn't support Unix domain socket server on windows which was added to windows in 2018. So I wrote windows equivalent functions using libraries that support windows.  I also added a circleci build to test if Trin builds to Windows, I assume we could also add a cross-compile for MacOS in the future.
I think Trin being cross-platform would be important in the future if it ever hits production. Also I use Windows as my host platform so it would be nice if I could build trin natively.
Original post which was way too long: https://hastebin.com/opewikujef.sql
> Add support for compilation to windows

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/portalnet/discovery.rs
- src/portalnet/protocol.rs
- src/portalnet/types.rs
As mentioned in https://github.com/carver/trin/issues/32, it is good idea to use `StructOpt` for parsing cli arguments into `TrinConfig`.
Fixes #32
> Add StructOpt for CLI parsing

- README.md
- src/portalnet/protocol.rs
- src/portalnet/utils.rs
This PR just adds default data directories that are used if ``TRIN_DATA_PATH`` (the replacement for ``TRIN_DB_PATH``) isn't set.
```
// Windows: C:\Users\Username\AppData\Roaming\Trin
// macOS: ~/Library/Application Support/Trin
// Unix-like: ~/.trin
```
These are the default data directories for each respected operating system. Just the standard locations with each operating system and normal naming scheme (caps or no caps etc)
> Add default data directory

- Cargo.lock
- trin-core/src/cli.rs
- trin-history/Cargo.toml
- trin-history/src/lib.rs
- trin-history/src/main.rs
- trin-state/src/lib.rs
- trin-state/src/main.rs
Bootstrap `trin-history` network by changing the default ports to not match `trin-state`. It also adds method to display the config values.
This is a hack until we make StructOpt handle CLI simultaneously for both networks.
> Bootstrap trin-history network on separate ports

- .circleci/config.yml
Clippy now only checks the trin crates - reduces job time from ~8mins to ~8secs
Fixes #71 
From circle output
```
Checking trin-core v0.1.0 (/home/circleci/project/trin-core)
Checking trin-state v0.1.0 (/home/circleci/project/trin-state)
Checking trin-history v0.1.0 (/home/circleci/project/trin-history)
Checking trin v0.1.0 (/home/circleci/project)
```
> Reduce clippy to only run for trin

- trin-core/src/socket.rs
Windows CI builds are working again and Clippy had a few errors, so I just fixed that.
#75 The errors can be seen in the CI build for this PR
> Fix windows clippy errors

- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/protocol.rs
This is something I added to one of my branches, but I thought I might as well make a PR for it because I think it will be quite useful for upcoming protocols also my uTP code will use this so I might as well get it in just so it is already there because I might not be PR'ing that for a while longer.
> Added protocol param to send_talkreq()

- README.md
- trin-core/src/utils.rs
same changes as this [PR](https://github.com/carver/trin/pull/68) but I removed the superfluous "merge" commits so now it's just one commit.
> add default data path for unix to README and comments

- trin-core/src/portalnet/protocol.rs
- trin-core/src/utils.rs
- trin-history/src/lib.rs
- trin-state/src/lib.rs
Sometimes, we may want to initialize a portal net protocol without jsonrpc support (for example when running tests or creating "dummy" node).
It will be also good if we can run multiple portal protocol instances simultaneously (for testing req/resp network calls). The current default db folder structure prevent this, because there is a db collusion between the different instances.
This PR removes jsonrpc dependency from PortalnetProtocol struct and adds last 8 chars from local base64 encoded Enr as a suffix to the default data application folder.
> Remove jsonrpc dependency from PortalnetProtocol struct and change default folder name

- Cargo.lock
- trin-history/Cargo.toml
- trin-history/src/lib.rs
- trin-history/src/types/header.rs
- trin-history/src/types/mod.rs
Add block header structure in a new `types` module in the `trin-history` crate. The implementation includes methods for RLP encoding and decoding. The implementation and unit tests were derived from [OpenEthereum](https://github.com/openethereum/openethereum/blob/main/crates/ethcore/types/src/header.rs).
We port the block header implementation to `trin` because the [OpenEthereum project is being deprecated](https://medium.com/openethereum/gnosis-joins-erigon-formerly-turbo-geth-to-release-next-gen-ethereum-client-c6708dd06dd).
> Add block header structure

- .circleci/config.yml
- Cargo.toml
- trin-core/src/cli.rs
By removing `default-members` section from the root Cargo.toml, `cargo test` in CircleCI is not able to detect all the tests in the crates.
This PR adds explicit `cargo test --workspace` command which will run tests on all workspace members in CIrcleCI pipeline. It also fixes some failing tests on master.
> Fix failing tests on master

- Cargo.lock
- trin-core/Cargo.toml
- trin-core/src/jsonrpc.rs
- trin-core/src/portalnet/protocol.rs
Adds support for parsing parameters for the JSON-RPC call.
Fixes https://github.com/ethereum/trin/issues/96
> Add params member to JSON-RPC request

- Cargo.lock
- src/main.rs
- trin-core/Cargo.toml
- trin-core/src/cli.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/protocol.rs
- trin-core/src/portalnet/utp.rs
- trin-core/src/utils.rs
- trin-history/Cargo.toml
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/Cargo.toml
- trin-state/src/lib.rs
- trin-state/src/network.rs
This introduces some new abstractions for the overlay networks:
```rust
// Base Discovery layer
pub struct Discovery {
/// discv5 protocol
pub discv5: Discv5,
/// Indicates if the discv5 service has been started
pub started: bool,
/// listen port for the discovery protocol
pub listen_socket: SocketAddr,
}
// Overlay layer, should be used by every network
pub struct OverlayProtocol {
// Contains discovery layer
pub discovery: Arc<RwLock<Discovery>>,
// The data radius of the local node
pub data_radius: Arc<RwLock<U256>>,
// The overlay routing table of the local node.
pub kbuckets: Arc<RwLock<KBucketsTable<NodeId, Node>>>,
}
// Network specific layers, currently contain only the overlay protocol
pub struct HistoryProtocol {
pub overlay: Arc<OverlayProtocol>,
}
pub struct StateProtocol { …
```
> Overlay network refactoring

- Cargo.lock
- Cargo.toml
- src/main.rs
- trin-core/src/jsonrpc/handlers.rs
- trin-core/src/jsonrpc/mod.rs
- trin-core/src/jsonrpc/service.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/mod.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/protocol.rs
- trin-core/src/portalnet/types.rs
- trin-history/src/events.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/events.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
This is PR following https://github.com/ethereum/trin/pull/103.
It adds support for running event handlers for state and history network in parallel.
The general idea is to have one main portal network event handler and a network event handler per network.
The main event handler will dispatch via unbounded channels all events to the specific network handlers by checking the `protocol` header in discv5 `talk_req`.
This implementation was tested with the dummy node from the testing framework branch by sending three ping requests, one for every network(state, history) and one for a network we don't support. Here are the results:
```rust
Sep 20 13:02:16.534  INFO trin_core::cli: Protocol: ipc
IPC path: /tmp/trin-jsonrpc.ipc    
Sep 20 13:02:16.534  INFO trin_core::cli: Pool Size: 2    
Sep 20 …
```
> Handle overlay network events

- trin-core/src/portalnet/overlay.rs
- trin-history/src/network.rs
- trin-state/src/network.rs
Add constructor for `OverlayProtocol` to remove redundant logic and make `OverlayProtocol` responsible for creation of `KBucketsTable`.
> Add OverlayProtocol constructor

- src/main.rs
- trin-core/src/utils.rs
- trin-history/src/lib.rs
- trin-state/src/lib.rs
Implements @ogenev's initial thoughts from #81.
Uses the first 8 characters of the Node ID's base 10 representation.
Any thoughts on whether we may want hex instead, or less than 8 characters?
> Modifies get_default_data_dir to take node id instead of enr

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- ethportal-peertest/README.md
- ethportal-peertest/src/cli.rs
- ethportal-peertest/src/events.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/main.rs
Following the discussion on https://github.com/carver/trin/issues/50, this is an experimental crate with a dummy node that sends request messages to a target node ( a node under test). A dummy peer is a minimal bare-bones node that is capable of executing request to a remote node and receive a response.
This crate may be useful for testing how a portal node responds to different network calls.
Current implementation is very primitive, it is just sending two ping requests to state and history network. This can be expanded by adding JSON-RPC API that will execute different test suite scenarios on the target node.
_JSON-RPC commands are not supported for now. I think we should first refactor the json-rpc code in `trin-core`, so we can make those parts reusable._
> Portal network cross-client testing framework

- trin-core/src/cli.rs
I wanted to change the port my node was listening to and after skimming
through the output of --help I tried to do so using the
--external-address flag. It turns out this is not the correct flag to
use!
While the previous help string hinted at the behavior of this flag the
new one should help to prevent future confusion.
> doc - update --external-address helpstring

- trin-core/src/jsonrpc/service.rs
In order to communicate to our http server from outside of a docker container, we need to bind to `0.0.0.0` rather than `127.0.0.1`. Though, I'm not sure if this opens up some security vulnerabilities as the new default? And instead should be controlled via cli flag / env var?
> Update localhost address for use in docker container

- CONTRIBUTING.md
Add guideline to contributing guidelines about using custom error types rather than `String`s.
> Add guideline about using custom error types

- Cargo.lock
- trin-core/Cargo.toml
- trin-core/src/utils/hash_delay_queue.rs
- trin-core/src/utils/mod.rs
Add a `HashDelayQueue` struct that can act as a generator that yields "expired" items. This struct is intended for the implementation of routing table management. With a `HashDelayQueue`, we can insert keys with a given timeout or delay, and when polled, the delay queue will yield an expired item (if one exists).
* Create a directory for the `trin_core::utils` module.
* Create a `HashDelayQueue` utility in the `trin_core::utils` module.
> Add HashDelayQueue utility

- CONTRIBUTING.md
- Cargo.lock
- ethportal-peertest/Cargo.toml
- ethportal-peertest/README.md
- ethportal-peertest/src/cli.rs
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/main.rs
- trin-core/src/cli.rs
- trin-core/src/jsonrpc/service.rs
First steps towards a more robust test harness. For some reason, the overlay network pings seem to be broken. I dug into it a bit, but couldn't quite figure out the solution. It also seems like either https://github.com/ethereum/trin/pull/141 might help the situation, or at least help with debugging the situation. Tracking that in this issue https://github.com/ethereum/trin/issues/147
Fixes #4
> Add http/ipc jsonrpc testing to harness

- .circleci/config.yml
- Cargo.lock
- trin-state/Cargo.toml
- trin-state/src/lib.rs
- trin-state/src/network.rs
- trin-state/src/trie.rs
Include the new eth-trie, and add a `TrieDB` that implements the trie's DB trait for rocksDB.
> Use newly-released eth-trie

- .circleci/config.yml
- trin-core/src/cli.rs
- trin-core/src/portalnet/overlay.rs
- trin-state/src/utils.rs
This change probably looks a little surprising in isolation. Right now it causes an extra clone (because we were previously able to move in a vector that now has to be cloned inside the method).
Here is a super draft-y PR to help show the context of where I think it makes more sense:
https://github.com/ethereum/trin/pull/166/files#diff-fd7cee899607b5a0b4e30853e7bb9f8a191ed26926c7724f6b66d3070f62cf56R67-R72
Also, at some point, it should be possible to build the request from a slice without copying it first. It just doesn't seem like a priority now. But we might as well prepare the API to head that direction IMO. As always, open to discussion.
> Prefer slice argument when passing in content key

- trin-core/src/socket.rs
Devops helped set up a stun server as part of the testnet infrastructure which is a more stable solution than the stun server we've been using. Everything appears to functional for me, but another confirmation that the new stun server is functional would be great. @carver you can go ahead and tear down the stun server you setup locally if you'd like.
fixes #25
> Update stun server

- README.md
- ethportal-peertest/src/cli.rs
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/main.rs
- trin-core/src/cli.rs
- trin-core/src/jsonrpc/service.rs
Updates cli arg `web3-http-port` to `web3-http-address` - useful for use with docker container to allow using `0.0.0.0` as the ip address. 
Fixes #129
> Update web3-http-port to web3-http-address

- .circleci/config.yml
See https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html
> Use rust v1.56.1 to mitigate "Trojan Source"

- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/events.rs
- trin-core/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
Update test harness handler with protocolid introduced in https://github.com/ethereum/trin/pull/162 and bump all crates rust version to 1.56.1 (related to https://github.com/ethereum/trin/pull/173).
> Update protocol id match in test harness handler

- ethportal-peertest/src/events.rs
- ethportal-peertest/src/main.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/mod.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types.rs
- trin-core/src/portalnet/utp.rs
- trin-history/src/events.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/network.rs
- trin-state/src/events.rs
- trin-state/src/jsonrpc.rs
- trin-state/src/network.rs
Related to #135. Move message dispatch and handling into `OverlayService`. The `Overlay` communicates with the associated `OverlayService` via a channel.
Motivation: Autonomous routing table management requires a separate task where the task must have a mutable reference to the overlay structure. We create a new overlay structure, `OverlayService`, and communication between this structure and `Overlay` occurs over a channel, which does not require a reference.
> Add overlay service to dispatch and handle requests

- Cargo.lock
- Cargo.toml
- trin-cli/Cargo.toml
- trin-cli/README.md
- trin-cli/src/main.rs
This is a much less ambitious version of #169 and replaces it.
Example output: 
```
$ cargo run -p trin-cli -- discv5_routingTableInfo
Attempting RPC. endpoint=discv5_routingTableInfo file=/tmp/trin-jsonrpc.ipc
{
"id": 0,
"jsonrpc": "2.0",
"result": {
"buckets": [
[
"0xa133..79e2",
"enr:-IS4QBD940ObAwu3B4K1ddW15ohedlJW96z04vmJ3W9nKwsOOsQVsN_OZUTLH6zYJrq7GknkHQQ1r24zlSBr6aT6MngBgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQNPYMlwKY62uH1WcO38VPTHHHD1CSHPJblkwxvbiwKXW4N1ZHCCEdg",
"Connected"
]
],
"localKey": "0x1c74..82db"
}
}
```
(the first line is emitted to stderr, so the output of this command can be piped into jq)
> Add little command for easy access to JSON-RPC interface

- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/main.rs
- src/main.rs
- trin-core/Cargo.toml
- trin-core/src/jsonrpc/handlers.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/utp.rs
- trin-history/Cargo.toml
- trin-history/src/jsonrpc.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/Cargo.toml
- trin-state/src/events.rs
- trin-state/src/jsonrpc.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
So I've been trying to get trin to talk to itself. I was running into something that looks like a deadlock. Locks, especially spread across a codebase, are a huge PITA to debug. Rather than do the first of many painful lock debug sessions, I wanted to see what it would look like to get rid of them.
It may be doable, but let's chat about it!
---
This requires some API updates to sigp/discv5. The good news is that the change is just to re-frame a bunch of methods as borrow instead of mutable-borrow. Then sharing the discovery instance will be trivial.
This seems to be a trivial change to discv5, because most of the internal variables are in a `RwLock` anyway.
> Run Discovery and StateNetwork without locks

- ethportal-peertest/src/jsonrpc.rs
There was some situation where trin was not responding to IPC calls. In that case, ethportal-peertest was hanging indefinitely instead of failing. So, add a timeout when reading from the socket.
Also, print some useful info to stderr.
Also, remove a test that hits Infura, before we start using it in CI.
> Add IPC timeout to ethportal-peertest

- trin-cli/Cargo.toml
- trin-cli/README.md
- trin-cli/src/main.rs
Adds capability for a single parameter to cli tool. It's been tested against `portal_statePing` in #188 .  Obviously, a more robust scheme with multiple parameters is ideal, but I held off on that for now since we don't have any jsonrpc endpoints with multiple params to test against.
> Add parameter to cli tool

- trin-history/src/events.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
With the latest `discv5` library, we no longer need to use locks on overlay networks. fixes #190
> Remove unnecessary rwlock from history network

- Dockerfile
- trin-cli/src/main.rs
- trin-core/src/cli.rs
A couple minor bugfixes for using `trin-cli` inside a docker container
- Make `--params` arg optional 
- Add copy `trin-cli` binary to dockerfile
> Add trin cli binary to dockerfile

- ethportal-peertest/src/jsonrpc.rs
- tests/self_peertest.rs
- trin-core/src/jsonrpc/service.rs
Fix #196 
Includes a refactor to reduce duplicate code when making IPC requests from peertest. Also, was crashing when ctrl-c was registering twice (on the 2nd trin run).
Note that we're not actually returning the correct values for portal_*Ping json requests, but that belongs in a separate issue (#198). This PR is just about building the structure necessary to run two copies of trin and trigger messages between them.
> Re-enable ping peertests

- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/types/messages.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
- Add support for `portal_stateFindNodes(enr, distances)`/`portal_historyFindNodes(enr, distances)` jsonrpc endpoint
- Implement some helper traits on `SszEnr` for cleaner param conversion
- Add validation methods to `send_find_nodes()` according to the [spec](https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md#find-nodes-0x02)
> Overlay nodes

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- trin-core/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
> Update Discv5 version

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- ethportal-peertest/src/jsonrpc.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
What does this PR do:
- Add new `CustomPayload` struct
- Add support for custom payload param of `historyPing` and `statePing` JSON-RPC
- Implement `CustomPayload` struct in overlay Ping/Pong messages. This required some custom SSZ decode/encode implementation, so we can match the test vectors.
Fixes https://github.com/ethereum/trin/issues/203
> Implement `custom_payload` element of overlay Ping/Pong JSON-RPC params

- ethportal-peertest/src/jsonrpc.rs
- trin-core/src/portalnet/types/messages.rs
Return JSON Value from Pong ssz bytes on json-rpc portal_*Ping requests and update tests.
Fixes https://github.com/ethereum/trin/issues/198
> Make Ping JSON-RPC result human readable

- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/utils/bytes.rs
- trin-core/src/utils/distance.rs
Modify XOR distance function to operate on length 32 byte arrays.
All distance computations should operate on 32-byte (256-bit) values. With this modification, we can remove unnecessary error handling and type conversions. I went with big-endian in this implementation, but if desired, I could add an additional parameter to specify endian-ness.
I think this is the general form that a `Distance` trait should take. I chose not to define that trait here, and defer it to a later PR.
> Modify XOR distance function to operate on length 32 byte arrays

- trin-core/src/lib.rs
- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/mod.rs
- trin-core/src/utp/mod.rs
- trin-core/src/utp/packets.rs
- trin-core/src/utp/stream.rs
This PR refactors uTP into its own folder, which has been requested numerous times.
It also cleans up a lot of await calls and runs the send talkreq in a tokio::spawn
It also corrects the finalization packet response type
> Refactor uTP and clean up async/await

- Cargo.lock
- trin-core/Cargo.toml
- trin-core/src/portalnet/types/content_keys.rs
- trin-core/src/utils/content_key.rs
This modifies the tests to conform to the test vectors here: https://github.com/ethereum/portal-network-specs/blob/master/content-keys-test-vectors.md.
Minor changes were made to the hash functions to conform to the updated spec as well.
Also it combines the test for encoding/decoding of key x and converting key x to the respective id into a single test. This reduces lines of code by a lot and also possibility for error.
> Modify content-key tests to conform to content keys test vectors spec

- Cargo.lock
- src/lib.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/uint.rs
- trin-core/src/utils/mod.rs
- trin-core/src/utils/node_id.rs
- trin-history/src/lib.rs
- trin-state/src/lib.rs
Implements bucket refresh lookup algorithm for base discv5 layer. It is using the same logic as described in https://github.com/ethereum/trin/pull/213.
- `generate_random_node_id` method has been extracted in the `utils` module, so it can be used in both discv5's `discovery` and `overlay_service`.
Fixes https://github.com/ethereum/trin/issues/223
> Discv5 bucket refresh lookup

- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/utp/packets.rs
- trin-core/src/utp/stream.rs
This is the first PR of a series of PRs to refactor the uTP implementation and fix some of the uTP bugs.
This PR includes a simple renaming of some of the variables, methods and adding comments to improve code readability and debugging. This PR doesn't change any functionality.
It is using the uTP [library](https://github.com/meqif/rust-utp) implemented in Rust for reference.
> Rename refactoring and add comments to uTP

- trin-core/src/portalnet/overlay_service.rs
- trin-core/tests/overlay.rs
Closes #205.
Add logic to process ENRs contained `Nodes` and `Content` responses. We attempt to insert newly discovered nodes into the routing table. If successful, we insert those nodes into the ping queue to establish an outgoing connection. For ENRs that we already have in the routing table, we attempt to update the local routing table entry if the ENR sequence number in the response is higher than what we have locally in the corresponding entry.
Add integration test in `trin-core` to test core overlay routing table logic according to various messages exchanged between a set of nodes. If desired, this piece of the PR can be separated out into its own PR.
> Add processing for nodes discovered from Nodes and Content

- trin-core/src/utp/packets.rs
- trin-core/src/utp/stream.rs
The goal of this PR is to refactor the way we are accessing the packet header. This accomplishes a few things:
- When setting the header fields, there is no need to pass the header around, we can set them on the packet, for example as `packet.set_seq_nr()`
- This refactoring allows us to set the packet header timestamp fields right before sending a packet without adding boilerplate code and it is fixing the issue where a packet timestamp was not sent when we resend a packet.
- Improves code readability
Uses [rust-utp](https://github.com/meqif/rust-utp) as referance.
> Refactor uTP packet header

- Cargo.lock
- trin-core/Cargo.toml
- trin-core/src/utp/bit_iterator.rs
- trin-core/src/utp/mod.rs
- trin-core/src/utp/packets.rs
- trin-core/src/utp/stream.rs
This PR is part of phase 1 defined in https://github.com/ethereum/trin/issues/232#issuecomment-1033862510.
It tries to accomplish the following:
- refactor uTP packet extension by creating `ExtensionType` object and iterator.
- update `set_selective_ack` method to match the new extension type
- change `send_window` from HashMap to Vec;
- add `advance_send_window` method to improve and encapsulate current advance window logic
- add more unit tests
Those changes bring us one step closer to having 1:1 core uTP implementation with rust-utp.
> Refactor uTP packet extensions

- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utils/node_id.rs
- trin-core/src/utp/stream.rs
What does this PR do:
- refactors the uTP packet handler by adding two more socket states: `FinSent` and `ResetReceived`. This allows us to cover more corner cases when receiving uTP packets depending on the current socket state.
- adds unit tests for the core uTP logic :tada: 
This is the last PR of Phase 1 in https://github.com/ethereum/trin/issues/232#issuecomment-1033862510. :heavy_check_mark:
> Refactor uTP packet handler and add tests

- docs/contributing.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
- trin-core/tests/overlay.rs
- trin-history/src/content_key.rs
- trin-history/src/events.rs
- trin-state/src/content_key.rs
- trin-state/src/events.rs
1. `Message` did not implement SSZ `Encode` and `Decode`.
2.  `Message` implemented custom `to_bytes` and `from_bytes` methods.
1. Unite all Portal message variants in `Message` and derive SSZ `Encode` and `Decode`.
2. Implement `Into<Vec<u8>>` and `TryFrom<Vec<u8>>` for `Message`.
> Refactor Message

- Makefile
- pyproject.toml
- trin-core/src/portalnet/storage.rs
These are just a couple of bugfixes/improvements I'd like to get into `master`. They popped up while trying to cut a first release. First release status is potentially on hold for now. There's something about patching in @ogenev 's `discv5` branch that `cargo-release` doesn't pick up on when packaging each crate individually - which results in a compile error since it reverts to `discv5 = 0.13.0-beta`. There definitely might be a workaround, but I wasn't able to find one. Ultimately, it seems to me like patches are intended for quick-fixes, and not a sustainable dependency. It also seems like fairly clean code habit to not cut any releases that rely on a patch. Tbh, a technical first release is not immediately urgent, but it does seem worthwhile to get those patched fixes in to `discv5`. …
> Misc improvements

- src/bin/seed-database.rs
- trin-core/src/bin/generate-data.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/portalnet/types/content_key.rs
- trin-core/tests/overlay.rs
The `content_id` method for `MockContentKey` always returns a zeroed byte array. In other words, the `content_id` method is the zero function. This is not so useful for testing.
Replace `MockContentKey` with `IdentityContentKey`, where the `content_id` method is the identity function with respect to the value within the content key. This allows us to create content keys with arbitrary content IDs.
> Replace MockContentKey with IdentityContentKey

- Cargo.lock
- Cargo.toml
- newsfragments/266.removed.md
`cargo clippy` shows the following warnings:
- warning: trin v0.1.0 (...) ignoring invalid dependency `cargo-release` which is missing a lib target
- warning: trin v0.1.0 (...) ignoring invalid dependency `trin-cli` which is missing a lib target
Remove `trin-cli` and `cargo-release` package from `Cargo.toml` dependencies because those packages are not libraries.
> Fix cargo clippy warnings

- Cargo.lock
- Cargo.toml
- newsfragments/248.added.md
- newsfragments/248.changed.md
- src/lib.rs
- trin-core/Cargo.toml
- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utp/stream.rs
- trin-core/src/utp/trin_helpers.rs
- trin-core/src/utp/util.rs
- trin-core/tests/overlay.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
- utp-testing/Cargo.toml
- utp-testing/README.md
- utp-testing/src/main.rs
To be able to write meaningful unit tests and build the uTP testing framework, we want to encapsulate the uTP module and consume the uTP socket packets.
- Implemented uTP socket `recv()` and `close()` methods that allows us to handle a uTP packet from the discv5 socket, consume the result and gracefully close the uTP connection, so it  works now as a standard socket call, for example, we can say:
```rust
client.send_to(..);
server.recv(..);
client.close()
```
- added a simple uTP testing code just to make sure we can transfer data between two uTP implementations without any known issues.
- added test for triple ack response
This PR is completing Phase 2 in https://github.com/ethereum/trin/issues/232#issuecomment-1033862510.
> Implement uTP socket recv() method and init uTP testing framework

- trin-core/src/portalnet/find/iterators/findnodes.rs
- trin-core/src/portalnet/find/iterators/mod.rs
- trin-core/src/portalnet/find/mod.rs
- trin-core/src/portalnet/find/query_info.rs
- trin-core/src/portalnet/find/query_pool.rs
This PR adds relatively generic utility types used for iterative FindNodes/FindContent implementations, mostly taken from https://github.com/sigp/discv5/blob/master/src/query_pool.rs with some customizations/re-organization done. 
Customizations include:
- Stripping out of `PredicateQuery` types. These allowed one to specify an arbitrary filter to run over ENRs discovered. Removing this type is the reason for the compiler currently requiring `PhantomData` fields in `query_pool.rs`, because the `PredicateQuery` definition used the `TResult` field while the `FindNodeQuery` definition does not.
- Modify `QueryInfo` to use `Trin` types when generating requests instead of `sigp/discv5' types.
The main types defined are the `QueryPool` type, the `Query` type (both defined in …
> Adds modified versions of QueryPool, Query types from sigp discv5

- newsfragments/270.added.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utp/stream.rs
- trin-core/src/utp/trin_helpers.rs
FindContent/Content uTP scenario was not implemented.
- Implemented uTP stream for FindContent/Content.
- Some unnecessary uTP logs where deleted.
The current implementation is manually tested with Fluffy in both directions.
Those should be added in later PRs, as I would like to test Offer/Accept uTP next:
- write uTP bi-directional test (when we want to send DATA packet right after SYN-ACK).
- Return content data instead of connection-id  to json-rpc client when we send FIndContent request and uTP stream is initialized.
> Implement FindContent <-> Content uTP stream

- newsfragments/278.fixed.md
- trin-core/src/portalnet/storage.rs
- trin-core/src/utils/db.rs
- trin-state/src/network.rs
@hmrtn pointed out that  `get_data_dir` was incorrectly namespaced under `/rocksdb` - when it should be returning simply the `/trin_xxxxx` directory.
Moved the `/rocksdb` namespacing to its appropriate location.
> Bugfix data dir setup

- newsfragments/275.added.md
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
- trin-core/src/utp/stream.rs
- trin-core/src/utp/trin_helpers.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
- utp-testing/src/main.rs
-  Offer/Accept implementation was not tested.
- `portal_*Offer` json-rpc endpoint was not implemented.
- Manually tested Offer/Accept uTP stream in both directions with Fluffy and fixed all known issues.
- Implemented `portal_*Offer` json-rpc endpoint.
> Refactor OFFER/ACCEPT uTP stream and add `portal_*Offer` json-rpc endpoint

- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utils/node_id.rs
We unnecessarily wrap return type for random `NodeId` generation function in `Result`.
Remove `Result` wrap from return type.
> Remove Result wrap of return type in random NodeId gen

- newsfragments/293.fixed.md
- trin-core/Cargo.toml
- trin-core/src/types/header.rs
the old web3's decoded response to `eth_getBlockByHash`...
```
AttributeDict({'author': '0x2a65aca4d5fc5b5c859090a6c34d164135398226',
'base_fee_per_gas': None,
'difficulty': 7767604946080,
'extra_data': [215,
131,
1,
3,
2,
132,
71,
101,
116,
104,
135,
103,
111,
49,
46,
53,
46,
49,
133,
108,
105,
110,
117,
120],
'gas_limit': '0x2fefd8',
'gas_used': '0x5208',
'log_bloom': '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
> Properly serialize extra data bytes in header

- newsfragments/283.added.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/utp/stream.rs
- uTP socket `recv_from` method was missing
- Adding `recv_from` method allow us to receive all streamed uTP data to a write buffer:
```rust
let mut buf = [0; BUF_SIZE];
socket.recv_from(&mut buf).await
```
> Add uTP `recv_from` method and more uTP tests

- newsfragments/294.fixed.md
- trin-core/src/utils/db.rs
@hmrtn pointed out that using `TRIN_DATA_PATH` environment variable was broken.
- Use `Path` to handle env var paths with & without a trailing slash (`./path/to/db` & `./path/to/db/`)
- Updates default data dir to namespace under `/trin`. Previously, all of the `trin_xxxxx` directories were just stored under the default data dir.
> Fix data dir setup

- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/main.rs
- newsfragments/295.fixed.md
- tests/self_peertest.rs
`ethportal-peertest` had a big flaw, you could only run one test per jsonrpc endpoint. This is not ideal, since we'll want to run multiple tests for various functionality against a single endpoint.
Reconfigured the test architecture to allow for multiple tests against a single endpoint. Furthermore, included some refactoring that will later allow us to introduce more complex tests (eg, a single test composed of multiple jsonrpc requests - which will be useful in testing content, iterative find nodes, and iterative find content...). It's not fully implemented here, but all the "validation functions" will need to perform these tests is whether to use `make_ipc_request` or `make_http_request` (aka, access to the `portalnet_config`) and then they can encapsulate any logic needed to perform …
> Reconfigure ethportal test structure

- Dockerfile
`utp-testing` crate wasn't added to Dockerfile, so compilation failed.
Added `utp-testing` crate to Dockerfile
> Add utp-testing crate to Dockerfile

- newsfragments/288.fixed.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/utp/stream.rs
Fixes https://github.com/ethereum/trin/issues/288
Wait for the uTP socket to receive the data stream to end and return it.
Before:
```j
{"jsonrpc":"2.0","id":86,"params":["enr:-IS4QDhGlinG83cF82q_1xr-QFwovgP_xOrMsOLCxagon4dJCCk3uixRepA-V_tehSb2ys5qaHKD2Vj4CkuMtUK-LQYBgmlkgnY0gmlwhMCoZD2Jc2VjcDI1NmsxoQIUBbeSac7_fnelMhiV6Bs22eRlEwPCuQn67TyEEhVV74N1ZHCCIzE", "000f00d1c390624d3bd4e409a61a858e5dcc5517729a9170d014a6c96530d64dd8621d"],"method":"portal_historyFindContent"}
{"id":86,"jsonrpc":"2.0","result":{"connection_id":50305}}
```
Now:
``` j
{"jsonrpc":"2.0","id":86,"params":["enr:-IS4QDhGlinG83cF82q_1xr-QFwovgP_xOrMsOLCxagon4dJCCk3uixRepA-V_tehSb2ys5qaHKD2Vj4CkuMtUK-LQYBgmlkgnY0gmlwhMCoZD2Jc2VjcDI1NmsxoQIUBbeSac7_fnelMhiV6Bs22eRlEwPCuQn67TyEEhVV74N1ZHCCIzE", …
```
> Handle received uTP data stream in FindContent/Content

- README.md
- docs/getting_started.md
The README and getting started docs could use some revisions.
- Trim down the README.
- Clean up formatting.
- Add more comments on commands.
- Remove CLI option section in favor of command to display CLI options.
- Remove boot node list in favor of link to portal network specs boot node list.
- Move "gotchas" from README to getting started.
> Update README and getting started docs

- Cargo.lock
- newsfragments/304.changed.md
- src/lib.rs
- trin-core/src/portalnet/events.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utp/stream.rs
- trin-core/tests/overlay.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
- utp-testing/Cargo.toml
- utp-testing/src/main.rs
The portal overlay layer communicates with uTP listener with locks which causes some of the locks to wait for too long.
FIxes https://github.com/ethereum/trin/issues/302
- Implement  Overlay <-> uTP listener communication via a channel and remove the locks.
- `UtpListener` now runs as a self-contained service in the background and waits for requests from the overlay layer.
Those changes bring a performance boost and reduce the number of log warnings about locks held.
> Add overlay layer <-> uTP listener communication channel instead of locks

- ethportal-peertest/README.md
- ethportal-peertest/src/lib.rs
- newsfragments/286.fixed.md
- newsfragments/309.added.md
- src/lib.rs
- tests/self_peertest.rs
- trin-core/src/cli.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
- trin-core/src/socket.rs
- trin-core/src/utp/stream.rs
- trin-core/tests/overlay.rs
- utp-testing/src/main.rs
An alternative fix #286
This fits with the discv5 validation, which hangs up on clients
immediately if the ENR IP does not match the observed IP.
Also, had to update a couple tests to configure local IPs so they can
contact each other. (The internal IP feature randomly chose a local
IP, which caused the discv5 validation to reject the local connections)
> Leave IP out of ENR by default

- newsfragments/312.fixed.md
- trin-core/src/utp/stream.rs
- utp-testing/src/main.rs
Fixes https://github.com/ethereum/trin/issues/312
1. Create a uTP stream with an internal discv5 packet channel.
2. Every time when we handle a uTP packet, we check for an existing uTP connection matching the remote NodeId and received connection id, and then we send the packet to the corresponding internal uTP stream channel.
3. Refactor RESET packet uTP listener handler.
4. Fix broken local utp-testing execution caused by https://github.com/ethereum/trin/pull/309.
> Handle concurrently multiple uTP streams

- README.md
Fixes https://github.com/ethereum/trin/issues/329
Update Discord link to non-expire
> Set non-expire Discord link in README

- ethportal-peertest/src/jsonrpc.rs
- newsfragments/334.fixed.md
- newsfragments/334.internal.md
- trin-core/src/jsonrpc/types.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/utils/bytes.rs
- trin-core/src/utils/db.rs
When doing manual testing to push content with `portal_historyStore`, I was getting the error "Unable to decode content_key".
I thought that was a bytes -> key issue, but it was actually a hex -> bytes issue. I updated the error message to be a bit more clear on that point.
It looks like most of the json-decoding was assuming hex without a prefix. The portal json-rpc spec has all content starting with 0x, so this was a bug to fix.
- Added a new `hex_decode` which strips away the "0x" -- plus a little hacky error if it's not there.
- Use the `hex_decode()` method instead of `hex::decode()` (which can't handle a prefix), basically everywhere in the json-rpc type decoding.
Some bonus fixes:
- Log out the database location in `info`. There was no other indication where the data directory is, …
> Decode json-rpc hex with prefix

- newsfragments/345.changed.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
When we send `OFFER` request via the `portal_*Offer` json-rpc endpoint, we are waiting for the `ACCEPT` response and process it here:
https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/overlay.rs#L556
However, this is not the case when a node receives an incoming `ACCEPT` request which is not a result of a `portal_*Offer` json-rpc request (for example when gossiping the content to a third node). 
All incoming requests are handled in `overlay_service` except `ACCEPT`: 
https://github.com/ethereum/trin/blob/43c2527c7f941a015b9d7b322f1a139fcf9a53c0/trin-core/src/portalnet/overlay_service.rs#L1071
This breaks the propagated gossip flow when a node receives `ACCEPT` response from a third node.
1. Move the processing of the `ACCEPT` response …
> Process ACCEPT response in overlay service

- trin-core/src/portalnet/find/query_info.rs
- trin-core/src/portalnet/find/query_pool.rs
- trin-core/src/portalnet/overlay_service.rs
- There was no find content variant for `QueryType`.
- `FindNodeQueryEvent` was not generic over `Query`.
- Add `FindContent` variant for `QueryType` with generic type parameter for `OverlayContentKey`.
- Add necessary generic type parameters to `QueryInfo` and `QueryPool` and `QueryEvent`.
- Rename `FindNodeQueryEvent` to `QueryEvent` and make generic over `Query` and `OverlayContentKey`.
- Add generic type parameter for `Query` to `query_event_poll` so that we can call the function with `QueryPool` for any type of `Query`.
The data type of the `callback` channel for `QueryType::FindContent` is `Option<Vec<u8>>` here for the data that corresponds to the (possibly not found) content. I could not find a (recursive) content lookup RPC in the portal JSON-RPC spec, so I was not sure whether …
> Add find content query type and make query event generic over query

- Cargo.lock
- Cargo.toml
- ethportal-peertest/src/jsonrpc.rs
- newsfragments/344.added.md
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/mod.rs
- trin-core/src/jsonrpc/utils.rs
- trin-core/src/portalnet/overlay.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
Trin has no way of retrieving a list of the nodes in the routing tables of each overlay network.
- Added `portal_historyRoutingTableInfo` & `portal_stateRoutingTableInfo` endpoints. 
- Add corresponding tests to `ethportal-peertest`.
The json output format (under the "result" key) of these endpoints is: 
```
"buckets": {
"246": [
{
"enr": "enr:-IS4QHq0W0mPXc5L5FkWnSB1vygIhnhSUh_xD2ddIZYCD3ycdBeHfU4S7wKLOB20zi93GEjfAa4qHHcE_i6eJaIwJPIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQMlZcyp8md8ISz7m6TQlyYqSZPvZgRmtkV3MYgKLexwzIN1ZHCCI6Y",
"node_id": "0x5e5feed5e2835682437c7bcae4e56ef55079bb80ace5d4482e2a2b684c86dcfb",
"radius": "18446744073709551615",
"status": "Connected"
}
],
"249": [
{
"enr": "enr:-IS4QI3GqhE7c_ufMjFYT7MXz98MqmzNlenWBKqvtFKvNqFHYVwMdM6jhtq8y4NzVYWUaJETm6jeK_V1nmmP0gJsXRgBgmlkgnY0gmlwhEF …
```
> Add RPC endpoints for retrieving routing table info for state and history networks

- trin-core/src/portalnet/discovery.rs
I came across some dead code for `Discovery`. Based on the blame, it was added around May 2021.
Remove dead code.
> cleanup: remove dead code for node discovery

- newsfragments/357.changed.md
- trin-core/src/portalnet/overlay_service.rs
We are responding to an overlay request before updating the overlay routing table with the remote `NodeId`.
This can lead to some unexpected behavior, for example when we receive an `OFFER` request, we want to check the overlay routing table if the node already exists and start listening for incoming uTP packets, **before** sending the `ACCEPT` response.
For reference, the discv5 implementation first adds the remote node to the routing table (after a successful handshake) and then responds with a talk response.
1. Extract a new method from existing code encapsulating the logic for overlay routing table update.
2. Call the method before building the overlay response.
> Add node in overlay routing table before returning overlay response

- trin-core/tests/utp_listener.rs
Fix #362 
Increase timeout to 1s
> Increase the utp_listener_events timeout to avoid sporadic CI failure

- trin-core/src/portalnet/find/query_pool.rs
- trin-core/src/portalnet/overlay_service.rs
The overlay does not support find content queries (i.e. lookups).
Here we take a first step toward support for find content queries. We add a find content query pool field to `OverlayService`. This query pool is polled in the main loop, and the generated query events are handled.
At this stage, no queries are initialized, and there is no external API to initialize a find content query from outside the overlay. Content found by a query is not republished to other nodes who did not possess the content. These pieces of functionality will be added in subsequent PRs.
> feat: add find content query pool to overlay

- trin-core/src/portalnet/overlay_service.rs
- trin-history/src/network.rs
- trin-state/src/network.rs
Currently, if any of our bootnodes respond to our initial `PING` with an invalid Discv5 packet, Trin crashes with:
`thread 'tokio-runtime-worker' panicked at 'called Result::unwrap() on an Err value: InvalidRemotePacket', trin-history/src/lib.rs:185:40`
Even if a user reads this and thinks "I should try a different bootnode" or "I should alert the Trin team that their default bootnodes are misbehaving", they don't know which ENR is at fault. Turning on `debug` only prints the Node ID and IP, and is lost in a lot of noise. 
To reproduce the error above, run trin with this particular ultralight bootnode (error is intermittent):
`cargo run -- --networks history --bootnodes enr:-IS4QKczGIvcJ5mpqvzQQGhSNIPhyoBqW5H9OEggKYwmgei7egF3VvXNoCohGEcyUUB9jyBh8qY2iN8sJdK7pRgPP-UDgmlkgnY0gmlwhKRc9EGJc2Vjc …
> Print error instead of crashing if bootnode responds with invalid packet

- .circleci/config.yml
Broken step in ci `win-build`, when trying to install rustup, mismatching checksums are found between the package that's installed and the published checksum. This indicates a security concern that we're actually downloading a possible compromised version, rather than the official release. I'm skeptical, given that this bug has appeared out of the blue. We've been installing `rustup.install` in the same manner and without any errors since we introduced `win-build` step. 
I've tried specifically installing rustup versions...
`choco install rustup.install --version 1.24.3` &
`choco install rustup.install --version 1.22.1` and they both result in a hash mismatch. I'm guessing there's a bug somewhere in how the hash is generated. 
A common solution to this problem that I've come across …
> Add --ignore-checksums flag to win-build rustup install step

- Cargo.lock
- ethportal-peertest/src/lib.rs
- newsfragments/364.added.md
- src/lib.rs
- tests/self_peertest.rs
- trin-core/Cargo.toml
- trin-core/src/cli.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/portalnet/types/content_key.rs
- trin-core/src/utils/db.rs
Fixes #81 
This PR supersedes https://github.com/ethereum/trin/pull/277. Thanks to @hmrtn for his initial work!
Changes:
1. Add --ephemeral flag in trin CLI and implement `Default` trait for `TrinConfig`.
2. Use --ephemeral flag in `self_peertest`.
Bonus:
- migrate from [tempdir](https://crates.io/crates/tempdir) crate to `tempfile`
As I was experimenting with temp dirs, I realized that the `tempdir` crate is deprecated in favor of `tempfile` and some duplicated code was present.
> Implement `--ephemeral` CLI flag

- newsfragments/292.added.md
- src/lib.rs
- trin-core/src/cli.rs
This consolidates the metrics flags into a single flag, `--enable-metrics-with-url`, as described in issue #262.
Fixes #262 
Removed the the `-enable-metrics` bool and `-metrics-url` string in favor of a single flag, `--enable-metrics-with-url`.  
`PortalnetConfig` and its downstream dependencies are left untouched because we can use a `is_some()` boolean to check if the flag is set (and use it if true).
> Consolidate metrics flags

- newsfragments/373.fixed.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/types/validation.rs
- trin-core/tests/overlay.rs
- trin-history/src/network.rs
- trin-history/src/validation.rs
- trin-state/src/network.rs
- trin-state/src/validation.rs
Fixes #342 
`async` expressions in the handlers of main `OverlayService` loop block the loop from continuing while they are awaited
- validation of content
- processing an accept message
Spawn new tasks for `async` expressions.
> Remove blocking async from overlay service loop

- newsfragments/381.added.md
- trin-core/src/portalnet/types/content_key.rs
- trin-core/src/portalnet/types/messages.rs
- trin-history/src/validation.rs
Added basic content key types for `EpochAccumulator` and `MasterAccumulator` content in the history network, as defined [here](https://github.com/ethereum/portal-network-specs/pull/155/files).
> History network types for accumulator content

- newsfragments/382.fixed.md
- trin-history/src/events.rs
- trin-state/src/events.rs
Similar to #373 We had blocking async inside of the overlay events processing loop.
Spawned new non-blocking tokio task to process an event when it's received.
> Remove blocking async from overlay events loop

- trin-core/src/portalnet/overlay.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
In #348, the line `std::process::exit(1)` was added in order to end the program "gracefully" in case initial bootnode pings fail. Turns out this does not gracefully clean things up at all, and was leaving an orphaned IPC file.
Additionally, #348 had replaced the panic that occurred if a bootnode failed ping with an error printout, which made the `network.ping_bootnodes()` method returning a `Result` pointless because it always returned `Ok(())`. 
This PR makes it so that specific errors are printed with no panic or exit for the cases in which:
- a single bootnode fails ping
- all bootnodes fail ping
- no bootnodes were provided
> Print errors without exiting on bootnode failures

- .circleci/config.yml
- Cargo.toml
- ethportal-peertest/Cargo.toml
- newsfragments/396.changed.md
- trin-core/Cargo.toml
- trin-core/src/types/block_body.rs
- trin-core/src/types/receipts.rs
- trin-core/tests/overlay.rs
- trin-history/Cargo.toml
- trin-state/Cargo.toml
The Rust version has not been updated since January 2022.
Update to the latest stable version (1.62.0).
Check [here](https://github.com/rust-lang/rust/blob/master/RELEASES.md) for release changes.
Fixes also some Clippy warnings.
> Update Rust to 1.62.0

- trin-core/src/cli.rs
This may be responsible for the timeouts on Windows CI, maybe clients
aren't closing their connections in the same way?
Anyway, it's a small enough change that it shouldn't wreck performance,
and it's worth it to check if this fixes this pain in the butt CI issue.
> Increase the default number of rpc serving threads

- Cargo.lock
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/lib.rs
- newsfragments/376.added.md
- tests/self_peertest.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/types/validation.rs
- trin-core/src/utp/stream.rs
- trin-state/src/network.rs
Content validation needed for accepted content.
Fixes #340 
- Spawned a non-blocking task to validate content once it's been accepted.
- Refactored `overlay_protocol.store_overlay_content()` -> `storage.store_if_should()`
- Removed `self` ref for `propagate_gossip()` so that it can be used inside tokio task
> Add content validation for accepted content

- newsfragments/395.fixed.md
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utp/stream.rs
During interop testing with Fluffy, the following issues were found:
- `wnd_size` value in the uTP packet header was set to 0 when sending SYN, DATA, and FIN packets.
-  we don't check for active uTP connection matching remote packet `connection_id` when we receive the FIN packet on the same socket where we are the senders of the DATA packet.
- Set `wnd_size` to max window size for `SYN` packets and `max_window_size - curr_window` for DATA and FIN packets.
- Handle FIN packets when we are senders of the data (bidirectional FIN).
> utp: Fix packet's `wnd_size` value and handle bidirectional FIN packets

- .circleci/config.yml
Not enough resources when compiling and testing in CIrcleCI linux pipeline
- Increase CircleCI resource class from medium to [xlarge](https://circleci.com/product/features/resource-classes/)
- Remove the `--job` flag from `cargo build` and `cargo test`
> Increase CircleCI linux and windows pipeline resource class

- ethportal-peertest/src/cli.rs
- src/bin/seed-database.rs
- tests/self_peertest.rs
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/utp/packets.rs
- trin-core/src/utp/time.rs
- trin-core/src/utp/trin_helpers.rs
- trin-history/src/validation.rs
- `clippy` throws new errors, perhaps after #396.
- Fix `clippy` errors based on suggestions.
> fix: address clippy errors

- newsfragments/413.added.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
Validation via `HeaderOracle` needed for content returned from a `FindContent` request.
Wraps up #311 
Added validation for returned content
> Validate content received over utp for findcontent requests

- docs/getting_started.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/mod.rs
- trin-core/src/portalnet/types/node.rs
`overlay_service.rs` file is becoming quite cluttered.
Moved the `Node` type into its own file.
Some refactoring of imports.
> Move node type out of overlay service

- .cargo/config
- .circleci/config.yml
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/scenarios.rs
- newsfragments/411.added.md
- newsfragments/411.changed.md
- newsfragments/411.fixed.md
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/jsonrpc/utils.rs
- trin-core/src/portalnet/overlay.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
Replacing #384 
Need a way to push content over RPC, to build bridge node.
- Move current logic in `portal_historyOffer` to `portal_historySendOffer`
- Add `portal_historyOffer` to broadcast a piece of content to all relevant peers
- slightly more convenient public function for propagating gossip in the overlay
- When validating accepted content, and finding that it fails, skip it instead of panicking
It's probably easiest to read through each commit in the PR individually.
Probably as good as it gets for client team confirmation, over Discord:
> acolytec3 — 8/23 at 5:26 PM
> Should be fine for us.  I don't know that we've even implemented this endpoint since our RPC is woefully lacking
> deme — 8/24 at 1:20 AM
> We didn't implement …
> Offer history content to all peers over rpc

- newsfragments/415.added.md
- trin-core/src/utp/stream.rs
Closes #415. 
Implemented the error handling of `send_talk_req()`.
> Add error check for uTP reply packet: Issue/#415 

- docs/contributing.md
- docs/getting_started.md
- newsfragments/423.fixed.md
- trin-cli/README.md
Missing documentation on how to use `encode-key` utility in `trin-cli`
Fixes #428 
Added a blurb to docs.
> Add how to use encode-key cli tool to readme & include link to contributing docs on how to create a newsfragment

- .circleci/config.yml
- Cargo.lock
- trin-cli/Cargo.toml
- trin-cli/src/main.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/portalnet/types/content_key.rs
This is a branch of #403, which runs windows unit tests, which fail
Modifies the offending 8 unit tests to call `std::mem::drop` on the `PortalStorage` instance, thereby closing the files that rocksdb and sqlite have open in the directory that `TempDir` tries to delete. This avoids the conflict that was causing any unit test that uses `setup_temp_dir` to fail on windows.
> Run windows unit tests and fix storage test failures

- newsfragments/417.fixed.md
- trin-core/src/utp/stream.rs
- utp-testing/docker/circleci/Dockerfile
- utp-testing/src/bin/test_suite.rs
Fixes https://github.com/ethereum/trin/issues/417
Some uTP issues were observed when testing uTP protocol with 10k byte transfer and network delay.
- Build selective ack for an empty incoming buffer, this case was not handled.
- Insert packets into the incoming buffer before packet handling.
- Remove all acknowledged packets from send window upon selective ack receive.
- Emit close event after FIN packet is fully handled.
> Fix some uTP issues

- trin-core/src/portalnet/overlay_service.rs
A trin node currently initializes its overlay routing table at boot by running a find nodes query for only its own node ID, with queries for node IDs in farther buckets being run once per minute. With `EXPECTED_NON_EMPTY_BUCKETS` at 17, it will take 17 minutes from boot to run a query for node IDs in all of the expected buckets.
A FindNode query for each of the expected non-empty buckets is run at boot.
**Also**: 
- Cleans up `overlay_service`'s `!select` loop by breaking out findnode query logic.
- Consolidates multiple variations of `init_find_nodes_query` functions into single function.
> Improve Routing Table Initialization 

- .circleci/config.yml
- newsfragments/416.fixed.md
- trin-core/src/utp/stream.rs
- utp-testing/src/bin/test_suite.rs
- utp-testing/src/lib.rs
Closes #416 
A feature to resend lost uTP packets caused by a timeout was missing.
If we don't receive acknowledgment for the sent uTP packet from remote, we mark the packet as lost and try to resend it.
> Resend lost uTP packets on timeout

- newsfragments/429.added.md
- trin-core/src/types/accumulator.rs
Need a function to validate that one `MasterAccumulator` contains the same validation data as another. For example, when bootstrapping & fetching `N` master accumulators from network peers, we want to validate that all of these accumulators contain the same validation data, even if they are not at the same height.
This means that all historical epoch roots should match, up to the point that both accumulators have the same number of historical epoch roots.
If one accumulator is not in the same current epoch as the other, there is no reason to validate that the header records from different current epochs match. So we return a valid check.
If the accumulators are both in the same current epoch, then we validate that both sets of header records check, up to the point that both accumulators …
> Add compare fn to MasterAccumulator

- trin-history/src/lib.rs
- trin-state/src/lib.rs
Fixes #430.
Log base-64-encoded and non-encoded (node ID and socket addresses) ENR for each boot node.
Example printout:
```shell
{ ENR: NodeId: 0x639a..d9bd, IpV4 Socket: Some(161.35.85.165:9000) IpV6 Socket: None, Encoded ENR: enr:-IS4QBISSFfBzsBrjq61iSIxPMfp5ShBTW6KQUglzH_tj8_SJaehXdlnZI-NAkTGeoclwnTB-pU544BQA44BiDZ2rkMBgmlkgnY0gmlwhKEjVaWJc2VjcDI1NmsxoQOSGugH1jSdiE_fRK1FIBe9oLxaWH8D_7xXSnaOVBe-SYN1ZHCCIyg }
```
> format ENRs in bootnode info log

- newsfragments/414.fixed.md
- trin-core/src/utp/stream.rs
Closes #414 
A bug caused a misleading error message when handling uTP RESET packet.
Return `Ok(None)` instead of `Err(..)` when handling the RESET packet.
> uTP: Do not return error when handling RESET packet

- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
Initiating a `RecursiveFindContent` via RPC does not first check whether the content is stored locally.
`lookup_content` will immediately return content if it is stored locally. If the data is not stored locally or we get a storage error, proceed with network lookup.
> feat: Adds local check for content in lookup_content

- src/bin/seed-database.rs
- src/lib.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/storage.rs
- trin-core/tests/overlay.rs
`PortalStorage::setup_config` was being used in the main trin binary to create a `PortalStorageConfig`, but the `setup_config` method was dividing the storage capacity by 4. This was originally done for testing/debugging purposes but seems to have moved to the main-execution-path undetected.
Removed the `setup_config` method, which was simply dividing the capacity by 4 and then returning a Result even though it couldn't fail. Replaced this method with direct calls to the method it had been calling, `PortalStorageConfig::new`.
> bugfix: Removes quartering of capacity

- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
We log `ProtocolId` of the overlay (i.e. subnetwork) as a prefix in most logs. This is tedious and does not utilize structured logging provided by `tracing`.
- Implement `fmt::Display` for `ProtocolId`.
- Log `ProtocolId` as a structured field.
Sample logs:
```shell
Starting overlay service protocol=History
...
Inserted bootnode into overlay routing table, adding to ping queue. Node 0xe6cd..c511 protocol=History
...
Processing Nodes response from node. Node: 0xc875..c6f2 protocol=History
...
Request 232667426343827416813305233791474747796 failed. Error: The request timed out protocol=History
```
> refactor: log protocol as structured field

- trin-core/src/portalnet/overlay_service.rs
For remote peers who are not in the subnetwork routing table, we rely on the `Discv5` routing table. However, the limited capacity of the `Discv5` routing table is shared among all active subnetworks.
Look up ENR for unrecognized remote peer in the node address cache. The node address cache contains the ENR and observed socket address from the latest established session for a given `NodeId`.
> feat: look up unknown ENRs in node address cache

- trin-core/src/portalnet/overlay_service.rs
```
WARN discv5::socket::send: Sending packet larger than max size: 1899 max: 1280
```
When responding to a FINDNODES with a NODES message, Trin limits the number of ENRs to put in the NODES message so as to not go over discv5's packet size limit. 
However, Content messages can also contain a list of ENRs (when we don't have content but respond with ENRs who might), and we were not limiting the number of ENRs here. This was causing the above warnings.
By modifying `handle_find_content` to use the ` limit_enr_list_to_max_bytes` function like `handle_find_nodes` does.
> Limit Content message ENR contents

- newsfragments/447.added.md
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/node.rs
Content found via find content queries is not disseminated to other peers who may store it.
Implement "poke" mechanism to offer the content found by a find content query to the nodes involved in the query who did not possess the desired content and whose radius is sufficiently large.
Also addressed:
- Fix `PartialEq` implementation for `Node` so that non-ENR changes are recognized by the routing table.
> feat: offer content from query to closest nodes

- docs/getting_started.md
- ethportal-peertest/src/jsonrpc.rs
- newsfragments/451.fixed.md
- src/bin/seed-database.rs
- trin-cli/src/main.rs
- trin-core/src/jsonrpc/eth.rs
- trin-core/src/portalnet/types/content_key.rs
- trin-history/src/validation.rs
`chain_id` field has just been removed from history network keys in the latest spec update.
Removed the chain id field from history network content key type & test values.
> Remove chain id from history network message

- newsfragments/456.removed.md
- trin-core/src/portalnet/types/content_key.rs
- trin-history/src/validation.rs
Master Accumulator content keys are no longer needed now that they are no longer a network-supported content type according to the latest spec update.
> Remove master accumulator content key

- src/lib.rs
- trin-core/src/cli.rs
- trin-core/src/jsonrpc/service.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/storage.rs
- trin-core/src/socket.rs
- trin-history/src/events.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/events.rs
- trin-state/src/jsonrpc.rs
Generally speaking, the logging for `trin` is not very helpful. Significant information is not prominent, and insignificant information is not being logged at the appropriate level.
- move a lot of event logs to `trace` level
- log structured fields to track requests and see event metadata
- prefer short log messages and move details into structured fields
- implement `fmt::Display` for `TrinConfig` and log this representation
```sh
INFO trin: Launching trin config=TrinConfig { networks: ["history"], capacity_kb: 100000, ephemeral: false, json_rpc_url: /tmp/trin-jsonrpc.ipc, pool_size: 5, metrics_enabled: false }
..
INFO trin_core::portalnet::discovery: Starting discv5 enr.encoded=enr:-IS4QBoEfZfpeGJ0fZnRh-kFRhsv1xEr2006H2hpFN4UJib-VclV7D8krb7HvgHP8HU-sPDxLmGB7paK6kIkgGt33TkBgmlkgnY0gmlwhD …
```
> refactor: add structured logging

- ethportal-peertest/src/scenarios.rs
- newsfragments/457.added.md
- src/lib.rs
- tests/self_peertest.rs
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/eth.rs
- trin-core/src/jsonrpc/handlers.rs
- trin-core/src/jsonrpc/types.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/types/accumulator.rs
- trin-core/src/types/validation.rs
Adds jsonrpc support for the `eth_getBlockByNumber` endpoint, but only for pre-merge blocks, where we can look up the header hash via the master accumulator, before retrieving the header from the chain history network.
> Add support for eth_getBlockByNumber for pre-merge blocks.

- newsfragments/460.fixed.md
- trin-core/src/jsonrpc/service.rs
`web3.py`'s default timeout is 10seconds, which will break the ipc socket if its timeout is reached before the jsonrpc request responds. 
Just handle the error, and we can make multiple, sequential jsonrpc requests to the same ipc socket that result in a timeout. 
> Handle broken ipc sockets due to timeouts

- docs/getting_started.md
- docs/jsonrpc_api.md
- newsfragments/307.doc.md
- trin-cli/README.md
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/types/messages.rs
It seemed to me like it's a good idea to have a resource for currently supported jsonrpc endpoints. We don't fully support the whole ETH spec - or the whole Portal spec. We also currently use a couple custom endpoints that aren't found in either spec. 
Updated return values....
- node ids to be full node ids rather than `0x1234..abcd`
- Hex values to have a `0x` prefix.
Wrote docs
> Add jsonrpc api docs.

- docs/getting_started.md
Noticed a couple dependencies missing, while installing on Windows Subsystem for Linux
Added them
> Added some OS build dependencies to the guide

- newsfragments/397.added.md
- trin-core/src/jsonrpc/utils.rs
- trin-core/src/portalnet/discovery.rs
- trin-core/src/portalnet/overlay.rs
Knowing which client and version of that client your node is failing to connect to is helpful for debugging issues on the portal network.
Getting a node's info via RPC is either cumbersome or impossible, depending on the node's settings.
- A client string (e.g. `t 0.1.0` for Trin v0.1.0) is added  to trin's ENR as a value under the key `client`.
- If a portal node has a `c` key in its ENR, it is displayed in the output of the `portal_*RoutingTableInfo` RPC endpoint, like so: 
```
{
"client": "trin 0.1.0",
"enr": "enr:-Je4QFui-99WVnY8Q4C3rR6iZokv_rK1d7Q4fUaWHEd6PEqPcPbVmSoaXOnHG-dFZd0L0v5GWIJXhz7XP3unaqBJv0YBhmNsaWVudIt0cmluIHYwLjEuMIJpZIJ2NIJpcIR_AAABiXNlY3AyNTZrMaEC64Hx6X6On6OQSGP-X5PaXZsCkEzUrimYclGbmwhFAXyDdWRwgiMq",
"node_id": …
```
> Add client info to ENR

- newsfragments/475.fixed.md
- trin-history/src/events.rs
- trin-state/src/events.rs
Related to #473 
If there is an error in processing a `TALKREQ`, we respond to the request with a bytes representation of the error message. 
This pr doesn't resolve the core bug, which is likely something to do with enr caching, but at least it prevents responding the the request with trin's internal error message.
Respond to the request with an empty string rather than responding with an error message. 
> Return an empty response for requests which result in an error during processing.

- newsfragments/478.added.md
- src/lib.rs
- trin-core/src/cli.rs
- trin-core/src/types/accumulator.rs
Fixes #449 
While docker-izing [eth-portal](https://github.com/carver/eth-portal), it turns out it would actually be quite useful to support loading a custom macc, due to a naming conflict b/w the executable ethportal (`./trin`) tries to launch and the directory (`./trin/`) in which we look up the default master accumulator. 
This pr also updates the error message if trin is unable to find the master accumulator. Which before was simple (`Not a directory, OS error 20`) which wasn't explicit about what file was unable to be found. 
Added support for loading a custom master acc from path. 
> Support loading custom master accumulators

- trin-core/src/portalnet/overlay_service.rs
`WARN discv5::socket::send: Sending packet larger than max size: 1300 max: 1280`
#450 fixed most of these errors, but they were still occasionally happening. The packets exceeding these limits cannot be decoded by the remote peer, so we are likely getting ourselves disconnected each time this happens.
Whereas #450 fixed an issue where we were often sending packets ~1000s of bytes over the limit, the issue now is that the limits are occasionally exceeded by 5-20 bytes.
The `limit_enr_list_to_max_bytes` function needs to account for the extra 4 offset bytes per ENR that the SSZ representation of the list of ENRs includes, as well as the 2 bytes for the `selector` byte and the `total` field in a `NODES` response, and the `selector` and union bytes in a `CONTENT` response. 
Trin tends to be …
> Account for additional overhead when limiting size of Nodes/Content responses

- docs/jsonrpc_api.md
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/mod.rs
- newsfragments/471.added.md
- tests/self_peertest.rs
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/jsonrpc/utils.rs
- trin-core/src/portalnet/find/iterators/findcontent.rs
- trin-core/src/portalnet/find/query_info.rs
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/utils/provider.rs
- trin-core/tests/overlay.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
It's tricky to see the path a recursive find network request follows as it hops from enr to enr in the network looking up the target content. Also, it's useful to know which enr actually returns the target content.
Add support for a `portal_traceHistoryRecursiveFindContent` request.
Fixes #469 
> Support tracing recursive find content history network requests

- .circleci/config.yml
- trin-core/src/utp/stream.rs
The duplicate check with `wrapping_sub()` will miss packets whose `seq_nr` is less than the most recently handled one, ie. `self.last_dropped`. As a result, it writes the duplicated bytes into the buffer and messes up the state of UtpStream when performing `flush_incoming_buffer()`.
Changed to `saturating_sub` so that any packet with `seq_nr` less or equal to `self.last_dropped` will be skipped.
> Possible bug in uTP packet duplication check 

- docs/ubuntu_guide.md
- newsfragments/483.doc.md
Missing walkthrough for setting up Trin on Ubuntu as noted in #483. This increases friction for newcomers.
Closes #483
Step by step guide in `docs/ubuntu_guide.md` for devs/testers/users to follow.
> Add docs guide for Ubuntu setup

- newsfragments/486.fixed.md
- trin-core/src/jsonrpc/service.rs
When receiving HTTP JSON-RPC request,  Trin drops the TCP stream right after the request is processed (the stream goes out of scope). This is unexpected behavior because the stream may not reach EOF and more requests should be expected on the same stream.
Add a loop to keep processing JSON-RPC requests until stream EOF.
> core/jsonrpc: Do not drop TCP stream before reaching EOF

- Dockerfile
When trying to use the docker image as a building block for another image, executing `./trin` command returns an error because there is a folder with the same name.
Move trin binaries in `/usr/bin/` folder which allows running with `trin` command instead of `./trin`.
> docker: Save binaries to /usr/bin folder

- newsfragments/492.fixed.md
- trin-core/src/types/accumulator.rs
- trin-core/src/types/header.rs
- trin-core/src/types/validation.rs
The primary pr I'm working on (introducing some bridge capability to trin) has grown quite large. This pr is an attempt to decrease the size of the upcoming pr by extracting some simple value conversion types. These types are going to be shared amongst `block_body.rs` / `header.rs` / `receipts.rs`. The verbose structure of the old conversion fns became quite cumbersome, so I introduced these types to simplify reusing the conversion logic in the different modules.
Added type conversion helper types. Didn't feel like unit tests are necessary for these, since they're being tested implicitly inside `Header`. 
> Add serde deserialization to header

- ethportal-peertest/src/jsonrpc.rs
- newsfragments/493.fixed.md
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
The Portal hive LocalContent test fails because we return an error instead of `0x0` when local content is not available.
Return `0x0` when local content is not available according to https://github.com/ethereum/portal-network-specs/pull/176.
> jsonrpc LocalContent: Return `0x0` when content is not available

- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/scenarios/eth_rpc.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- ethportal-peertest/src/scenarios/paginate.rs
- newsfragments/496.fixed.md
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
According to JSON-RPC [specs](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/portal-network-specs/assembled-spec/jsonrpc/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false), Trin should return a boolean instead of a  string from the `portal_*Store` endpoint.
Return JSON boolean.
> jsonrpc: Return a boolean instead of a string from the `portal_*Store endpoint`

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/README.md
- ethportal-api/src/types/content_key.rs
We want to pass a reference to `HistoryContentKey` as a function signature and be able to decode it into Vec<u8>.
- Implement `From<&HistoryContentKey>` for `Vec<u8>` trait
- Replace `Into<Vec<u8>>` for `HistoryContentKey`  with the From trait which implicitly implements `Into`.
- Release the new `ethportal-api` version with the patch above
- Fix Readme typo
> ethportal-api: Implement `From` trait for `&HistoryContentKey`

- docs/getting_started.md
`build-essentials` package should be `build-essential` - [link](https://askubuntu.com/questions/674449/install-build-essentials)
Fixed command
> Fix build-essential typo

- newsfragments/506.fixed.md
- trin-core/src/portalnet/overlay.rs
- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
- trin-core/src/utils/portal_wire.rs
- trin-core/src/utp/stream.rs
- trin-core/src/utp/trin_helpers.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/validation.rs
Using `ByteList` as the type for content we offer was a mistake... `ByteList` is just an alias for `VariableList` with max length `2048` - so every piece of content we offered was truncated to 2048... which obviously meant that it didn't pass validation on the receiving side, and is likely the reason for poor testnet performance recently.
Changed use of `ByteList` -> `Vec<u8>`
Why didn't testing catch this? Well, utp testing isn't covered extensively inside trin, and that will be covered in `portal-hive` scenario testing. @ogenev (who helped debug this, thanks!) I would just make sure to document in some todo-list that this situation is one we should definitely cover as soon as `portal-hive` is capable of executing this type of test.
> Remove ByteList as type for offered content

- .circleci/config.yml
- Cargo.toml
current rust version is `1.62.0`
bump rust version to `1.66.1` in `Cargo.toml` and circle CI config
> chore: bump rust from 1.62.0 to 1.66.1

- .circleci/config.yml
The Docker build pipeline fails on the master branch.
Increases the no_output_timeout ` setting.
> circleci: Add no_output_timeout value to docker-build job

- Dockerfile
#515 did not bump the rust Docker image version so the Docker image fails to build
bump rust Docker image from `1.62` to `1.66.1`
> fix: bump rust Docker image to 1.66.1

- ethportal-api/src/types/content_key.rs
- newsfragments/518.added.md
As noted in #518, there was no explicit way to access the bytes of an `OverlayContentKey`.
Closes #518 
```rs
pub trait OverlayContentKey:
Into<Vec<u8>> + TryFrom<Vec<u8>> + Clone + fmt::Debug + fmt::Display 
{
/* snip */
/// Returns the bytes of the content key.
fn bytes(&self) -> [u8; 33]; // <-- New
}
```
With implementation:
```rs
fn bytes(&self) -> [u8; 33] {
let mut bytes = [0u8; 33];
let (selector, hash) = match self {
HistoryContentKey::BlockHeader(k) => (0x00, k.block_hash),
HistoryContentKey::BlockBody(k) => (0x01, k.block_hash),
HistoryContentKey::BlockReceipts(k) => (0x02, k.block_hash),
HistoryContentKey::EpochAccumulator(k) => (0x03, k.epoch_hash.0),
};
for (i, byte) in hash.into_iter().enumerate() {
bytes[i] = byte
}
bytes.rotate_right(1);
bytes[0] = selector;
bytes
}
```
- …
> `ethportal-api`: Add `bytes()` to `OverlayContentKey`

- Cargo.lock
- README.md
- docs/getting_started.md
- docs/jsonrpc_api.md
- docs/ubuntu_guide.md
- newsfragments/509.added.md
- trin-core/Cargo.toml
- trin-core/src/cli.rs
- trin-core/src/jsonrpc/service.rs
- trin-core/src/utils/provider.rs
As noted in #509, Trin sometimes requires a connection to a trusted provider, however was no alternative to 
Infura. 
Added:
- CLI flag `--trusted-provider`
- New option `custom` 
- Altered option `geth` -> `pandaops`
- `Url` library (see below)
- CLI flag `--trusted-provider-url` 
- Accepts a url, such as `http://127.0.0.1:8545` that is parsed with `Url` library
- Is required for the `custom` and `pandaops` trusted provider arguments
- Documentation in `./docs/getting_started.md`
- Flag testing for invalid combinations
- Requirement that `--trusted-provider custom` choice requires the `--trusted-provider-url`.
- ~~The ability to pass a either `http://127.0...` or `127.0...`~~. Urls are parsed for correctness, and must have a base otherwise the CLI parser will panic and return an …
> add CLI flag and docs for local trusted provider

- trin-core/src/portalnet/overlay_service.rs
- trin-core/src/portalnet/types/messages.rs
Trin's processing of `PING`/`PONG` messages is not updating the radius of the source node in the routing table. This results in Trin's gossip functionality sending `OFFER`s to nodes that are not interested in the data based on their radius. These nodes respond with `ACCEPT` messages, but they are empty implying no interest.
Interpret `PING` and `PONG` custom payload field as a 32 byte, little endian representation of an unsigned 256 bit radius value and update the routing table entry.
> Updates source node radius on `PING`/`PONG`

- ethportal-api/src/types/content_key.rs
The recently introduced `.bytes()` method is not explicit about resources used in conversion.
For `OverlayContentKey`:
```rs
// Before
.bytes() 
// After
.to_bytes()
```
The method is `borrowed -> owned` and so follows the naming [guidelines](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv) 
> rename .bytes() to .to_bytes()

- trin-core/src/portalnet/overlay.rs
Trin currently gossips to nodes without regard for whether the routing table shows them as disconnected or not.
Nodes are filtered by connection status before gossiping.
> Do not gossip to disconnected nodes

- Cargo.lock
- Cargo.toml
- Dockerfile
- newsfragments/526.added.md
- src/bin/purge_db.rs
- trin-core/src/portalnet/storage.rs
After #514 we will have testnet nodes that contain invalid / outdated data. Also following the discussion [here](https://github.com/ethereum/portal-network-specs/pull/177#discussion_r1068003004) it is now expected that we might have to occasionally purge the data from our testnet due to spec updates / etc.
Add a script that can be easily run in our testnet deployment ansible playbook to either flush all data from a node's db - or iterate through and evict only incorrectly encoded data.
> Add purge db script

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/history.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- newsfragments/499.fixed.md
- rpc/src/history.rs
- trin-core/src/jsonrpc/endpoints.rs
- trin-history/src/jsonrpc.rs
We need to change Trin's offer endpoints to match recent [spec changes](https://github.com/ethereum/portal-network-specs/pull/179).
Closes #499 
Rename the `Offer` endpoint to `Gossip` and add a new `Offer` call.
- `portal_*Offer` accepts now a single content key as a parameter, instead of a list of content keys.
- Do not return `connection_id` in the offer json-rpc result.
> jsonrpc: Rename `Offer` endpoint to `Gossip` and add new `Offer` call

- docs/contributing.md
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- newsfragments/545.fixed.md
- src/lib.rs
- tests/self_peertest.rs
- trin-cli/src/main.rs
- trin-core/src/cli.rs
- trin-core/src/jsonrpc/service.rs
- trin-core/src/jsonrpc/utils.rs
- trin-core/src/types/merkle/proof.rs
- trin-core/src/types/validation.rs
- trin-core/src/utp/packets.rs
- trin-core/src/utp/stream.rs
- trin-core/tests/overlay.rs
- trin-history/src/jsonrpc.rs
- utp-testing/src/bin/test_suite.rs
As @perama-v pointed out in https://github.com/ethereum/trin/pull/510#issuecomment-1407260933- clippy nightly now checks for interpolated string formatting when possible. Assuming this will eventually make its way into stable, but in the meantime I don't see any problem with moving ahead and adopting this. I've added a line to the Style Guide, since I don't think it's worth updating our ci to nightly to catch this.
> Use interpolated string formatting everywhere

- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- trin-core/Cargo.toml
- trin-core/src/portalnet/overlay_service.rs
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
Our discv5 dependency needs to be on a stable release, not a random git branch, to be able to publish a release since cargo requires that "all dependencies must have a version specified when publishing."
> Move to stable discv5 dependency

- ethportal-peertest/src/lib.rs
- newsfragments/542.fixed.md
- src/lib.rs
- src/main.rs
- tests/self_peertest.rs
- trin-core/src/jsonrpc/service.rs
Closes #542 
Remove the obsolete `JsonRpcExiter` struct and instead return jsonrpsee server handle from the `run_trin` method.
> Remove obsolete `JsonRpcExiter`

- newsfragments/549.fixed.md
- trin-core/src/portalnet/storage.rs
We ran into an issue w/ our testnet databases where they were in a state of storing content keys both with and w/o a `0x` prefix. The naked unwraps inside the `paginate` function bricked the node when it tried to paginate over local content keys. The following changes are to help prevent this situation from repeating in the future - accompanied by a purge of the testnet databases.
- store content keys w/o `0x` prefixes in our meta db
- added check to invalidate content keys w/ `0x` prefix before inserting them into the meta db
- removed some naked `unwrap`s & `expect`s
> Store content keys in meta db w/o 0x prefix

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/discv5.rs
- ethportal-api/src/history.rs
- ethportal-api/src/lib.rs
- ethportal-api/src/web3.rs
- newsfragments/557.removed.md
- rpc/Cargo.toml
Build error preventing `ethportal-api` tests from running
Fixes: #557
- Removed features from ethportal-api (see discussion in issue)
- Added jsonrpsee features required
- Minor version bump to `ethportal-api`
> Use `jsonrpsee` features by removing `ethportal-api` features

- src/bin/purge_db.rs
The strategy we use in Ansible for capturing log output from the purge step only works for `stdout`.
Use `println!` / `eprintln!` for log output rather than tracing library
> Output purge logs to stdout

- ethportal-api/src/history.rs
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- newsfragments/563.fixed.md
- rpc/src/history.rs
- tests/self_peertest.rs
- trin-core/src/jsonrpc/endpoints.rs
- trin-core/src/portalnet/overlay.rs
- trin-history/src/jsonrpc.rs
Portal json-rpc [specs](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/portal-network-specs/assembled-spec/jsonrpc/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) require that a `content_value` param is accepted in `portal_*Offer` endpoint. 
Closes #559
Add an optional `content_value` param to `Offer` rpc. If it is not provided, we look for the content in the database, otherwise, we keep the content value in memory and send it using the `PopulateOffer` overlay request.
> Add optional `content_value` param in `portal_*Offer` rpc

- rpc/src/lib.rs
- trin-core/src/portalnet/find/query_info.rs
- trin-core/src/utp/trin_helpers.rs
Some `![allow(dead_code)]` attributes are sneaking into our codebase.
Removes all `![allow(dead_code)]` occurrences.
> Cleanup clippy's `allow(dead_code)` attributes

- src/lib.rs
Missed some unwraps in #562 - that I noticed while deploying bridge nodes to the testnet.
Added `#[warn(clippy::unwrap_used)]` to main trin module.
> Lint unwraps in trin

- newsfragments/564.fixed.md
- trin-core/src/portalnet/storage.rs
- trin-core/src/portalnet/types/distance.rs
`PortalStorage` has some inconsistency w/ respect to the `--kb` flag, which revealed itself while running bridge nodes w/ `--kb 0`. 
Scenario 1
- User runs a fresh `trin` node (eg. random private key) w/ `--kb 0`
- Problem: Storage would be configured w/ `Distance::MAX` as it's radius instead of `0`
- Solution: Set radius to `Distance::ZERO` in this scenario
Scenario 2
- User runs an old `trin` node w/ `--kb 1` (when `--kb` was set to a greater number in a previous run)
- Problem: There was no pruning until the user tried to "store" a new piece of data
- Solution: Prune db inside `PortalStorage::new()` if capacity is reached on startup, & set relevant fields
Scenario 3
- User runs an old `trin` node w/ `--kb 0`
- Problem: There was no pruning until the user tried to "store" a new piece of …
> Use zero radius if empty storage & 0kb config

- newsfragments/577.removed.md
- trin-core/src/cli.rs
Fixes #571 
The `--pool-size` flag is no longer used.
Removed `pool_size` from `TrinConfig`
I didn't find any occurence of `--thread-pool` mentioned in #571
> remove `--pool-size` flag

- .circleci/config.yml
- Cargo.toml
We have two docker hub registries that need consolidation. 
- `portalnetwork/trin:latest` will be updated automatically with every merge into `master`. 
- `portalnetwork/trin:testnet` will be updated manually, and a tag `testnet` will be pushed to github to track testnet releases
- `portalnetwork/trin:bridge` will be updated manually
Requires
Also...
Includes a hotfix for failing `docker-build` step on `master`'s CI. The `[[bin]]` definition causes the output executable to be under a different name (`purge-db`). Since our testnet config is already tied to `purge_db`, I just removed the superfluous definition
> Transfer from ogenev docker registry to portalnetwork

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/lib.rs
- ethportal-api/src/types/content_key.rs
- ethportal-api/src/utils/bytes.rs
- ethportal-api/src/utils/mod.rs
- newsfragments/528.added.md
Resolves #528. 
Adds new default method to `OverlayContentKey` trait as follows:
```rust
/// Returns the content key as a hex encoded "0x"-prefixed string.
fn to_hex(&self) -> String {
hex_encode(self.to_bytes())
}
```
Uses `to_*` naming convention for borrowed->owned methods according to [guidelines](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv)
Trin-native `hex_encode`/`hex_decode` are used instead of external `hex::encode`/`hex::decode`. These utils
were copied from trin-core to `ethportal-api`. 
Added test cases for `.to_hex()` and, for comparison, the existing `.to_string()` 
```sh
// Existing .to_string()
"EpochAccumulator { epoch_hash: 0xe242..c491 }"
// New .to_hex() …
```
> add hex string method to overlaycontentkey

- newsfragments/578.changed.md
- src/lib.rs
- trin-core/src/cli.rs
Fixes #535
Web3 transport is either `ipc` or `http`
Wrap it in a `Web3TransportType` enum in `trin_core::utils::transport`
> Change web3-transport cli argument to enum instead of string

- trin-core/src/types/validation.rs
Hmmm. no idea how this bug snuck through in #585 - since those tests were all passing green. But, turns out there was an import statement that needed updating.
> Hotfix for failing master build

- Dockerfile
Eww, sorry for the second hotfix in one day. I forgot to add the step to the dockerfile to copy over the newly created workspace: `trin-types` in #588 
> Add trin-types copy step to dockerfile (hotfix)

- .github/workflows/book.yml
- newsfragments/590.fixed.md
`book.yml` didn't trigger a Github action, and the mdbook didn't deploy to Github pages.
Update `book.yml` to test/build/deploy the mdbook. It will run test/build when PR are for the master branch, and it will deploy a page only when commits push to the master branch. [Deployed page](https://e3243eric.github.io/trin/).
- Rename branches from `main` to `master`.
- Add `book.yml` to paths.
- Update some steps in jobs. Reference: [running-rust-tests](https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#running-rust-tests), [starter-workflows](https://github.com/actions/starter-workflows/blob/main/pages/mdbook.yml), [workflow to publish your site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages- …
> Update Github action for mdbook

- ethportal-peertest/src/lib.rs
- newsfragments/591.fixed.md
- tests/self_peertest.rs
- trin-core/src/utils/provider.rs
- trin-history/src/validation.rs
The logic for generating `TrustedProvider` when using panda ops caused a panic, which occurred when deploying the bridge nodes to the testnet. Imo, it's worth removing the `ws` attribute entirely from `TrustedProvider`
- The pandaops nodes don't support ws
- The decision to have a ws option was back when we were targeting wallet users - and expected to proxy to infura quite frequently. Now, we're targeting research and expect to remove any infura relience in the near future.
If we want to leave in the `ws` attribute, it's fairly simple bugfix to avoid the panic. But, imo since we don't need `ws` we might as well remove it entirely
Removed `ws` attribute from `TrustedProvider`
> Remove websocket from trusted provider

- Makefile
- newsfragments/601.added.md
Related to Issue #599.
Add a new Makefile `lint-optional` command. This command includes the original lint checks, and adds the `clippy::cargo` and the rustc lint `unused_crate_dependencies`. It will bump up warnings and includes some false positives as #599 said.
> Add 'clippy::cargo' and 'unused_crate_dependencies' lints to Makefile

- .circleci/config.yml
- Dockerfile
- newsfragments/604.fixed.md
- trin-utils/build.rs
`git` is not available from within the docker build context. Which means that all of our docker-based nodes (eg. hive & testnet) are built w/o the git hash in their enr (`trin v0.1.0-unknown`). The latest commit hash must be passed in manually using the `--build-arg` flag. 
Added logic to check for the docker build argument if git is not available to produce the git hash.
[This docker image](https://hub.docker.com/layers/portalnetwork/trin/latest/images/sha256-13fbae2c1ebedfebc8d989d5e7f5ff338bb01377aff7d8e4fbe60f64048a0295?context=explore) contains the build of this pr. If you pull it down locally and run it, you can see the git hash in the displayed version when you launch trin.
> Build docker image with git hash env var

- trin-core/src/portalnet/storage.rs
- trin-history/src/lib.rs
Progress on #530 
Want to report more storage usage metrics in the logs
Bonus issue: There was going to be some duplication of effort, to build the metrics for logs. So we combine the collection/calculation to one spot.
Changes are small, but there are several of them. I recommend reviewing commit-by-commit.
1. Always track the database statistics, whether or not we report them online (since we always report them to log now)
2. Combine all storage metrics into a single loggable string
3. Internally track whenever the radius changes (both, setting `storage.radius` and updating `storage.metrics.report_radius()`)
4. Correctly generate the starting radius, when reusing an existing database
5. Bonus fix: the first log was getting double-reported for unknown reasons, this went away in local …
> Storage metrics for log report

- trin-types/src/cli.rs
trin was panicking when being called with `--help` or `--version`. This was introduced by #578 
Add a test that `-h` doesn't panic. Return the error instead of panicking. Then, when parsing args for CLI, use `Clap::Error`'s built-in `.exit()`, which prints the appropriate message and exits immediately.
> Panicking during: trin --help

- Cargo.lock
- ethportal-api/Cargo.toml
- portalnet/Cargo.toml
- trin-history/Cargo.toml
- trin-types/Cargo.toml
- trin-utils/Cargo.toml
- trin-validation/Cargo.toml
Unused dependencies in some workspace crates.
Ran [cargo-udeps](https://github.com/est31/cargo-udeps) to remove unused dependencies.
> Remove unused cargo dependencies

- Cargo.lock
- ethportal-api/README.md
- ethportal-api/src/history.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/jsonrpc.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- ethportal-peertest/src/scenarios/paginate.rs
- newsfragments/538.changed.md
- portalnet/src/overlay_service.rs
- portalnet/src/storage.rs
- portalnet/src/types/messages.rs
- rpc/Cargo.toml
- rpc/src/history.rs
- src/bin/purge_db.rs
- tests/self_peertest.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/validation.rs
- trin-types/Cargo.toml
- trin-types/src/constants.rs
- trin-types/src/content_key.rs
- trin-types/src/content_value.rs
- trin-types/src/lib.rs
- trin-utils/Cargo.toml
- trin-utils/src/bytes.rs
- Resolves #538
- Fixes #540
- `thiserror` is used to capture errors 
- Problematic bytes are stored in an error variant:
- Where decoding fails to produce a known content type (item/key), represent the input as an error variant rather than a content variant.
- `From` replace with `TryFrom`:
- When a content key decode failure was encountered via `From`, the `Unknown` variant was used. Now, `From` is replaced with `TryFrom`.
- RPC responses are wrapped in an Option-like enum for `HistoryContentValue `called `PossibleHistoryContentValue`. This allows the None variant to be represented as `0x`. The serialization and deserializeation of this new enum could be probably be shortened by pointing to the implementations for `HistoryContentValue`.
```rs
// ethportal-api/src/types/content_item.rs …
```
> Remove history content key/item `Unknown` variants

- ethportal-api/src/lib.rs
`Portal-hive` tests want to match on `PossibleHistoryContentValue` which is not exported via `ethportal-api`.
Re-export `PossibleHistoryContentValue` and `ContentValueError` from `trin-types`.
> ethportal-api: Re-export `PossibleHistoryContentValue` and `ContentValueError`

- docker/Dockerfile
Quick hotfix to fix failing `docker` builds on master CI
> Copy trin-bridge in main dockerfile

- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/tests/overlay.rs
- trin-history/src/network.rs
- trin-state/src/network.rs
Fix #619 
Rremove any duplicate values of `data_radius` and pass all reads through to storage. Then pings/pongs should use the real value from our data store.
> Pass real radius during ping/pong

- Cargo.lock
- ethportal-peertest/src/main.rs
- src/bin/purge_db.rs
- src/main.rs
- tests/self_peertest.rs
- trin-bridge/src/main.rs
- trin-utils/Cargo.toml
- trin-utils/src/lib.rs
- trin-utils/src/log.rs
- utp-testing/src/bin/test_app.rs
Fix #638 
Only import the libraries as needed, per OS.
Unfortunately, increases the size of trin-utlis a bit, to add log tracing.
On *nix, check if output is going to terminal (or for example, piped to a file). Also, if going to a terminal, make sure the terminal supports color (ie~ the environment variable TERM is not "dumb").
> Only use ANSI colors if output to colored terminal

- .circleci/config.yml
Minor update to take into account moving the location of `portal-accumulator` repo
> Update accumulators repo

- portalnet/src/overlay_service.rs
Imo - content keys are far more useful to display - especially for debugging purposes.
> Display content key rather than id

- portalnet/src/storage.rs
In a local test with 2M rows, adding this index sped up a SELECT TOTAL(content_size) query time from 125ms to 75ms.
Fix #649 
Add an index and shelve the issue, for now.
> Add a SQL index to speed up data size checks

- portalnet/src/metrics.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/src/storage.rs
- portalnet/src/types/messages.rs
- src/bin/purge_db.rs
- src/lib.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/network.rs
Fix #655 
Combine metrics into one, using labels to differentiate. Display offers and accepts in the heartbeat log. Other things are being tracked, this is shown just to give you a flavor of what's going on.
The heartbeat log now looks like:
```
2023-04-13T04:09:28.335984Z  INFO trin_history: reports~ data: radius=0.4% content=2086.4/2000kb #=27 disk=2509.3kb; msgs: offers=7/8, accepts=3/4
```
> Track and display network message stats

- trin-types/src/bootnodes.rs
If trin bootnodes are down, there is no backup mechanism to start trin
Added ENRs from the portal spec testnet bootnodes section to default bootnodes configuration.
- Closes #336 
- ~~[ ] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)~~
> add fluffy and ultralight boodnodes to default

- portalnet/src/storage.rs
Fix #659 
It won't take long for 1 digit of percentage to be rounded down to 0, for even moderately sized nodes. So we need to generate and display more precision for the logs.
Get more bytes of the radius, to get a higher precision estimate. We don't expect to display a higher precision than 1 in a million, so 3 bytes would be sufficient. The nearest supported integer is at u32 with 4 bytes.
Ratio (0-1) is favored over % (0-100) in the prometheus system. Switch to saving that value, plus the corresponding metric name change.
Depending on the size of the radius, grow or shrink the number of displayed digits in the heartbeat log.
> Radius metric: higher precision, switch to ratio, log approprate number of digits

- Cargo.toml
- newsfragments/668.changed.md
- src/bin/purge_db.rs
Related to #627. A tiny PR of #651.
How was it fixed?
Switched from StructOpt to Clap in purge_db.
> Switch from StructOpt to Clap in purge_db

- Cargo.toml
Fixes https://github.com/ethereum/trin/issues/676
by readding removed ``trin-bridge = { path = "trin-bridge" }``
> readded mistakenly removed dependency trin-bridge

- newsfragments/674.changed.md
- trin-bridge/Cargo.toml
- trin-bridge/src/cli.rs
- trin-bridge/src/main.rs
Related to #627. A tiny PR of #651.
Switched from StructOpt to Clap in trin-bridge.
> Switch from StructOpt to Clap in trin-bridge

- portalnet/src/overlay_service.rs
During some debugging with @mrferris we discovered what appears to be a bit of a bug in how we handle utp streams. 
If there is an error while reading to eof - we should return early - in the same way as if there is an error for `accept_with_cid`. Currently, we do not return early upon an error. This means that we go ahead and try to `process_accept_utp_payload` with an invalid payload - which is usually just an empty vector.
Return early
> Return early if there's an error while reading utp stream to eof

- ethportal-peertest/src/lib.rs
- newsfragments/671.fixed.md
- rpc/src/server.rs
- src/lib.rs
- trin-types/src/cli.rs
Fixes todo added in this https://github.com/ethereum/trin/pull/44 PR
Instead of using String/&str I converted the types of Path or PathBuf where it made sense. Basically just using PathBuf instead of using a String
> change web3_ipc_path from String to PathBuf

- book/src/developers/contributing/git/pull_requests.md
- docs/contributing.md
When I made my PR https://github.com/ethereum/trin/pull/670 clippy failed on CI even though I ran the commands developers are told to use in the guidelines. I am on "Ubuntu 20.04.6 LTS". The clippy in CI tests features additional commands ``--all-targets --all-features --no-deps`` When I ran the command gotten from the CI I got the same output as it and was able to fix the issue.
From testing what made the clippy error happen was adding ``--all-targets`` so I added that. I decided to add ``all-features`` too since I seen in tokio they use "features" a lot so if we ever start using them, it would be good to have this. Since if someone is working on a feature in the future and don't have this flag it won't error on their machine but will in CI.
I decided to not add ``--no-deps`` like CI has …
> add ``--all-targets --all-features`` to clippy linting guidelines

- newsfragments/688.changed.md
- trin-cli/Cargo.toml
- trin-cli/src/main.rs
Related to #627. A tiny PR of #651.
Switched from StructOpt to Clap in trin-cli.
> Switch from StructOpt to Clap in trin-cli

- docker/Dockerfile
- docker/Dockerfile.bridge
We never added the `purge_db` script to the docker bridge image.
Also removed some unnecessary lines post #681 
> Add purge db executable to bridge docker image

- Cargo.lock
- newsfragments/680.fixed.md
- portalnet/Cargo.toml
- portalnet/src/socket.rs
- portalnet/tests/overlay.rs
fixes https://github.com/ethereum/trin/issues/358
By depreciating ``find_assigned_ip()``. ``find_assigned_ip()`` was only still used for this one test case and is no longer part of anything else so if using 127.0.0.1 is a solution to the problem it doesn't make much sense keeping the function around. This also lowers the dependency count which is nice.
> depreciate find_assigned_ip

- Cargo.lock
- trin-types/Cargo.toml
To cut a release for `trin-types` we need to update the `trin-utils` dependency
> Update trin-types dependency on trin-utils

- ethportal-api/src/history.rs
- ethportal-peertest/src/scenarios/basic.rs
- rpc/src/history_rpc.rs
- trin-history/src/jsonrpc.rs
- trin-types/src/jsonrpc/endpoints.rs
Spec changed here:
https://github.com/ethereum/portal-network-specs/pull/202
Fix #696 
Remove the paramater. We just ignored it anyway, so it's pretty straightforward.
> Remove data radius from json-rpc ping

- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/scenarios/basic.rs
- trin-history/src/jsonrpc.rs
The `total` field doesn't match the spec, it is just supposed to return a top-level list of ENRs.
Fix #702 
Redefine the `FindNodesInfo` type to a vector of ENRs.
> Remove total from result for portal_historyFindNodes

- ethportal-api/src/lib.rs
`trin-types`'s `Enr` type was not re-exported from `ethportal_api`, like `NodeId` was
re-exported it
> Re-exports trin-types's Enr type from `ethportal_api`

- newsfragments/719.fixed.md
- trin-utils/src/log.rs
``use std::env`` is only used on none windows so it breaks clippy since it doesn't have a cfg.
Also we have 2 not needed use's which don't do anything
I changed ``env::var(`` to ``std::env::var(`` then I removed not 2 not used uses
> Remove not used import and fix a windows clippy issue

- book/src/users/monitoring.md
No guide for grafana setup without docker
Guide added to user/monitoring section of book.
Includes setup of node-exporter system data so that this data may be used, but does not plug in/expose those data to the user.
- ~[ ] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)~
> add guide for grafana setup

- .circleci/config.yml
The CI takes so long most of this is just building libraries!
The cause? The mass amount of libraries Rust projects use as a side affect of an easy to use package manager!!!
1. By adding [Mozilla'a sccache](https://github.com/mozilla/sccache) library.
2. Splitting lint-build-test CI into lint, build, and test
> Add optimizations for CI tests

- Cargo.toml
- newsfragments/725.added.md
- portalnet/src/events.rs
- src/lib.rs
- trin-types/src/cli.rs
We want to launch the beacon chain network
This PR launches the beacon portal network **without** RPC support when "beacon" is included in the `networks` cli flag.
To enable RPC for the beacon network, we need first to refactor how JSON-RPC server endpoints are initialized based on the networks launched, which will follow in a separate PR.
> Launch beacon portal network

- book/src/users/monitoring.md
The template prometheus config is missing 2 spaces so if a user follows the instructions Prometheus won't launch
Grafana isn't in the default package repos on Ubuntu 22.04
I added 2 spaces so the config is valid yml and add 3 commands from https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
> Fix 2 issues with Monitoring docs

- ethportal-api/src/discv5.rs
- ethportal-api/src/history.rs
- ethportal-peertest/src/scenarios/basic.rs
- newsfragments/718.added.md
- portalnet/src/overlay.rs
- rpc/src/discv5_rpc.rs
- rpc/src/history_rpc.rs
- tests/self_peertest.rs
- trin-history/src/jsonrpc.rs
- trin-types/src/jsonrpc/endpoints.rs
We didn't finish implementing the rest of portal_history* RPC's
I implemented ``add_enr``, ``get_enr``, ``delete_enr``, ``lookup_enr``.
I modelled our lookup_enr after Fluffy's for consistency between clients.
> Implement portal_history* ``add_enr``, ``get_enr``, ``delete_enr``, ``lookup_enr`` RPC's

- Cargo.lock
- newsfragments/726.fixed.md
- portalnet/src/find/iterators/query.rs
- portalnet/src/overlay.rs
fix https://github.com/ethereum/trin/issues/708 supersedes https://github.com/ethereum/trin/pull/698 since this resolves the root of the problem
By changing our ``query_peer_timeout`` from 10s to 2s.
Our recursiveFindNode code is heavily based off sigp/discv5 implementation. The biggest difference? Our ``query_peer_timeout`` is set 5 times higher. 
Our ``query_timeout`` is 60 seconds with 3 allowed async queries. The issue is if we ping 3 bad nodes that means 1/6th of our query time is gone. So worst case we can only make 18 queries. Where as if we match the timeout our implementation is based off of, of 2s our worst case is 90.
/// The timeout after which a `QueryPeer` in an ongoing query is marked unresponsive.
/// Unresponsive peers don't count towards the parallelism limits for a …
> fix ``historyRecursiveFindNodes`` endpoint taking too long to return

- Cargo.lock
- ethportal-api/src/beacon.rs
- ethportal-api/src/lib.rs
- newsfragments/732.added.md
- rpc/src/beacon_rpc.rs
- rpc/src/lib.rs
- trin-beacon/src/jsonrpc.rs
- trin-types/src/content_key.rs
- trin-types/src/content_value.rs
- trin-types/src/jsonrpc/endpoints.rs
No Beacon network json-rpc endpoints were implemented.
Implement Beacon network RPC endpoints.
**Note**: The RPC server is still not running those endpoints, because some additional refactoring is needed on the server side which will follow in a separate PR. Then we can also add tests for those endpoints and refactor the duplication in the history and beacon crates.
> Implement Beacon network RPC endpoints

- Cargo.lock
- newsfragments/737.fixed.md
- trin-cli/src/main.rs
https://github.com/ethereum/trin/issues/573 (``trin-cli`` removal as talked about in the meeting 5/11/2023)
removed json-rpc from ``trin-cli``
> remove json-rpc from ``trin-cli``

- newsfragments/738.fixed.md
- trin-cli/src/main.rs
in call on 5/11/2023 we talked about removing this with the cli
by removing it
> remove EncodeKey from ``trin-cli``

- docker/Dockerfile
- docker/Dockerfile.bridge
Dockerfile builds on master are broken post #723 
Remove `trin-types` references from dockerfiles
> Remove trin-types from dockerfiles

- trin-utils/Cargo.toml
- trin-utils/src/log.rs
Fixes #734 
Added explicit support for env-set log levels, which isn't supported when calling `.init()` as opposed to `::init()`.
https://github.com/tokio-rs/tracing/issues/1697#issuecomment-1003513224
> Fix tracing subscriber init to support env log levels

- Cargo.lock
- newsfragments/749.fixed.md
- trin-state/Cargo.toml
- trin-state/src/utils.rs
The distance function code for the state network was undated and hard to read.
It was fixed by simplifying the way we do the calculation instead of using the nums library we natively use U256 to do the calcluation.
The result of this in much more readable code, as well as the code resembling the spec's implementation which increases readability
> Simplify state network distance code

- newsfragments/743.fixed.md
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
```
/// Constructs a JSON call for the RecursiveFindNodes method.
async fn recursive_find_nodes(
network: Arc<RwLock<HistoryNetwork>>,
node_id: ethportal_api::NodeId,
) -> Result<Value, String> {
let node_id = discv5::enr::NodeId::from(node_id.0);
let overlay = network.read().await.overlay.clone();
let mut nodes = overlay.lookup_node(node_id).await;
nodes.sort_by(|a, b| {
XorMetric::distance(&node_id.raw(), &a.node_id().raw())
.cmp(&XorMetric::distance(&node_id.raw(), &b.node_id().raw()))
});
let nodes: Vec<Enr> = nodes.into_iter().take(16).collect();
Ok(json!(nodes))
}
```
```
nodes.sort_by(|a, b| {
XorMetric::distance(&node_id.raw(), &a.node_id().raw())
.cmp(&XorMetric::distance(&node_id.raw(), &b.node_id().raw()))
});
let nodes: Vec<Enr> = nodes.into_iter().take(16).collect();
```
^ …
> Remove unused sort and take 16 from recursive_find_nodes

- ethportal-api/src/types/cli.rs
- newsfragments/748.fixed.md
fix's https://github.com/ethereum/trin/issues/618
i replaced the panics in CLI with clap::Error
> CLI parsing return clap:Error instead of panicking

- newsfragments/763.added.md
- trin-bridge/src/cli.rs
- trin-bridge/src/lib.rs
- trin-bridge/src/types.rs
No support for running a bridge node with more than one overlay network.
Add 'network' cli flag to trin-bridge
> Add `network` cli flag to trin-bridge

- ethportal-api/src/types/cli.rs
- newsfragments/757.fixed.md
- rpc/src/rpc_server.rs
- trin-beacon/src/events.rs
- trin-history/src/events.rs
- trin-state/src/events.rs
#742 introduced support for websockets. When running trin-bridge with multiple nodes running at once, we end up with a panic resulting from a port collision. Since, the websocket port is set by default, spinning up multiple nodes at the same time results in multiple nodes trying to open a ws connection on the same port. This causes the events channel to close, and results in a panic.
A long-term solution would be to enable configuration for custom ws ports via a cli argument.
- Update default ws to use the same port as http
- Handle panics inside a subnetwork events loop
> Update default ws port to avoid collisions when running multiple nodes

- ethportal-api/src/types/cli.rs
- newsfragments/768.changed.md
- rpc/src/lib.rs
- rpc/src/rpc_server.rs
Running Http and Websocket on the same port cause Trin to crash
Remove default support for WS.
> Do not run WebSocket RPC by default

- Cargo.lock
- ethportal-api/src/beacon.rs
- ethportal-api/src/discv5.rs
- ethportal-api/src/history.rs
- ethportal-api/src/types/discv5.rs
- ethportal-api/src/types/enr.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- ethportal-api/src/types/node_id.rs
- ethportal-api/src/types/query_trace.rs
- ethportal-peertest/src/scenarios/basic.rs
- ethportal-peertest/src/scenarios/find.rs
- newsfragments/669.fixed.md
- portalnet/src/discovery.rs
- portalnet/src/overlay_service.rs
- rpc/Cargo.toml
- rpc/src/beacon_rpc.rs
- rpc/src/discv5_rpc.rs
- rpc/src/history_rpc.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
Fix https://github.com/ethereum/trin/issues/539 
Update discv5 to ``v0.3.0``
Use discv5 node_id type and remove our encapsulated one
We can't fully remove it till we add ``#[serde(with = "SerHex::<StrictPfx>")]`` to ``sigp/enr`` it is used for recursive query tracing. It is a issue with serialization with hashmaps, if we don't have this flag checked.
https://github.com/sigp/enr/pull/34
^ here is a PR I made to resolve it.
I think we can still merge this even though we still have this 1 reliance, since our goal is to only have to use ``discv5::enr::NodeId`` and not maintain our own and this is one step closer. In the next version of discv5 we should be able to fully remove our wrapper.
> replace wrapped NodeId with native discv5 type (except for caveat in description)

- ethportal-api/src/types/bootnodes.rs
- newsfragments/773.fixed.md
- portalnet/src/discovery.rs
- portalnet/src/overlay.rs
- portalnet/src/types/messages.rs
- src/lib.rs
- trin-beacon/src/lib.rs
- trin-beacon/src/network.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
I'm not a fan of outputting all 11 of our bootnode enrs on startup & each individual enr on success/failed bonding with said bootnode. It's not very useful information & really clutters the logs.
Before...
```shell
2023-06-09T18:15:01.077921Z  INFO portalnet::overlay_service: Starting overlay service protocol=History
2023-06-09T18:15:01.078302Z  INFO trin_history: About to spawn History Network with boot nodes: { enr:-I24QDy_atpK3KlPjl6X5yIrK7FosdHI1cW0I0MeiaIVuYg3AEEH9tRSTyFb2k6lpUiFsqxt8uTW3jVMUzoSlQf5OXYBY4d0IDAuMS4wgmlkgnY0gmlwhKEjVaWJc2VjcDI1NmsxoQOSGugH1jSdiE_fRK1FIBe9oLxaWH8D_7xXSnaOVBe-SYN1ZHCCIyg, Encoded ENR: enr:-I24QDy_atpK3KlPjl6X5yIrK7FosdHI1cW0I0MeiaIVuYg3AEEH9tRSTyFb2k6lpUiFsqxt8uTW3jVMUzoSlQf5OXYBY4d0IDAuMS4wgmlkgnY0gmlwhKEjVaWJc2VjcDI1NmsxoQOSGugH1jSdiE_fRK1FIBe9oLxaWH8D_ …
```
> Alias bootnodes

- Cargo.lock
- Cargo.toml
We import ENR depend in our Cargo.toml, but only use the one re-exported from discv5, so it is unused.
by removing the unused depend
> Remove unused ENR dependency

- portalnet/src/discovery.rs
If a network bootnode uses the default bootnode list to bootstrap itself into the network, it will inevitably try to connect with itself, which will throw an `invalid self update` error.
This clause checks to make sure that a node never attempts to add itself to its routing table.
> Add catch for bootnode self-update

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/types/discv5.rs
- newsfragments/784.changed.md
- portalnet/src/discovery.rs
The `NodeId `type as a `NodeInfo` field is incompatible with Fluffy and Ultralight and doesn't follow the json-rpc specs. This causes `portal-hive` tests to fail.
Change node id field type to `String`.
> ethportal-api: Change `node_id` field of `NodeInfo` to `String`

- book/src/developers/quick_setup.md
In the section 3.1 of the book, it shares following snippet to interact with trin using python web3 lib:
```sh
>>> from web3 import Web3
>>> w3 = Web3(Web3.IPCProvider("/tmp/trin-jsonrpc.ipc"))
>>> w3.clientVersion
'trin 0.0.1-alpha'
>>> w3.eth.blockNumber
11870768
```
However, clientVersion and eth.blockNumber do not exist on w3. 
I have changed them to block_number and client_version. 
More info here: https://web3py.readthedocs.io/en/latest/examples.html#getting-the-latest-block
> fixed minor typos in book's dev/quick_setup

- ethportal-api/src/types/jsonrpc/request.rs
- newsfragments/772.changed.md
- trin-bridge/src/bridge.rs
- trin-bridge/src/constants.rs
- trin-bridge/src/lib.rs
- trin-bridge/src/main.rs
- trin-bridge/src/pandaops.rs
trin-bridge should provide data for more than one overlay subnetwork. Some refactoring is necessary to enable more solid architecture for adding support for the beacon and state overlay data.
Create a Pandaops middleware structure and encapsulate requesting the data from the DevOps nodes. 
> Refactor `trin-bridge` with PandaOps middleware

- book/src/users/installation/linux.md
> Fixed depends install typo in trin books linux install guide

- Cargo.lock
- newsfragments/785.fixed.md
- trin-bridge/Cargo.toml
- trin-bridge/README.md
- trin-bridge/src/cli.rs
- trin-bridge/src/client_handles.rs
- trin-bridge/src/lib.rs
- trin-bridge/src/main.rs
Add support for trin-bridge to use fluffy as the client it uses to gossip out data to the network.
Added a subcommand to the `trin-bridge` command that requires a user to specify what kind of client is located at `--executable-path` 
> Add support for fluffy-bridge

- portalnet/src/overlay.rs
lookup_enr can prematurely fail if FindNodes errors out. It shouldn't be errored if that is the case, it should continue trying the other ways of finding an enr
by using a if let Ok instead of using a ? (a try statement in rust). This prevents the potential case of lookup_enr failing prematurely
> Prevent lookup_enr failing prematurely if internal FindNodes fails

- newsfragments/793.added.md
- portalnet/src/events.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/tests/overlay.rs
- trin-beacon/src/network.rs
We want to introduce a separate Beacon network service that takes care of the light client mechanics and keeps the node in sync with the tip of the chain. This service needs to listen for the latest `LightClientFinality` and `LIghtClientOptimistic` content updates. Currently, there is no way to listen for an event from the overlay service.
IMO, listening for an event is best done by an event stream. This PR adds an event stream to the `OverlayService` which can emit light client updates events or any other kind of events. As discussed in Boulder, this event stream can be also used for testing and debugging.
> Introduce an event stream to `OverlayService`

- ethportal-api/src/types/enr.rs
- ethportal-peertest/src/scenarios/find.rs
- newsfragments/797.fixed.md
- portalnet/src/types/messages.rs
- tests/self_peertest.rs
I was trying to write tests for portal-hive https://github.com/ethereum/portal-hive/pull/61
And I notice FindContent returning ENRS would fail everytime
I did some debugging and found out it was an issue with serializing. So I used serde derivied serialization and it worked like a charm.
> Fix FindContent Enr failing to serialize and add test

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-api/src/types/enr.rs
- ethportal-peertest/Cargo.toml
- newsfragments/800.fixed.md
- portal-bridge/Cargo.toml
- portalnet/Cargo.toml
- rpc/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
Update discv5 version which has fixes for NodeID serialiation
By updating the dependency.
``let string = base64::encode_config(bytes, base64::URL_SAFE);`` was switched to ``let string = base64::encode_config(bytes, base64::URL_SAFE_NO_PAD);`` since we just used a wrapped of sigp/enr Enr::from_str which uses "URL_SAFE_NO_PAD" I am not sure why we used URL_SAFE, but regardless if ``Enr::from_str()`` doesn't use URL_SAFE us using it will indeed throw an error, so if we want that we have to implement ``Enr::from_str()`` ourselves
> Update discv5 version to 0.3.1 (Fixing NodeId Serialization)

- portalnet/src/overlay_service.rs
`sigp/discv5` provides the `kbucket::closest_values` method, but the `ClosestValue` output of this method does not include information about the connection state of the nodes on which we can filter. So we haven't been filtering disconnected nodes.
Currently out of the 16 nodes that our queries begin with, only an average of 3 respond, which is  **19%**
Iterating over the kbuckets directly and filtering out disconnected nodes, sorting, then taking the top 16.
After this change, an average of 13 / 16 respond which is **81%** 
Testing was done manually using a local glados instance and comparing batches of audit trace results with and without the change.
> Filters disconnected nodes before beginning queries

- Cargo.toml
- ethportal-api/src/history.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/validation.rs
- newsfragments/812.added.md
- portalnet/src/find/query_info.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/tests/overlay.rs
- rpc/src/history_rpc.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/validation.rs
- trin-validation/src/oracle.rs
Add support for boolean `utpTransfer` field in json responses to find content & recursive find content jsonrpc requests.
Repurpose `ContentInfo` response type to accommodate both find content and recursive find content responses. As well as adding the `utp_transfer` field.
> Add utp transfer to find content return

- trin-history/src/validation.rs
When trying to validate a blockbody or receipt we didn't have the header with proof for. ``header_oracle`` would deadlock trying to find the header with proof through a RECURSIVE_FIND_CONTENT request
By changing ``header_oracle.write()`` to ``header_oracle.read()`` where ``write`` wasn't needed
Portal Hive test results with fix
```
INFO[08-10|11:55:26] building image                           image=hive/hiveproxy nocache=false pull=false
INFO[08-10|11:55:26] building 1 clients... 
INFO[08-10|11:55:26] building image                           image=hive/clients/trin:latest dir=clients/trin nocache=false pull=false
INFO[08-10|11:55:29] building 1 simulators... 
INFO[08-10|11:55:29] building image                           image=hive/simulators/portal-interop:latest …
```
> Fix header_oracle deadlocking on history validation

- Cargo.lock
- Cargo.toml
- ethportal-peertest/src/constants.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/basic.rs
- ethportal-peertest/src/scenarios/bridge.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/mod.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- ethportal-peertest/src/scenarios/paginate.rs
- ethportal-peertest/src/scenarios/utp.rs
- ethportal-peertest/src/scenarios/validation.rs
- ethportal-peertest/src/utils.rs
- newsfragments/814.fixed.md
- portalnet/src/overlay.rs
- tests/self_peertest.rs
- trin-history/src/validation.rs
- trin-utils/src/log.rs
Our testing setup for peertest was not ideal. We spin up a small testnet of nodes and use the same testnet for every scenario. This makes testing difficult & non-intuitive, when side-affects from certain scenarios can affect the outcome of later scenarios. Especially relevant for find content tests. 
Initially, I thought that it would be better to simply use unique test values for each scenario. However, this is an unsustainable approach, as we will need to continually generate new test values for each scenario we add. It turns out that the time overhead for spinning up a new peertest for each scenario is really not that bad, and avoids the unneeded complexity of maintaining unique content key/values for each scenario.
- Updated any relevant scenarios to use a fresh peertest testnet.
- …
> Validate find_content result in non-utp transfers & use fresh testnet for each peertest scenario

- Cargo.lock
- portalnet/Cargo.toml
- portalnet/src/discovery.rs
- portalnet/src/overlay_service.rs
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
- utp-testing/src/lib.rs
Handle new APIs:
- &mut self in socket trait methods
- shutdown() -> async close()
Fix #827 
utp library recently had a new release: https://github.com/ethereum/utp/releases/tag/v0.1.0-alpha.6
A (now) unnecessary mutex is wrapped around the discv5 talkreqs in the utp transport layer.
Upgrade utp-rs, fix compile errors related to breaking changes. Also remove the mutex.
> Upgrade utp-rs to v0.1.0-alpha.6 & remove mutex on discv5 transport layer for utp

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-peertest/Cargo.toml
- light-client/Cargo.toml
- light-client/src/rpc.rs
- portal-bridge/Cargo.toml
- rpc/Cargo.toml
- rpc/src/beacon_rpc.rs
- rpc/src/builder.rs
- rpc/src/discv5_rpc.rs
- rpc/src/errors.rs
- rpc/src/history_rpc.rs
- rpc/src/lib.rs
- rpc/src/rpc_server.rs
- rpc/src/serde.rs
- utp-testing/Cargo.toml
- utp-testing/src/bin/test_suite.rs
- utp-testing/src/lib.rs
Fix #786 
Fix #832 
Upgrading reth-ipc requires a jsonpsee upgrade. These two updates have to be combined, otherwise the two different jsonrpsee versions (one for trin, the other for reth-ipc) cause their own build problems.
> Upgrade reth-ipc & jsonrpsee

- portalnet/src/overlay_service.rs
In `init_find_content_query`, `closest_enrs.is_empty()` was being checked redundantly. 
Removed redundancy
> Remove redundant empty-check in content query initialization

- portalnet/src/overlay_service.rs
When a utp connection ID is received at the end of a content query, trin uses `OverlayService::find_enr` to lookup the sender's ENR by its node ID. Currently if it can't find anything it just throws a warning and lets the oneshot get canceled so the query never completes.
The best thing would be for `find_enr` to find the ENR, which I'm working on. In the meantime this PR just has trin send a response back so that the query completes and we can at least see the trace.
> Responds to query if utp peer enr is unknown instead of dropping oneshot

- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- portalnet/Cargo.toml
- src/bin/purge_db.rs
- trin-state/Cargo.toml
An [error](https://gist.github.com/danielrachi/376f43eac9fda2e8f07996a25302ddb0) appeared when building on systems with gcc 13.
Bumped rocksdb version from 0.18.0 to 0.21.0, on all crates.
It was necessary to also update a for loop in `src/bin/purge_db.rs` for trin to compile with the updated rocksdb.
N/A
> fix: bump rocksdb version to 0.21.0

- book/src/SUMMARY.md
- book/src/developers/contributing/rotation/index.md
No structure at all for the person going on rotation.
Started to add some structure to guide the rotation role. Most importantly, the weekly summary and daily checklist that is on notes.ethereum.org.
> docs: add guide for weekly trin Flamingo rotation

- book/src/developers/contributing/releases/deployment.md
- book/src/developers/contributing/releases/release_checklist.md
Fleshed out a lot of instructions, after deploying last week
Fixes #846
> docs: Deployment guide rewrite

- portalnet/src/overlay_service.rs
**blocked till https://github.com/ethereum/portal-network-specs/pull/222 is merged**
There is a update to the spec where we no longer ``list of ENR records of nodes that are closer than the recipient is to the requested content.`` and instead do ``list of ENR records of nodes that are closest to the requested content.``
By removing the filter that compared if a nodes distance was closer then our distance or not
> Remove restriction on closeness of nodes returned on FindContent

- book/src/developers/quick_setup.md
- book/src/users/installation/linux.md
There was no info about how to build Trin on non-debian-based systems.
Added a guide explaining the steps necessary to build Trin on Arch Linux. Also fixed some errors.
The guide was tested on a fresh container built from the [official Archlinux Docker image](https://hub.docker.com/_/archlinux/)
N/A
> docs: add guide on how to build on Arch Linux

- ethportal-api/src/types/node_id.rs
`ethportal-api`'s `NodeId` implementation was missing `random()` method, this was causing problems for glados which was using this method in testing
Implements `NodeId::random()`
> Adds random method to NodeId type

- ethportal-api/Cargo.toml
PR #867 added a method to `NodeId` within `ethportal-api` but should have also bumped the ethportal-api version number to make the crate publishable
bumped to v0.2.2
> Update ethportal-api to v0.2.2

- .github/workflows/stale.yml
As I'm combing through our issues list, I'm finding that we don't have the best track record with tracking issues after they've been opened. I've seen a fair number of duplicate issues, outdated bug reports, and issues that were solved but never close. 
The [Stale Issues Action](https://github.com/actions/stale), introduced here will...
- Run daily
- Add a label "Stale" on issues and pull requests after 60 days of inactivity and comment on them
- Close the stale issues and pull requests after 14 days of inactivity
- If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart
The action itself is very customizable, but imo this default is sufficient to start with and we can adjust it as we see fit.
Introduced github action
[//]: # …
> Add github stale issues action

- .github/workflows/stale.yml
Minor typo from #863 
Fixed typo
> Typo in stale issue message

- ethportal-api/src/types/content_value/beacon.rs
- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/src/beacon_bridge.rs
- portal-bridge/src/consensus_api.rs
- portal-bridge/src/main.rs
Closes #849 
For every slot, we request the latest finalized block root, if a new finalized block root is available, request and serve new `LightClientBootstrap` data.
> portal-bridge: Serve light client bootstrap data

- portal-bridge/src/execution_api.rs
- portal-bridge/src/pandaops.rs
Fixes #830 
Batch requests to a panda-ops provider of > 100 were failing as those clients are configured to handle a max of 100 batch requests at a time.
This bug was the reason why our bridge has not been pumping out receipts. Can confirm that bridge now gossips receipts as expected.
Add a limit to haw many pandaops requests can be batched into a single request.
> Impose limit on batch request size

- ethportal-peertest/src/utils.rs
- portal-bridge/src/beacon_bridge.rs
We can skip variable locking by passing the variable in directly and reassigning it when the method is complete.
An example for #873
> fix(bridge): non-blocking sleep, to publish beacon every 12s && refactor(bridge): Mutex + Atomic to value-passing

- Cargo.lock
- Cargo.toml
- portalnet/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
Includes fix to use the ack_nr from the FIN packet to acknowledge all sent data. This helps prevent the sender from hanging, timing-out, or considering the transfer failed, in some scenarios (especially with dropped STATE packets).
Fixes #888
> chore: upgrade utp-rs to v0.1.0-alpha.7

- Cargo.lock
- light-client/Cargo.toml
- light-client/src/config/checkpoints.rs
After the latest slimming-down of light-client, we could remove ethers
completely. When we eventually add the functionality back in, we are
likely to use internal types instead of the ones from ethers anyway, so
this is probably a permanent-ish change.
I was noticing that a recent PR that added ethers 2.0 for testing the
RPC server was causing CI to crash while building. It seemed like it was
the Out of Memory Killer that sigkilled the build. Ethers was the only
big thing added, so I stripped it down, and that helped some, but while
I was getting familiar with ethers, I thought I'd also do this change to
make the build even a little bit smaller and faster.
The problem was multiplied because light-client was using a different
version of ethers, so two copies were built.
> perf(light-client): faster & smaller builds by removing ethers-rs

- Cargo.lock
- Cargo.toml
- ethportal-api/src/eth.rs
- ethportal-api/src/lib.rs
- ethportal-peertest/src/scenarios/eth_rpc.rs
- ethportal-peertest/src/scenarios/mod.rs
- portalnet/src/overlay.rs
- rpc/Cargo.toml
- rpc/src/builder.rs
- rpc/src/eth_rpc.rs
- rpc/src/lib.rs
- tests/rpc_server.rs
- tests/self_peertest.rs
- tests/utils/mod.rs
- trin-validation/src/constants.rs
Need the `eth_` namespace to accomplish #885 
I think this is the minimal set of changes to implement a new RPC namespace. I'm not totally impressed, because it seems to sprawl a bit. I don't have any ideas for how to improve it yet, besides leaving this PR as a guide.
> feat: add base eth_* rpc & eth_chainID is always 1

- portalnet/src/overlay_service.rs
If there was no connected nodes, we would go into the forloop then our code would fail since it had no connected nodes which was confusing when trying to debug.
I gave this function the same treatment Mike gave for ``init_find_content_query``. We shouldn't go into the forloop if we don't have any nodes to gossip to in the first place.
> Better handle nodes in propagate gossip cross thread when none are connected

- ethportal-api/src/types/content_key/beacon.rs
- portal-bridge/src/beacon_bridge.rs
There is a portal specs [change](https://github.com/ethereum/portal-network-specs/pull/217) that adds slot number to the `LightClientOptimisticUpdateKey` and `LightClientFinalityUpdateKey`.
- Remove the `ZeroKey` struct
- Add the slot number to the content keys
- Update tests
> feat: Add slot number in light client finality and optimistic content keys

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/scenarios/bridge.rs
- ethportal-peertest/src/scenarios/find.rs
- portal-bridge/Cargo.toml
- portal-bridge/src/consensus_api.rs
- portalnet/Cargo.toml
- portalnet/src/discovery.rs
- portalnet/src/overlay.rs
- rpc/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
Bump discv5 dependency to branch that contains support for concurrent requests.
> Bump to discv5 experimental branch for concurrent requests

- Cargo.lock
- portalnet/Cargo.toml
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
We were seeing failed connection attempts fairly regularly on the testnet. This is one step of resolving that issue.
utp-rs is mostly tested using the default configurations, which have changed a few times to improve results. As far as I can tell, the configuration choices here are just an old copy of the config.
So instead of copying in new values, I switched the config to use defaults whenever possible. (which requires using lazy_static) The only custom configuration that seems to matter is that discv5 enforces a custom maximum packet size.
Some reasons I think this will help:
- Number of connection attempts doubles from 3 -> 6
- Idle connection timeout ~doubles from 32->60
- Maximum packet timeout is cut in a quarter from 60->15, for more retries before triggering an idle timeout. …
> fix: improve the utp connection success rate, by using a default config

- portal-bridge/src/bridge.rs
When using history bridge in test mode headers didn't have enough time to be propagated so block bodies and receipts would fail randomly.
By adding the same delay used in the serve block code which was used for the same reason
> Add header saturation delay for history bridge test mode

- portalnet/src/metrics/overlay.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
Add metrics reporting whether or not received content is being successfully validated or not. 
Added metric reporting logic. Update to grafana dashboard template will come in a following pr along with other dashboard changes.
> Add content validation result metrics

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-peertest/Cargo.toml
- portal-bridge/Cargo.toml
- portalnet/Cargo.toml
- rpc/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
New bugfix was submitted in https://github.com/njgheorghita/discv5/pull/5, so we need to bump the `discv5` rev hash to include this change.
- bump rev hash
> Bump discv5 dependency rev hash

- portalnet/src/discovery.rs
fixes https://github.com/ethereum/trin/issues/927
Alternative solution to https://github.com/ethereum/utp/pull/113 
In Galdos there were audits where content would be found but the uTP transfer would fail with the error ``Unable to establish uTP conn based on Content response err=timed out``
Here is a log of the bug 
```nim
2023-09-18T23:19:13.648255Z DEBUG uTP{send=737 recv=736}: utp_rs::conn: uTP conn starting...
2023-09-18T23:19:13.807470Z DEBUG utp_rs::socket: received uTP packet for non-existing conn cid=736 packet=Data seq=30115 ack=27342
2023-09-18T23:19:13.807533Z DEBUG utp_rs::socket: received uTP packet for non-existing conn cid=736 packet=State seq=30113 ack=27342
2023-09-18T23:19:13.807587Z DEBUG utp_rs::socket: received uTP packet for non-existing conn cid=736 packet=Data …
```
> Alternative Solution: Fix ConnectionId hashmap key bug

- .circleci/config.yml
- ethportal-peertest/src/lib.rs
- portalnet/src/overlay_service.rs
- portalnet/src/storage.rs
- src/lib.rs
- tests/rpc_server.rs
- tests/self_peertest.rs
Certain parts of Trin either won't compile on Windows or crash because rust doesn't support windows Unix IPC
By adding ``#![cfg(unix)]`` in files that should only be compile on windows and by adding an error if someone tries to use IPC on Windows.
Reth added ``#[cfg(unix)]`` a few months back so the reth-ipc library will compile it will just crash when we try to use ipc functions.
I also added a CI using ``check`` instead of ``build``
https://doc.rust-lang.org/cargo/commands/cargo-check.html
TL:DR it has all the CI benefits of building but without the codegen part. So it is a lot quicker for the result we want.
> Make Trin compilable/(not crash) on Windows + Add check CI

- portalnet/src/discovery.rs
- portalnet/src/overlay_service.rs
Many `FindContent` queries fail when the result is an uTP stream.  This is because we cannot find the `ENR `of the source `NodeID` and reject the incoming uTP content.
This fix is expected to also improve `FindNode` queries.
Check in the discovery ENR cache when trying to find an `ENR` for a known `NodeId` when processing `FIndContent` and `FindNode` queries.
> fix(overlay-service): Check for peer `NodeId` in discovery ENR cache

- portalnet/src/discovery.rs
- portalnet/src/types/messages.rs
- src/lib.rs
We didn't update the sequence number when we updated fields in our Enr.
If in our ``folderpath/nodeid/trin.enr`` did exist we either update or set the enr sequence according to if we updated a field or not relative to the Enr saved to disk. If a file doesn't exist that means the Enr is new and we set it to 1.
> feat: add increasing Enr sequence on updated Enr

- .circleci/config.yml
CI broke for windows compiling c-kzg-4844 in pr https://github.com/ethereum/trin/pull/942
By updating our windows server version from 2019 to 2022
> chore: update windows server ci version from 2019 to 2022

- ethportal-peertest/src/scenarios/find.rs
- portalnet/src/overlay_service.rs
- portalnet/tests/overlay.rs
While I was debugging the flakiness in #851, I noticed that quite often we see the error ~ `Unable to insert node into routing table, invalid self update`. Indicating that a node is trying to add itself to its own routing table, since it is present in the `Nodes` response from a peer. 
This pr follows the spec update in https://github.com/ethereum/portal-network-specs/pull/230. It filters the "requesting" node out from a `FindNodes` response. We already filter out the "requesting" node from a `FindContent::Enrs` response in https://github.com/ethereum/trin/blob/master/portalnet/src/overlay_service.rs#L1148 & "responding" nodes are automatically omitted from that list
Filter out source node from a `Nodes` response.
> Filter out source node from Nodes response

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/types/execution/header.rs
We didn't have a clean data structure for representing the combined header/block thing that's returned by `eth_getBlockByHash` and friends.
Import the reth-rpc-types for `Block` and add a conversion utility from the trin `Header` into the reth `Header` which is a field in `Block`.
To understand more about how this is used, see #908
> chore: add reth-rpc-types to serialize block to json-rpc

- rpc/src/fetch.rs
- rpc/src/history_rpc.rs
- rpc/src/lib.rs
Want to reuse the logic to make requests to the history network, in #908
> refactor: reuse logic to fetch history content

- portalnet/src/discovery.rs
- portalnet/src/overlay_service.rs
- portalnet/src/types/messages.rs
- portalnet/tests/overlay.rs
- rpc/src/rpc_server.rs
- src/lib.rs
- utp-testing/src/lib.rs
I made a PR https://github.com/sigp/enr/pull/53 and Age Manning gave me the insight that the signature should always be the same in the client if the content is the same.
We had an issue before my increase seq pr and after that even though our enr could be the same, the signature would change which isn't good.
It was fixed by restructuring a bit of my code. I also cleaned it up a bit for how to compare them from suggestions from Age and Nick.
I also resolved a param name nitpik nick had in my last PR.
> fix: enr signature changes on restart even if enr content is the same

- .github/workflows/stale.yml
- Update stale issue bot period to 6 months
- Add `good-community-issue` to exempt labels list
> Update stale issues bot to 6 months

- Cargo.lock
- Cargo.toml
- portalnet/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
We want the fix pushed out by the latest utp release: https://github.com/ethereum/utp/releases/tag/v0.1.0-alpha.8
Upgrade to it
> chore: upgrade utp-rs to v0.1.0-alpha.8

- Cargo.lock
- ethportal-api/src/eth.rs
- ethportal-api/src/types/content_key/history.rs
- ethportal-api/src/types/execution/header.rs
- rpc/Cargo.toml
- rpc/src/builder.rs
- rpc/src/eth_rpc.rs
- rpc/src/fetch.rs
- tests/rpc_server.rs
- tests/utils/mod.rs
Will fix #885 
There are a few little tweaks I have left to do, but nothing standing in the way of a review, IMO. Everything planned is unchecked below. I may just skip the 944 rebase, since it is relatively small, and can probably be reviewed together in this PR. (and I don't want to add unnecessary delay, so I can move on to transactions & uncles)
> feat: support eth_getBlockByHash over json-rpc (only with header fields, for now)

- .github/PULL_REQUEST_TEMPLATE.md
We no longer use towncrier, so we should remove the line from the pr template
> docs: remove outdated towncrier line from template todo

- book/src/developers/contributing/rotation/index.md
Added guideline for flamingo schedule to docs.
> docs: add flamingo schedule

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-peertest/Cargo.toml
- rpc/Cargo.toml
Building against a moving target is hard. It's just good practice to have everyone working against a consistent version of the dependency anyway. The "version" attribute was basically ignored by cargo.
So those are the theoretical reasons. Here is a practical one: Basic things are changing about the RPC structs, like the type of the transaction hashes, even in just the last few weeks.
Split from #963
> chore: pin reth dependencies to a release

- portalnet/src/overlay_service.rs
- portalnet/src/storage.rs
I was debugging gossip and then getting
```nim
2023-10-10T00:02:24.255068Z  WARN portalnet::overlay_service: Accepted content outside radius or already stored content.key=0x00389863ef224a3d170b0d396387c31a39eb0cda2b59aee881cd8aaa3a2e73c5e4
2023-10-10T00:02:33.252706Z  WARN portalnet::overlay_service: Accepted content outside radius or already stored content.key=0x029031e54f5b379e53a959fb3ac11b52c7943c1f06d4f5bb061da60a8573f2301f
2023-10-10T00:02:56.485819Z  WARN portalnet::overlay_service: Accepted content outside radius or already stored content.key=0x035688720000000000
2023-10-10T00:02:56.569614Z  WARN portalnet::overlay_service: Accepted content outside radius or already stored content.key=0x035b88720000000000
2023-10-10T00:02:56.690561Z  WARN portalnet::overlay_service: Accepted …
```
> chore: change bool to enum for is_key_within_radius_and_unavailable for better errors

- ethportal-api/src/types/content_key/history.rs
- rpc/src/eth_rpc.rs
- rpc/src/fetch.rs
- tests/rpc_server.rs
> Add transaction hashes and uncles to the block that json-rpc returns

- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
When I would ping nodes I would recieve the wrong data_radius, turns out ping was giving me our data radius back
By decoding the data radius from the pong instead of returning our nodes data_radius
> fix: bug ping rpc returns our radius instead of target's

- portalnet/src/overlay_service.rs
The errors which hard to grep through and organize. Also we used unwrap_or which was potentially dropping important information
By changing the unwrap_or to a match case.
I added more detailed trace logs including enr, cids, which content keys a connection was using. I added content_keys to all the respective error logs so you can just grep by x key and it will all be there.
> chore: add more detailed logs to handle offer code

- portalnet/src/discovery.rs
- portalnet/src/overlay_service.rs
- trin-utils/src/log.rs
fixes https://github.com/ethereum/trin/issues/940
by adding info as the default log level. Then setting discv5 to Error cause it is super noisy.
https://stackoverflow.com/a/67310139 < apparently log level hierarchy is in order of ``error`` > ``warn`` > ``info`` > ``debug`` > ``trace``. So by enabling info we are also enabling warn.
```nim
/home/kolby/.cargo/bin/cargo run --color=always --package trin --bin trin
Finished dev [unoptimized + debuginfo] target(s) in 0.68s
Running `target/debug/trin`
2023-10-18T01:00:53.405856Z  INFO trin: Launching Trin: v0.1.1-alpha.1-de638d
2023-10-18T01:00:53.405942Z  INFO trin: With: config=TrinConfig { networks: ["history"], capacity_mb: 100, ephemeral: false, json_rpc_url: /tmp/trin-jsonrpc.ipc, metrics_enabled: false }
2023-10-18T01:00:53.413046Z  INFO …
```
> feat: make info log default level in most cases

- ethportal-api/src/types/cli.rs
- portalnet/src/config.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- trin-history/src/network.rs
#766 
Disabling the poke mechanism is useful for keeping a clear, unaffected view of the network while doing network analysis eg in glados. 
Kind of like how when you're fishing, throwing a fish back in will disturb the water. 🐟 
Adds `--disable-poke` flag to Trin, and passes it into the `OverlayService` where poking is handled.
Tested manually.
> Adds disable poke CLI flag to trin

- portalnet/src/events.rs
If you run trin with beacon ie `trin --networks history,beacon` and then later run with only history ie `trin --networks history`, you will still receive TALKREQ packets from nodes on the portal beacon network. These will cause `ERROR portalnet::events: Beacon event handler not initialized!` which is a little over the top for something that's not really a problem.
Added some extra context and turned it down to `debug` level
> Get rid of error message for uninitialized networks

- portalnet/src/gossip.rs
- portalnet/src/lib.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
A bit of preparation for #962. Basically, in order to track the success rate & peers from gossip results, we'll need to introduce a new `propagate_*` utility function. In order to reduce the bloat to `overlay_service.rs` it seems like a good time to move this code to it's own module. 
- Moved gossip related code to separate module.
> Relocate gossip code to separate module

- ethportal-api/src/types/query_trace.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/utp.rs
- portalnet/src/find/iterators/findcontent.rs
- portalnet/src/find/query_info.rs
- portalnet/src/overlay_service.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
Changes to the `portal_*TraceRecursiveFindContent` endpoint in the [specs](https://github.com/ethereum/portal-network-specs/pull/236) needed implementation.
Fixes #987 
- Implemented changes to endpoint
- Changed `ContentId` type from `NodeId` -> `[u8; 32]`
> Update trace-recursive-find-content response to match spec changes

- ethportal-api/src/types/content_key/beacon.rs
- portal-bridge/src/beacon_bridge.rs
Beacon network [specs](https://github.com/ethereum/portal-network-specs/blob/master/beacon-chain/beacon-network.md#lightclientfinalityupdate) require a finalized slot to be included in `LightClientFinalityUpdate`'s content key.
- Use the finalized instead of the signature slot in the `LightClientFinalityUpdate` content key.
- Update beacon bridge to serve `LightClientFinalityUpdate` content only if the finalized slot changes.
- Improve some beacon bridge logs. 
> Use `finalized slot` in `LightClientFinalityUpdate` content key and update beacon bridge to serve the data.

- .github/workflows/release.yml
Manually adding binaries for a release is a PITA.
Added a git action workflow which should create a new draft release with binaries included on a new git tag push
> chore: Automate release on new git tag push

- portal-bridge/src/beacon_bridge.rs
- portal-bridge/src/bridge.rs
- portal-bridge/src/lib.rs
- portal-bridge/src/main.rs
- portal-bridge/src/stats.rs
Updated the bridge gossip stats to accurately reflect what was gossiped, using the new trace gossip result type. The idea is to make grepping through the bridge logs a feasible way to figure out whether content was successfully gossiped into the network.
- Added improved metrics and logs to beacon and history bridge processes
> Log detailed gossip results from bridge processes.

- portal-bridge/src/bridge.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/client_handles.rs
this is required for the rewrite of the hive bridge test I am writing
Without the timeout bridge closes without the finishing uTP transfers.
Without being able to set bootnodes I can't test this as it wouldn't be valid
Without being able to set external ip the trin node can't be connected to from the other docker containers
below is the chat history of the problem we are trying to solve.
https://github.com/ethereum/portal-hive/pull/110#discussion_r1372181073
https://github.com/ethereum/portal-hive/pull/110#discussion_r1372183148
https://github.com/ethereum/portal-hive/pull/110#discussion_r1372187887
this PR is required to make the sister pr on portal hive https://github.com/ethereum/portal-hive/pull/115
By adding 2 params required to write the test
> chore: add bootnodes,external-ip cli to bridge to support hive test

- etc/grafana/dashboards/collected-metrics-dashboard.json.template
- etc/grafana/dashboards/trin-bench-trin-metrics-dashboard.json.template
- ethportal-api/src/dashboard/grafana.rs
- ethportal-api/src/types/cli.rs
Local dashboard template needed updating to include newly available metrics.
Fixes #871 
- updated metrics template
- fixed broken asset path
- added some notes to help avoid gotchas while testing updated template
- added dashboard template from `trin-bench`'s `Trin Metrics` dashboard for backup
> Update local metrics dashboard

- portal-bridge/src/cli.rs
- portal-bridge/src/client_handles.rs
Bridge cli default value for `external_ip` was `"none"` when it should have been an `Option`
Updated default value. Tested locally and bridge does successfully gossip content
> fix: use option for bridge external ip cli arg

- .github/workflows/ci.yml
Since `trin`'s entire commit history (on master) doesn't follow conventional commit formatting, we don't want to run the commitlint check on pushes to master but only on pull request actions.
> Only run commitlint on pull_request action

- portalnet/src/discovery.rs
Assume client A and B don't have a session together
A wants to send B a Ping or FindContent request
```mermaid
sequenceDiagram
participant Node1
participant Node2
Note over Node1: Start discv5 server
Note over Node2: Start discv5 server
Node1 ->> Node2: PING message packet encrypted with unknown key
Node2 ->> Node1: WHOAREYOU packet including id-nonce, enr-seq
Node1 ->> Node2: PING handshake message packet, encrypted with new initiator-key
Node2 ->> Node1: PONG encrypted with new recipient-key
```
diagram of if a new session needs to be formed ^
```mermaid
sequenceDiagram
participant Node1
participant Node2
Note over Node1: Start discv5 server
Note over Node2: Start discv5 server
Node1 ->> Node2: PING
Node2 ->> Node1: PONG
```
diagram of if a session already exists ^
Currently there is a …
> chore: increase discv5 request_timeout from 1 to 3 seconds

- Cargo.lock
- portalnet/Cargo.toml
- portalnet/src/events.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/src/types/messages.rs
- portalnet/tests/overlay.rs
- src/lib.rs
- tests/rpc_server.rs
- trin-beacon/src/events.rs
- trin-beacon/src/lib.rs
- trin-history/src/events.rs
- trin-history/src/lib.rs
- trin-state/src/events.rs
- trin-state/src/lib.rs
This pull enables the portalnets handler to subscribe to the event stream of each of the overlays it handles, and redistribute events to all overlays except the one that emits it. This allows an event discovered on one layer to be useful across multiple others.
> Enable communication between overlays

- Cargo.lock
- ethportal-api/src/types/discv5.rs
- ethportal-peertest/src/scenarios/basic.rs
- portalnet/src/discovery.rs
- portalnet/src/overlay.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
Loosely defined RoutingTableInfo type.
Closes #862
Changed RoutingTableInfo to a struct according to the specification. The Routing table consists of a `localNodeId` field and a `buckets` field which is represented as a nested array of node-ids, with each inner array representing a single bucket in the k-buckets table. 
The serializable types represent node_id as a `String`(hex-encoded) so as to conform to the serialization and deserialization scheme proposed by the specs. This is a workaround for the fact that the `NodeId` type exported by the enr crate only supports default serialization and deserialization to and from a `bytes32`, which is possibly a reason why `RoutingTableInfo` was defined as a `Value` in the first place(#862).
> feat: define concrete type for RoutingTableInfo

- portal-bridge/src/client_handles.rs
There has been a breaking change from `--storage-size` to `--storage-capacity`.
Arguments are adjusted.
Also the IP limits have been set (temporarily) to higher defaults.
And the network setting is default now the mainnet "testnet" since a while.
So those args are no longer needed and have been removed.
> chore: adjust fluffy cli arguments for portal-bridge

- ethportal-api/src/types/cli.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/main.rs
- portal-bridge/src/utils.rs
In our bridge architecture, we spin up multiple bridge nodes, but their private keys are currently randomly generated. We want the option to provide custom private keys so that we can ensure the bridge nodes are equally distributed around the keyspace.
- Added cli option for providing custom private keys to bridge nodes
> feat: add cli option for root private key in bridge

- portalnet/src/overlay_service.rs
during devconnect Mike brought up glados's cartographer was trying to ping 1800 enrs, because trin nodes were returning disconnect nodes.
I don't think we should remove the last resort of using disconnected nodes to initialize a RFC/RFN. Since the last resort will only be used if there are 0 connected nodes in the whole routing table which should only happen on startup.
in short I believe this is the right solution
This can also be in glados audits
In this picture the Trin node is returning Enr's of disconnected nodes which haven't run for over a month. The trin node returned these because it sorted by distance without filtering out disconnected first. This PR adds the filter so that should no longer happen.
by filtering out disconnected nodes by status
I applied to filter to both the …
> fix: filter out disconnected nodes on Node/(Content Enr) response

- book/src/developers/contributing/releases/deployment.md
Add step to remind deployers to pull latest master from cluster repo
---
> docs: add pull latest master deployment scripts to deployment steps

- portal-bridge/src/beacon_bridge.rs
- portal-bridge/src/bridge.rs
- portal-bridge/src/gossip.rs
- portal-bridge/src/lib.rs
- portal-bridge/src/stats.rs
Bridges only made one gossip attempt, and gave up. This isn't ideal. The bridge gossip strategy has been updated to...
- attempt a gossip
- if no content was successfully **transferred**, make a rfc request
- if content is found on the network, abort the gossip
- if the bridge is unable to find the data on the network, wait 15 seconds and try another gossip / rfc cycle
- repeat for a maximum of 3 times before giving up
Testing locally, I've seen all kinds of cases, which is encouraging. eg.
- bridge successfully transfers data without retries
- bridge unsuccessfully transfers data, but finds it on the network and aborts
- bridge retries gossip multiple times, and makes a successful transfer on a retry
- bridge retries gossip multiple times, but finds it on the network after a retry and …
> feat: add retries to bridge gossip, with rfc network checks

- light-client/Cargo.toml
`/usr/bin/trin: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory` when running a docker image built from trin's `docker/Dockerfile`.
I thought it was interesting that @njgheorghita saw this error but his instance kept running normally.
This was caused by this commit on master https://github.com/ethereum/trin/commit/00cbbd8e73ba6c1e92e4df609862e5401a20d543
Which started using openssl through our reqwest library
By changing ``reqwest = { version = "0.11.13", features = ["json"] }``
to
``reqwest = { version = "0.11.13", default-features = false, features = ["json", "rustls-tls"] }``
``default-features = false`` disables openssl from being used
``features = ["rustls-tls"]`` enables using the rust native tls library
Kolby tested the …
> fix: Uses ``rustls-tls`` for ``reqwest`` instead of requiring ``openssl``

- .circleci/config.yml
- book/src/developers/contributing/releases/release_checklist.md
We had an issue where the docker image tagged for testnet couldn't be run, it was missing a library. 
Adds a step to the CI that attempts to run the docker image (with the `-h` flag for immediate but successful exit).
Adds a step to release steps to check that the master CI was successful for what we're about to deploy. This both applies to the docker image, as well as to the testing iteself, which I realized was also failing for the latest commit on master after having deployed a broken docker image.
> fix: add deployment step to confirm that docker images can be run

- ethportal-api/src/types/cli.rs
I can't disable --no-upnp on glados, I thought since ``--no-upnp`` was in ``external-ips`` group it would disable it, because if ``--no-upnp`` is in the ``external-ips`` group you can only choose to use on of the cli options.
by removing ``--no-upnp`` from the ``external-ips`` group. No we can activate ``--no-upnp`` and (``external-ip`` or ``--no-stun``) at the same time
> fix: remove --no-upnp from "external-ips" group

- ethportal-api/src/types/content_value/beacon.rs
- ethportal-api/src/types/content_value/history.rs
- portal-bridge/src/bridge.rs
- portal-bridge/src/pandaops.rs
`Retry` logic is better suited to be located alongside the other pandaops request logic. 
- Relocated `Retry` type
- Fixed a couple of lint errors
> refactor: relocate retry logic

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-api/src/types/enr.rs
- ethportal-peertest/Cargo.toml
- light-client/Cargo.toml
- portal-bridge/Cargo.toml
- portal-bridge/src/utils.rs
- portalnet/Cargo.toml
- portalnet/src/discovery.rs
- portalnet/src/storage.rs
- portalnet/src/utils/db.rs
- rpc/Cargo.toml
- src/bin/purge_db.rs
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-state/Cargo.toml
- utp-testing/Cargo.toml
Bump `discv5` library to latest `0.4.0` version.
This includes native concurrent discv5 requests, and the latest `enr` library dependency.
> Bump discv5 version dependency

- portal-bridge/src/constants.rs
Investigating some of the issues with our bridge provider.
1. The assumption that we were simply not able to deserialize the requests from different clients seems to have been "mostly" disproven.
- I don't even think this is a valid concern, I would be shocked if production execution clients have jsonrpc responses formatted differently from each other. I mean that's the entire point of the spec. Of course... I haven't thoroughly audited all jsonrpc responses from different clients, but I think this concern has been a bit of a red herring.
2. It seems like the cause of most of our issues is dshackle. A new load-balancing service that routes "most" of the requests to the pandaops nodes. All pandaops urls use dshackle (as of today) except for those that have an explicitly defined `el-cl` …
> fix: update base el endpoint for bridge provider

- ethportal-api/src/types/bootnodes.rs
Need to update our bootnode enrs to match https://github.com/ethereum/portal-network-specs/pull/244/files
> fix: update hardcoded trin bootnode enrs

- ethportal-api/src/types/content_key/beacon.rs
- portalnet/src/storage.rs
- trin-beacon/src/network.rs
_This PR is open against the upstream `remove-rocksdb`  branch._
We need different storage mechanics for the Beacon portal network
- create a `BeaconStorage` struct which implements the `ContentStore` trait used by the overlay service.
- create a new `lc_update` SQL table for storing and querying `LigthClientUpdate` content (see #1006).
- Add beacon specific implementations to all `ContentStore` methods.
- some common utils for `PortalStorage` and `BeaconStorage` were extracted
It may be useful to review this PR commit by commit.
All storage code and SQL queries are in a single `storage.rs` file, which is a mess. We will refactor this at a later stage.
Ideally, we want to rename `PortalStorage` to `HistoryStorage` but I prefer to do this in a separate PR because I don't want to introduce …
> Add Beacon Storage

- light-client/src/config/cli.rs
- light-client/src/config/networks.rs
- light-client/src/config/utils.rs
- light-client/src/consensus/consensus_client.rs
- light-client/src/consensus/types.rs
- light-client/src/consensus/utils.rs
- light-client/src/lib.rs
- light-client/src/node.rs
This PR fıxes #1045.
Mostly done by using `expect` to make clippy happy. On de/serializer functions, I used serde errors and returned them.
I didn't touch any test code.
> fix: remove naked unwraps in `light-client` crate

- portal-bridge/README.md
- portal-bridge/src/bridge/beacon.rs
- portal-bridge/src/gossip.rs
- portal-bridge/src/main.rs
I was trying to read through bridge logs and I couldn't tell if they were coming from the history or beacon bridge. This makes grepping and debugging hard.
with this change all the logs generated by the history bridge are marked by history and all the logs generated by the beacon bridge are tagged with beacon
```nim
2024-01-06T15:47:10.139336Z  INFO history: surf::middleware::logger::native: request completed    
2024-01-06T15:47:10.143257Z DEBUG history:send_async{method=POST uri=https://erigon-lighthouse.mainnet.eu1.ethpandaops.io/}:handler{id=8}: isahc::handler: Connection #0 to host erigon-lighthouse.mainnet.eu1.ethpandaops.io left intact
2024-01-06T15:47:10.290635Z DEBUG history: portal_bridge::bridge::history: Gossip: Block #18949112 Receipts
2024-01-06T15:47:10.321927Z DEBUG …
```
> feat: add an instrument to portal-bridge for more clear logs

- ethportal-api/src/beacon.rs
- ethportal-api/src/history.rs
- ethportal-api/src/types/beacon.rs
- ethportal-api/src/types/history.rs
- ethportal-api/src/types/mod.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/utp.rs
- ethportal-peertest/src/scenarios/validation.rs
- portal-bridge/src/gossip.rs
- portalnet/src/storage.rs
- rpc/src/beacon_rpc.rs
- rpc/src/history_rpc.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-validation/src/oracle.rs
I was looking into getting a foundation built out so we can have beacon tests on portal hive and I ran into a issue oh no.
Beacon RFC was out of date with the spec, then I found for FC, RFC, TRFC, PLCK we were returning history Key/Value types :scream: 
By making variants of ContentInfo, PaginateLocalContentInfo, TraceContentInfo for beacon and using them
> fix: use beacon types for beacon rpc instead of history types

- portal-bridge/src/bridge/history.rs
we need to merge this PR first https://github.com/ethereum/trin/pull/1081
serve() can block new blocks from being gossipped for a very long time currently before waiting a worse case right now is
10s wait for letting head propagate
15s * (3 (header, body, receipt)
60s * 3 if trin was the only bridge and we gossiped to a fleet of empty fluffy nodes. The uTP transfer would be successful technically but trin uTP would return a close failure. RFC would find it and return successful though
that is a wait of 3m 55s.
maybe there are other combinations which are worse, but the point is we don't want this to block latest blocks from starting the process of being gossiped.
Instead of awaiting a vector of handles, we just spawn new tokio threads for each block we are gossiping. now serve() can't …
> fix(bridge): prevent await from blocking new gossips

- Makefile
I'd rather remove the `--check` flag from the newly updated makefile `lint` commands. It makes sense to leverage the automatic correction of these lints rather than going through manually and fixing each error.
Removed the flag from the makefile `lint` commands.
> style: remove check flag from makefile lint

- portal-bridge/src/bridge/history.rs
this is a new solution for https://github.com/ethereum/trin/pull/1087 me and nick jumped on a call and disscussed it and decided for each of us to take stabs at what we think the best solution is and compare them side to side and merge the best one.
- By adding semaphore's to limit the amount of gossiping at a time.
- adding a timeout on serve_full_block() in case a timeout bug happens
> feat(bridge): add (semaphore to limit gossips) + (timeout on gossips) for history backfill

- portal-bridge/README.md
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/types/mode.rs
Nick said he wanted backfill by block range for making his kurtosis tests. I already wrote most of the code for it in a previous PR so  here is the PR with that.
If this PR doesn't suit what you imagined Nick just close it and open a new one no biggy. I am not too picky about this, just thought it could save you some time which is why I mentioned it. If this PR is 90% percent the way there of course I would be happy to get this reviewed and merged.
This includes the block range change + a quick refactor I did to make it so backfill used block ranges as a whole. This simplifes the code a lot and removes a whole while loop which is code. Functionally both of these will perform the same. Without this refactor adding the backfill via block range code felt awkward.
> feat(history bridge): add backfill by block range

- Cargo.lock
- portalnet/Cargo.toml
- portalnet/src/utils/db.rs
Fixes #941 
Used `hex::encode` directly to encode node id.
> fix: remove `0x` prefix from trin node data directory

- Cargo.lock
- Cargo.toml
- docker/Dockerfile
- docker/Dockerfile.bridge
- src/bin/poll_latest.rs
- src/bin/sample_range.rs
Added two scripts to help with quick & easy network testing. These are meant to be "backups" to glados, but also will be very useful for running tests on kurtosis.
Later, I'd like to implement support for providers other than infura, but given that `audit_latest` requires a `ws` connection, which is really only "easily" available via infura (eg. pandaops doesn't support this), then I figured pandaops / generic provider support can wait
- `audit_latest` script, which will basically poll how soon "latest" data appears on the network
- `sample_range` script, which samples X number of randomly selected blocks from any given range
> Add poll_latest and sample_range scripts

- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/constants.rs
- portal-bridge/src/main.rs
After some initial testing, the `archive.mainnet.ethpandaops.io` endpoint is clearly superior to the `geth` / `erigon` endpoints w/ regards to successfully creating receipts (aka it has access to what I assume are receipts being pruned on `geth` / `erigon`).
This is sort of a hotfix. While it will improve the amount of valid receipts making it into the network (which is a good thing), it's still not 100% from my experiments. Imo, we should go ahead and merge this update. But I'm happy to hold off on this change until we figure out why it's not quite hitting 100%.
> fix(bridge): use archive endpoint for backfill

- trin-beacon/src/storage.rs
- trin-history/src/storage.rs
- trin-storage/src/sql.rs
resolve: #1097
added storage calculation as described in the issue
> feat: report correct storage metrics for beacon and history

- portal-bridge/src/constants.rs
Ok, I was wrong in #1104 . After some experiments using #1106 and the error handling in #1108 , it's clear that the `erigon-*` endpoint is better at creating historical receipts. 
However, I do think it's useful to keep the distinction between a "backfill" endpoint and a "latest" endpoint.
It's still not perfect, but at least it appears to be competent in creating historical receipts that don't involve a "state_root". That pre-byzantium issue still needs addressing. 
- Changed the endpoint.
> fix: change backfill provider to erigon

- ethportal-api/src/types/cli.rs
- portalnet/src/gossip.rs
- portalnet/src/lib.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/src/utp_controller.rs
- portalnet/tests/overlay.rs
- src/lib.rs
- trin-beacon/src/lib.rs
- trin-beacon/src/network.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
Currently Trin can open up limitless uTP streams. 
X = base X amount of memory trin uses
Y = arbatrary statical average each new uTP connection incurs
So currently Trins memory usage is =  X + (Y * (# of connections))
This is unbounded growth, this PR proposes to set a configurable limit of how many inbound and outbound uTP connections can be made to the node.
I am proposing this limit for connections that are incurred from the node running itself, not requestions started from JSON-RPC requests.
It is very common for ISP's to provide high download speeds but low upload speeds. So being able to set these seperately can help people who face those kinds of constraints.
Requests initiated by rpc, we can add a seperate limit if we want but this is a user experience kind of thing. If a user is …
> feat: add utp transfer limit for requests not initiated by rpc

- portal-bridge/src/types/e2s.rs
- portal-bridge/src/types/mod.rs
In `portal-bridge` we'll soon need the ability to read/write era1 files. These are the initial set of utils for reading/writing `e2s` files, which are the standard format that `era1` files are based on
- Implemented basic encode/decode functionality for `e2s` files
- Added standard test vectors
> feat: initial utils for reading/writing e2s files

- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/constants.rs
- portal-bridge/src/lib.rs
We need a better way to switch between pandaops provider endpoints. For example, the `erigon` nodes went down the other day, breaking our bridge. The only way to change this would be to update the hardcoded `BASE_*_ENDPOINT` variables, then cut a new release, and then deploy the new release. With this change, we can simply change the env variable in the deployment scripts and re-run the deployments. 
*Note* - These env variables will override the default values for pandaops endpoints. If the user selects a non-pandaops provider via the cli flag, the env variables will be ignored. 
- Added the feature to select the pandaops provider endpoint via env variable
> feat: configure bridge provider via env variable

- book/src/developers/contributing/releases/deployment.md
supercedes https://github.com/ethereum/trin/pull/1119 We didn't have instructions to do glados's deployment
Also glados's ansible playbook was broken glados Trin instance hasn't been updated in 6 weeks https://github.com/ethereum/cluster/pull/923 here is the fix
^ before ansible fix
^ after ansible fix
Wrote the instructions and fixed the playbook
> feat: add instructions for glados deployment

- .circleci/config.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- Cross.toml
- Makefile
- book/src/developers/contributing/build_instructions/linux.md
- book/src/developers/quick_setup.md
- ethportal-peertest/Cargo.toml
- portal-bridge/Cargo.toml
- trin-history/Cargo.toml
We integrated a GitHub action to release pre-compiled binaries on `git push <tag>` but we missed an updated Make file with the required commands.
1. Updated the Make file with commands to compile for the following architectures using [cross](https://github.com/cross-rs/cross):
- x86_64-unknown-linux-gnu
- aarch64-unknown-linux-gnu
- x86_64-pc-windows-gnu
- x86_64-apple-darwin
- aarch64-apple-darwin
2. Removed OpenSSL from dependencies because it caused issues with compiling on aarch64 linux.
3. Some docs cleanup on the requirements for compiling openssl.
> Cross-compile Trin on a new release

- ethportal-api/src/types/execution/block_body.rs
- ethportal-api/src/types/execution/transaction.rs
We had a custom implementation of the `Encodable`/`Decodable` rlp traits for `Transaction`. These were removed in favor of actually implementing those traits
- Removed redundant implementations
> refactor: remove duplicate transaction rlp implementations

- ethportal-api/src/lib.rs
- ethportal-api/src/types/content_key/beacon.rs
- ethportal-api/src/types/content_key/history.rs
- ethportal-api/src/types/content_key/overlay.rs
- ethportal-api/src/types/content_key/state.rs
- ethportal-api/src/types/content_value/beacon.rs
- ethportal-api/src/types/content_value/history.rs
- ethportal-api/src/types/content_value/mod.rs
- ethportal-api/src/types/content_value/state.rs
- ethportal-api/src/types/mod.rs
- ethportal-api/src/types/state.rs
- ethportal-api/src/utils/bytes.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/storage.rs
- trin-history/src/jsonrpc.rs
- trin-validation/src/accumulator.rs
There was repetative logic for serializaion and deserialization of the `<T>ContentKey` and `<T>ContentValue` types.
The state types also didn't implement it yet.
- Refactored functions by extracting common functions into `OverlayContentKey` and `ContentValue` types, and reusing them.
- Implementing missing logic in state types
fix: #1114
> refactor: refactor serialization for content key and values

- ethportal-api/src/types/bytes.rs
- ethportal-api/src/types/consensus/body.rs
- ethportal-api/src/types/consensus/execution_payload.rs
- ethportal-api/src/types/consensus/serde.rs
- ethportal-api/src/types/execution/header.rs
- ethportal-api/src/types/portal_wire.rs
- ethportal-api/src/types/state_trie/mod.rs
- ethportal-api/src/types/state_trie/nibbles.rs
I noticed that we have a type called `ByteList`, which was just:
```
type ByteList = VariableList<u8, typenum::U2048>;
```
I liked the idea considering that `VariableList<u8, ...>` is somewhat common, but I didn't like that the length is somehow assumed.
I renamed the type to `ByteList2048` and I introduced similar types (for lengths that appear in the codebase).
> refactor: replace VariableList<u8, X> with ByteListX types

- ethportal-api/src/types/content_key/state.rs
The StateContentKey tests weren't using test vectors from `portal-spec-tests` and they weren't testing serialization.
I rewrote the tests and added new one.
> feat(state network): improve StateContentKey tests

- .github/workflows/release.yml
Github release workflow is [failing](https://github.com/ethereum/trin/actions/runs/7796150696/job/21265228082)
Update gpg pub key and release command
> chore: fix github release workflow

- Cargo.lock
- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/Cargo.toml
- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/constants.rs
- portal-bridge/src/main.rs
Depending on the EL provider we can overwhelm it with requests. Or some providers have a request limit per a day. This is a problem because we don't want to overwhelm/(go over our api limit on something like infura)
By adding surf_govener api rate limiter
> feat(bridge): add EL api ratelimit

- Cargo.lock
- portal-bridge/Cargo.toml
- portal-bridge/src/api/execution.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/bridge/mod.rs
- portal-bridge/src/bridge/utils.rs
- portal-bridge/src/main.rs
- portal-bridge/src/types/era1.rs
- portal-bridge/src/types/mode.rs
We want to use era1 files as our data source for gossiping pre-merge content, to relieve some of our dependency on live providers. 
It may be possible to achieve this feature more elegantly, but for some reasons, I decided against trying to integrate the `HistoryBridge` with `era1` file compatibility.
- we still want to support live providers in the `HistoryBridge`
- data sources are different (eg http requests to era1 file sources & live providers)
- validation model is different for data from live providers & era1 files
For these reasons, it seems like the best way forward is to implement a new "kind" of bridge, `Era1Bridge`. 
The `Era1Bridge` takes a directory of `era1` files, processes them all and then gossips out the data.
A few to-dos remain, which will be handled in upcoming prs …
> feat(bridge): add support for gossiping from era1 files

- Cargo.lock
- ethportal-api/src/types/jsonrpc/endpoints.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/basic.rs
- ethportal-peertest/src/scenarios/find.rs
- tests/self_peertest.rs
- trin-state/Cargo.toml
- trin-state/src/jsonrpc.rs
- trin-state/src/network.rs
- trin-state/src/storage.rs
State network doesn't have any endpoint implemented.
I added implementation for the enr and node_id related queries.
Next steps are:
- Implement `StateStorage` (at least minimal support for now)
- Implement the rest of the endpoints
> feat(state_network): implement enr and node_id endpoints for state network

- portal-bridge/src/types/e2s.rs
- portal-bridge/src/types/era1.rs
Converting bytes to rust types and rust types to bytes is common as serializing and deserializing.
Even if we don't use the serde framework for deserializing/serializing Era files (at this stage), I think it is nice if we don't deviate much from the common concepts.
- rename `File` to `E2storeFIle`
- Reading from a byte slice is confusing with reading into a buffer which is typical to [Readers](https://doc.rust-lang.org/std/io/trait.Read.html). To remove this confusion, I renamed `read` to `deserialize` because this is what we are trying to do here: deserialize from a byte slice into a type.
- To keep consistent with the above, I renamed `encode` to `serialize`.
> refactor(e2store): refactor e2store utils

- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/constants.rs
Yesterday when testing the bridge we found that a surf http  request took 6 minutes to respond. We assume this is becase the provider took forever to respond. Either way we don't want to wait 6 minutes + to timeout if a provider can't respond in a responsible about of time we should give up and log it, so we aren't confused why we aren't seeing logs.
by setting a 20 second timeout in surf.
I choose 20 seconds to be conservative. I don't believe any provider request should take over 1s and if that does happens the provider is overloaded.
> feat(bridge): add http request timeout to prevent requests over 6 minutes

- portal-bridge/src/bridge/history.rs
Currently if a provider is working, but falls out of sync with the chain we report 0 logs that the history bridge is alive or something is wrong or not. If this case happens it is a clear case the EL provider is out of sync so we should inform the user regardless.
Add a counter which prints an error if the provider doesn't give us a new block for over a minute.
This error could go off if the provider down as well either way we want to ring some bells something is wrong with the provider.
> feat(bridge): history latest log error if provider isn't giving new blocks

- Cargo.lock
- portal-bridge/Cargo.toml
- portal-bridge/README.md
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/main.rs
- portal-bridge/src/types/era1.rs
Source `era1` files from `https://era1.ethportal.net` instead of the local test folder. Randomly shuffle the `era1` files and then gossip out their content.
- added support for fetching `era1` files & randomly shuffling them
> feat(bridge): use ethportal.net as source for era1 files

- Cargo.lock
- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/Cargo.toml
- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/constants.rs
- portal-bridge/src/lib.rs
- portal-bridge/src/main.rs
- src/bin/test_providers.rs
When the rate limiter was added, it seems to me like this broke our bridge. Locally (running just trin & inside kurtosis), I'm consistently unable to request any data from any provider, latest / backfill mode. 
The culprit appears to be `GovernorMiddleware::with_period(period)`.. it just doesn't appear to be performing as expected. I've updated it to use the `GovernerMiddleware::per_hour()` limit api, which solves the problem locally. 
- changed default el provider to `geth`, since `erigon` is down
- added some debug logs
- removed the rate limiter (aka governer) and the concept of a daily rate limit
> fix(bridge): change rate limiter period calculation

- portal-bridge/src/main.rs
Our subnetwork logs only have the per/subnetwork `Instrument` set on `info!` level logs. Imo, this is also useful to have on all log-levels, including debug & trace
- `info_span` -> `trace_span`
> style(bridge): use trace_span for subnetwork instrument

- portal-bridge/README.md
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/main.rs
- portal-bridge/src/types/mode.rs
Using a provider is unreliable for testing using kurtosis
Solution? Use era1 files as they remove the provider failure point out of the equation
Adding a optional specifier for epoch.
> feat(era1 bridge): add gossip epoch mode for reliable testing

- portal-bridge/README.md
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/types/mode.rs
Gossiping an entire epoch takes quite a while. In kurtosis, it's useful to have the ability to gossip a small range of blocks. But we also want the ability to do this using era1 files as the provider, since they're more reliable.
- added the ability to gossip a range of blocks, as long as they're all within the same epoch. 
- added some debug logs to help understand what's being gossiped on a more granular level
> feat(bridge): add support to gossip block range from era1 files

- trin-beacon/src/storage.rs
- trin-history/src/storage.rs
- trin-storage/src/utils.rs
The main performance bottleneck in `prune_db()` was calling `get_total_storage_usage_in_bytes_from_network()` twice per iteration of the loop in `prune_db()` (once in `does_eviction_cause_under_capacity()` and once in `capacity_reached()`). Which was taking 40-50 seconds in total (2 x 20-25s). We should only be calling `get_total_storage_usage_in_bytes_from_network()` at the initialization of `HistoryStorage` and maintaining the count from their in memory.
This 40-50 second result was taken from one of our testnet nodes with a ~8GB sqlite database doing the inital prune_db() at startup initalization.
We only insert data or evict data in 2 spots in the code. So we can just keep a count of how much storage we use in memory and increment it or decrement it from there. We will only call …
> perf(history storage): decrease `prune_db()` loop iteration time by 40-50s on 8gb database

- trin-storage/src/sql.rs
Some of our queries were very slow because our db indices weren't setup correctly.
For example, the `TOTAL_DATA_SIZE_QUERY_DB` query took 20-25 seconds on 4GB database.
I added `network` column to the indices. Based on Kolby's measurements on the same db, we noticed following improvements:
| query | before (sec) | after (sec) |
|---|---|---|
| TOTAL_DATA_SIZE_QUERY_DB | 23.087 | 0.008 |
| XOR_FIND_FARTHEST_QUERY_NETWORK | 6.154 | 0.017 |
> fix: add network column to indices

- trin-state/src/jsonrpc.rs
A lot of json_rpc methods weren't implemented for the state network.
Implemented missing methods.
Most of them were implemented in a similar/same way as the history network.
NOTE: Currently, none of these methods would work because storage for the state network is not implemented. However, I do have some version of the storage implemented in the local branch and methods that I tested work fine.
> feat(state): implement jsonrpc for the state network

- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- trin-beacon/src/validation.rs
- trin-history/src/validation.rs
- trin-state/src/network.rs
- trin-state/src/validation.rs
- trin-validation/src/validator.rs
Implementation of `Validator` and `OverlayService` weren't flexible enough for the state network.
For the state network, content-value that is sent via `Offer/Accept` and `Find/Found Content` is not the same, and doesn't have the same validation properties. The `Offer/Accept` should always be provable that is part of a canonical chain, while that's not the case for the content from `Find/Found Content` (we can prove that content corresponds to the content-key).
Another issue is that Recursive Gossip that is part of the state network was not possible.
Created `ValidationResult` object that is returned by the validator that contains all important information. Overlay Service now knows if content is canonical and it's safe for storing locally, and if there is additional content to be …
> feat: content valid for storing and recursive gossip

- trin-storage/src/sql.rs
Non optimal sql indexes which were made in the last PR.
With this fix we are getting 10x faster find_farthest_content_id and up to 20-40x more database calls per minute
> refactor(perf): fix indexes with 10x increase in performance for find_farthest_content_id

- ethportal-api/src/types/distance.rs
- trin-beacon/src/storage.rs
- trin-history/src/storage.rs
- trin-storage/src/lib.rs
- trin-storage/src/sql.rs
- trin-storage/src/utils.rs
Most of the improvements were found/discovered by milos and discussed here https://github.com/ethereum/trin/issues/1157
This was caused because of `XOR_FIND_FARTHEST_QUERY_NETWORK`
- we were calculating distance on every value in the database
- We are doing `hex_encode(value)` which is making us store double the values
- `hex_encode`/`hex_decode` also makes inserts/reads slower as well
I implemented 2 new tables `content_data_history` and `content_data_beacon` which now uses blobs instead of text
The biggest improvement though in terms of eff is `XOR_FIND_FARTHEST_QUERY_NETWORK` now we precalculate the distance values
> fix(storage): uses milos find of blobs + proposal 1 for history/beacon

- portalnet/src/overlay_service.rs
Partially accepting `Offer` request doesn't work.
The `process_accept_utp_payload` function expects to receive keys and values that were accepted, while we send all requested keys (even the ones that are not accepted).
I noticed this while implementing the state network, as this logic is used during Recursive gossip.
Propagated correct keys.
**NOTE: Testing**
- I tried for at least 8 hours to make a test for this but I failed. I'm open for suggestions on how to do it.
- I was mostly trying to make a test inside `overlay_service.rs`
-  I still have the branch and I can push it to my github if someone wants to see and try to make it work (I think I got close)
- I thought about doing with via `ethportal-peertest`, but none of the public facing apis exposes this functionality.
I verified that …
> fix: accepting offer with multiple keys

- portal-bridge/README.md
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/types/mode.rs
We know we have some issues with our bridge when it's run as a long-running service. When our "latest" audit was switched to Infura, it still witnessed some stability issues. However, these were always resolved by rebooting the bridge, since the Infura provider is reliable. But debugging long-running processes is difficult. 
This solution is a bit of a hack, but effectively it turns our "backfill" bridges into short-term (aka the time it takes to gossip a single epoch) processes rather than long-running processes. With this new mode, after gossiping a **single** randomly selected epoch, the bridge process will naturally terminate. In which case the `docker_container` process used in our Ansible deployment scripts, will automatically restart the container, due to the `restart_policy: …
> feat(bridge): add single random epoch mode to fourfours bridge

- Cargo.lock
- portal-bridge/Cargo.toml
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/main.rs
`era1` files are available via a new html-based index that can actually record all of the files, unlike the old xml index. 
- Updated the bridge code to read & process the new html-based index for era1 files
> fix(bridge): update era1 file source

- ethportal-api/src/types/portal.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
grapababa found that we were returning a u32 for pong seq reponse instead of a u64 https://eips.ethereum.org/EIPS/eip-778#:~:text=seq%3A%20The%20sequence%20number%2C%20a%2064%2Dbit%20unsigned%20integer as seen in the ENR spec it should be a u64
by returning a u64 instead of a u32
> fix: Pong enr_seq is supposed to be u64 not u32

- Cargo.lock
- Cargo.toml
- portalnet/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- utp-testing/Cargo.toml
wee are using an old version
by updating it
> chore: update utp to v0.1.0-alpha.11

- Cargo.lock
- portalnet/Cargo.toml
- portalnet/src/overlay_service.rs
It's possible to propagate the same content id multiple times within the same offer.
The #1176 added functionality to propagate additional content key/value, which made this more likely to occur (originally it was possible only if offer contained duplicates).
Now we are keeping only unique content ids.
NOTE: Similar to other functionality that involves offer with multiple entries, I don't know how to test this.
I tested it using state network and recursive gossip on my local machine (that's how I noticed issue to begin with).
Once, #1187 is in, I will create peer-to-peer tests that will test this and other similar functionality.
> fix: remove duplicate ids when propagating

- Cargo.lock
- trin-beacon/Cargo.toml
- trin-beacon/src/validation.rs
- trin-history/Cargo.toml
- trin-history/src/validation.rs
- trin-state/Cargo.toml
- trin-state/src/validation/validator.rs
- trin-validation/Cargo.toml
- trin-validation/src/validator.rs
We were using `async_trait` in our validators, which I was told should no longer be needed.
Removed the `async_trait` from validators.
I didn't test this in any way, I'm counting on our tests catching if there is any issue.
> refactor: remove async_trait from validators

- Cargo.lock
- Cargo.toml
- ethportal-api/src/types/consensus/beacon_state.rs
- portal-bridge/src/types/e2s.rs
- portal-bridge/src/types/era.rs
- portal-bridge/src/types/era1.rs
- src/bin/historical_batch.rs
Adding the script used to extract `HistoricalBatch` from [Nimbus era ](https://mainnet.era.nimbus.team/) files.
> feat(bin): add script to extract `HistoricalBatch` from nimbus Era files

- portalnet/src/overlay_service.rs
This reverts commit 3094fbb2a9b937eb1e5e57e543910610da080570.
Tons of uTP requests are "failing" reporting trying to connect to connection id 0 
This bug was introduced in https://github.com/ethereum/trin/pull/1189
The bug basically was there wouldn't be a semaphore avaliable but the bitlist would already be filled with data
by reverting https://github.com/ethereum/trin/pull/1189
As stated https://github.com/ethereum/trin/pull/1189#issuecomment-1971881083 `try_acquire_owned` is none blocking it instantly fails if a semaphore isn't avaliable which is the intended behavior.
We should check if a semaphore is avaliable first because the call `try_acquire_owned` is instant and free, we don't have to wait because if there are no semaphores avaliable it instantly returns with …
> Revert "refactor: wait for semaphore permit only if accepting content"

- trin-storage/src/utils.rs
- trin-storage/src/versioned/id_indexed_v1/config.rs
- trin-storage/src/versioned/id_indexed_v1/mod.rs
- trin-storage/src/versioned/id_indexed_v1/sql.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-storage/src/versioned/mod.rs
- trin-storage/src/versioned/sql.rs
- trin-storage/src/versioned/usage_stats.rs
As described in #1157, we could use sql triggers to track count and size of content that is stored, instead of doing:
- it manually (what history does) 
- making expensive queries (what history used to do and what `id_indexed_v1` does now)
Created `usage_stats` table and provided utility functions for interaction.
We already had `struct UsageStats` as part of the `id_indexed_v1` store, that I repurposed. As a consequence I had to refactor some of it's logic (mostly move it inside `IdIndexedV1StoreConfig`).
I created dedicated tests for it, but it's indirectly tested by tests in `id_indexed_v1`.
> feat: create usage_stats table and triggers to update it

- ethportal-peertest/src/scenarios/find.rs
- portalnet/src/overlay_service.rs
- rpc/src/beacon_rpc.rs
- rpc/src/errors.rs
- rpc/src/fetch.rs
[Spec proposal](https://github.com/ethereum/portal-network-specs/pull/276) proposes different error code than trin currently uses
> fix: updates ContentNotFound error code to match spec

- portal-bridge/src/cli.rs
- portal-bridge/src/client_handles.rs
`portal-bridge` was using `url::Url` for the metrics url, when core `trin` uses `SocketAddr`. 
To avoid some extra string parsing, I just updated the bridge's metrics url to be a `SocketAddr` as well
> fix(bridge): fix bridge cli args to be compatible with client metrics

- Cargo.lock
- portalnet/src/config.rs
- portalnet/src/overlay.rs
- portalnet/src/overlay_service.rs
- portalnet/src/utp_controller.rs
- portalnet/tests/overlay.rs
- src/lib.rs
- trin-beacon/src/lib.rs
- trin-beacon/src/network.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/Cargo.toml
- trin-state/src/lib.rs
- trin-state/src/network.rs
Initial refactor of `OverlayService`. Fairly straightforward extracting of all utp stream handling logic into the `UtpController`.
Coming up in a following pr will be the "offer" queue to eliminate concurrent utp streams for the same content key.
- extracted logic from `OverlayService` -> `UtpController`
- tested locally via kurtosis & resolved a bug in metrics reporting
> refactor(portalnet): extract basic utp stream handling into utp controller

- light-client/src/consensus/rpc/portal_rpc.rs
- portalnet/src/find/query_info.rs
- portalnet/src/gossip.rs
- portalnet/src/lib.rs
- portalnet/src/overlay/command.rs
- portalnet/src/overlay/config.rs
- portalnet/src/overlay/errors.rs
- portalnet/src/overlay/mod.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/request.rs
- portalnet/src/overlay/service.rs
- portalnet/tests/overlay.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/network.rs
- trin-beacon/src/sync.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/network.rs
- trin-state/src/jsonrpc.rs
- trin-state/src/network.rs
`overlay_service.rs` is too big.
Split out the components inside `overlay_service.rs` into their own separate modules.
> refactor(portalnet): split out overlay_service into submodules

- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/stats.rs
`GossipReport` logs on the bridge are far too excessive, since it simply calls `Debug` on the `BlockStats` object rather than using the `report()` method. eg..
```
Done serving block: 2647790 - Mutex { data: HistoryBlockStats { block_number: 2647790, header_with_proof: Some(ContentStats { offered: {Enr { id: Some("v4"), seq: 9, NodeId: 0xa0cd2d177067f663bd06b351219591ec0bab274f020e0964035a3006d47c298a, signature: "ea9ee579b2bf56ffc3939b02c7846d5982f57c5447d51faf8359d6f28723c39a59813cf1e011626ddbd2840292cb0daddcc160f29b5ab1384cb95661c3d50339", IpV4 UDP Socket: Some(159.223.210.116:9009), IpV6 UDP Socket: None, IpV4 TCP Socket: None, IpV6 TCP Socket: None, Other Pairs: [("c", "967420302e312e312d616c7068612e312d343736636237"), ("secp256k1", …
```
> style: reduce bridge debug logs

- portalnet/src/overlay/service.rs
Use `UtpProcessing` object in `process_received_content` flow.
> refactor(portalnet): expand utp_processing

- portal-bridge/src/cli.rs
- portal-bridge/src/main.rs
Our bridge is currently stuck inbetween two paradigms. 
- a single bridge gossiping via a single node
- a single bridge gossiping via more than one nodes
Personally, I'd like to only support the first use case. Especially, if you want to run two bridges in different modes (as I do). But, that's a different discussion. This pr basically allows for a user to run two bridges from the same machine, which isn't possible unless you can configure the discovery port.
- added ability to customize discovery port & http port via cli
- custom http port is not necessarily a feature I need, but it's so closely related to the discovery port, that I figured it was better to update the functionality for both ports to maintain consistency
> feat(bridge): launch bridge with custom discovery and http ports

- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/lib.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/lib.rs
- utp-testing/src/lib.rs
we had a non needed mutex
removed it
> chore: remove non-needed mutex from rpc handler

- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/lib.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/lib.rs
As said here https://github.com/ethereum/trin/pull/1215#discussion_r1527267279 we also don't need the RwLock held on the rpc handler for the beacon and history rpc handler's
By removing the rwlock
> refactor: remove RwLock from History/Beacon rpc handler

- Cargo.lock
- trin-history/src/network.rs
- trin-history/src/storage.rs
- trin-storage/Cargo.toml
- trin-storage/src/sql.rs
- trin-storage/src/utils.rs
- trin-storage/src/versioned/legacy_history/mod.rs
- trin-storage/src/versioned/legacy_history/sql.rs
- trin-storage/src/versioned/legacy_history/store.rs
- trin-storage/src/versioned/mod.rs
- trin-storage/src/versioned/utils.rs
Current implementation of history storage is within `trin-history` crate.
In order to migrate it to the new storage (`id_indexed_v1`), we first have to move current logic into a separate module.
Created `legacy_history` module and moved all related logic into it. This was done with very little code changes (mostly regarding initialization).
Plan for the followup PR is to write a code for migration from `legacy_history` to `id_indexed_v1` (which should be just table rename). After that PR we should be able to remove `legacy_history` module, and cleanup code a bit.
> refactor: extract history storage into separate file

- trin-state/src/jsonrpc.rs
- trin-state/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/sql.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
The `id_indexed_v1` store didn't support pagination.
This is a requirement before transitioning history storage to this store as well.
Implemented pagination and using it from state network.
I added tests and tested JSON api locally.
> feat: add pagination to the id_indexed_v1 store

- trin-state/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/config.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
- trin-storage/src/versioned/id_indexed_v1/mod.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-storage/src/versioned/sql.rs
- trin-storage/src/versioned/utils.rs
We need custom logic in order to migrate History Storage to `id_indexed_v1` Store.
Added custom logic for detecting if legacy history storage is used and migration to the new store.
> feature: add legacy_history to id_indexed_v1 store migration

- ethportal-api/src/types/execution/block_body.rs
- ethportal-api/src/types/execution/transaction.rs
- portal-bridge/src/types/full_header.rs
Bug in blob transaction ssz decoding was preventing glados from hitting 100% on block bodies.
Fixed broken decoding and added test case.
> bugfix: broken blob transaction ssz decoding

- ethportal-api/src/types/execution/block_body.rs
- ethportal-api/src/types/execution/receipts.rs
- ethportal-api/src/types/execution/transaction.rs
- portal-bridge/src/types/era1.rs
This PR supercedes https://github.com/ethereum/trin/pull/1225
```nim
2024-03-13T23:15:24.103417Z  INFO portal_bridge::bridge::era1: Launching era1 bridge: FourFours(RandomSingle)
2024-03-13T23:15:24.104041Z  INFO portal_bridge::bridge::era1: Processing era1 file at path: "https://era1.ethportal.net/mainnet-01797-34123297.era1"
2024-03-13T23:15:26.341131Z ERROR portalnet::overlay::protocol: Error bonding with bootnode alias=ultralight-2 protocol=History error=The request timed out
2024-03-13T23:15:29.343137Z ERROR portalnet::overlay::protocol: Error bonding with bootnode alias=ultralight-3 protocol=History error=The request timed out
2024-03-13T23:15:32.344509Z ERROR portalnet::overlay::protocol: Error bonding with bootnode alias=ultralight-4 protocol=History error=The request timed out …
```
> fix: era1 typed-(transaction/receipt) encode/decode

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-api/src/types/consensus/serde.rs
- ethportal-api/src/types/execution/receipts.rs
- ethportal-peertest/Cargo.toml
- light-client/Cargo.toml
- portal-bridge/Cargo.toml
- portalnet/Cargo.toml
- trin-beacon/Cargo.toml
- trin-history/Cargo.toml
- trin-history/src/validation.rs
- trin-validation/Cargo.toml
- trin-validation/src/accumulator.rs
We had dependency on private fork of `ethereum_ssz` and `ethereum_serde_utils`.
1. Adding `ssz` feature to `alloy-primitives` eliminated need for custom version of `ethereum_ssz`.
2. The custom function `u256_from_dec_str` from `ethereum_serde_utils` that Kolby added wasn't really needed because `alloy-primitives` has `U256::from_str_radix(...)`.
3. In order for everything to work, I also needed to fork @KolbyML 's `ssz_types` repo and make it depend on public `ethereum_ssz` and `ethereum_serde_utils` as well (commit [link](https://github.com/morph-dev/kolby_ssz_types/commit/e6129bf860cea549a510281222a13154f3370ac1)).
- Going forward, we can merge my changes into his repo, as he is more likely to keep maintaining it long term.
This leaves us with only 3 non-public repos:
- …
> chore: depend on public ethereum_ssz and ethereum_serde_utils crates

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/types/cli.rs
- portalnet/src/events.rs
- trin-utils/Cargo.toml
- trin-utils/build.rs
- trin-utils/src/lib.rs
- trin-utils/src/version.rs
This PR resolves one issue and adds a small improvement.
The improvement is small; it replaces the ref Option with Option ref. It might seem unreasonable, but from the API standpoint, the ref option leaks implementation details; on the other hand, option ref just asks for optional data.
Resolves: [#9](https://github.com/ethereum/trin/issues/995)
The shadow_rs collects data at compile time; I use this data to generate a `VERSION` const that is embedded in the clap library.
Everything is working on compile time.
```
yurtur@pc:~/projects/trin$ cargo run -- --version | tail -1 | sed "s/ /\//g"
Finished dev [unoptimized + debuginfo] target(s) in 0.44s
Running `target/debug/trin --version`
trin/0.2.2-e66c5c2c/linux-x86_64/rustc1.77.0
```
> Display correct Trin version in CLI

- trin-storage/src/versioned/sql.rs
- trin-storage/src/versioned/usage_stats.rs
While looking into issue regarding #1235, I discovered the bug regarding usage stats "on update" trigger.
There was a test that was supposed to test this functionality but it was passing by chance.
Updated the test (verified that it fails), fixed the code and verified that test passes.
The more correct approach would be to drop the trigger if it exists, and create new one with different name.
I think that this is overkill as this code is not yet used in public. The only exception are 5 machines that @KolbyML 's used while testing the #1235 (this [comment](https://github.com/ethereum/trin/pull/1235#issuecomment-2040483220) for context), which can he can fix by manually executing following query:
```sql
DROP TRIGGER ii1_history_on_update_update_usage_stats_trigger;
```
This PR should be …
> fix: use correct column name in "on update" usage stats trigger

- portal-bridge/README.md
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/types/mode.rs
- portalnet/src/overlay/service.rs
- src/bin/historical_batch.rs
launches era1 bridge mode with random single, but only for epochs greater than the provided floor
added cli flag
> feat(bridge): cli flag for random era1 file with floor

- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/types/era1.rs
Era1 files can get pretty large, and storing the entire deserialized object in memory can overwhelm our bridge nodes.
Iter over block tuples rather than store entire `Era1` object in memory
> fix: stream era1 block tuples

- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/constants.rs
- portal-bridge/src/main.rs
we have headroom on our era1 bridges which we can use to gossip more blocks simultaneously
by adding a cli option to configure the constant
> feat(bridge): make gossip limit a cli option

- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
In our `history` gossip, we have a 10 second sleep after gossiping the header to allow for network saturation, since this header is necessary to validate the following receipts & body values. We are missing this sleep in `era1` gossip. Now, the effectiveness of this sleep & it's value are up for debate, but it seems to me like it's worthwhile to match this behavior inside `era1` gossip, at least until it's proven unnecessary.
added sleep to `era1` gossip
> fix: add sleep to allow for header saturation in era1 gossip

- trin-history/src/jsonrpc.rs
- trin-history/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
History storage is still using the legacy store.
This PR migrates it to the new storage scheme.
Remaining work afterwards will be to remove legacy store and cleanup code where applicable.
> feat: migrate history to id_indexed_v1 store

- portal-bridge/src/bridge/history.rs
The latest bridge was waiting for 2 new blocks before it started gossiping them. If you notice in the picture groups of 2 form due to this bug
I choose to just use a loop because it was easier for me to read and understand, a Range was a little overkill so this simplification helped me fix the issue.
I tested it by copy pasting it into a test and replacing any function call with logs, then fixing it till I got the expected log output I was looking for.
It no longer has a delay in gossiping latest blocks.
I also tested in interops of 2,3 new blocks per loop {} and it is working as expected
> fix: latest bridge waiting for 2 new blocks before gossiping

- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- trin-metrics/src/bridge.rs
we don't have enough bridge metrics
what block are we even on?
by adding a current_bridge metric for the history bridge
> feat(bridge): add metric for current block number

- portal-bridge/src/api/execution.rs
Logs aren't descriptive
On logs so we can see what is happening
> chore: add more descriptive error for get_trusted_receipts()

- trin-metrics/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
The `IdIndexedV1Store` store was checking for pruning only once it estimated the it reached full capacity.
In practice, this could lead to using way more storage than desired.
I added `PRUNING_CHECKING_FREQUENCY` that forces us to check for pruning more frequently.
Checking for pruning is no longer as expensive as it was originally (because we are now using triggers to update usage stats), so this shouldn't have big performance impact.
I also removed one test that was hard to test with new logic. It's worth pointing out that most parts of the tests were already covered by other tests.
> fix: check for pruning more frequently

- trin-history/src/storage.rs
Pruning 5-10% of the database can take too much time that, which also blocks other tasks.
Revert code to use `LegacyHistoryStore` again (partial revert of #1235 ).
> fix: revert history storage to use LegacyHistoryStore

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/types/cli.rs
- ethportal-api/src/types/portal_wire.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/basic.rs
- ethportal-peertest/src/scenarios/gossip.rs
- portal-bridge/src/client_handles.rs
- portalnet/src/discovery.rs
- portalnet/src/events.rs
- portalnet/src/overlay/service.rs
- portalnet/src/utils/db.rs
- portalnet/tests/overlay.rs
- rpc/src/lib.rs
- rpc/src/rpc_server.rs
- src/lib.rs
- tests/self_peertest.rs
- trin-history/src/storage.rs
- utp-testing/src/lib.rs
We aren't able to configure protocol_id in the case we want to support different networks like a testnet
This is basically the same thing we already did except we use a bidirectional map instead of trait conversions acting as a bidirectional map.
For storing mainnet/future network data we will use a folder structure I seen L1 clients use ``trin/mainnet/...`` ``trin/futurenetworkname/...``
Now we can easily configure future networks
> feat: add support for configuring network protocol_id's

- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/Cargo.toml
- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/lib.rs
- portal-bridge/src/main.rs
- src/bin/test_providers.rs
Added the ability to set a fallback provider, in case a request to the primary provider fails.
- Removed `Retry` middleware
- Added fallback & primary providers for both el & cl bridge apis
- Removed ability to set provider urls via env variable, since these can now just be set via cli flag
> feat(bridge): add fallback providers

- trin-storage/src/versioned/id_indexed_v1/mod.rs
- trin-storage/src/versioned/legacy_history/migration.rs
- trin-storage/src/versioned/legacy_history/mod.rs
- trin-storage/src/versioned/legacy_history/store.rs
- trin-storage/src/versioned/sql.rs
It is currently not possible to migrate from `id_indexed_v1` back to `legacy_history` store.
This makes development and testing the migration hard.
Implemented the migration.
One can now easily switch to any desired implementation.
> feat: implement `id_indexed_v1` -> `legacy_history` store migration

- .github/workflows/release.yml
We don't update the `Summary` section in the release template when we release a new version.
Removes the `Summary` section from the release template for now.
> chore: update github release template

- ethportal-api/src/types/consensus/beacon_state.rs
- ethportal-api/src/types/consensus/historical_summaries.rs
- ethportal-api/src/types/consensus/mod.rs
- ethportal-api/src/types/content_value/beacon.rs
- ethportal-api/src/types/content_value/history.rs
- ethportal-api/src/types/execution/header.rs
- ethportal-api/src/types/execution/header_with_proof.rs
- ethportal-api/src/types/execution/mod.rs
- portal-bridge/src/api/execution.rs
- tests/rpc_server.rs
- trin-history/src/validation.rs
- trin-validation/src/accumulator.rs
- trin-validation/src/oracle.rs
We need types to contain post-merge execution header proofs
- move all header proofs to a new `header_proofs.rs` file inside the `execution` folder.
- add and update post-merge header proof types
- rename the old `header_proofs.rs` file in the consensus folder to `historical_summaries.rs` because now It contains only those types.
Post-merge proof types are based  on the following portal specs PRs: 
- https://github.com/ethereum/portal-network-specs/pull/287
- https://github.com/ethereum/portal-network-specs/pull/291
> feat(ethportal-api): add and refactor post-merge header proofs

- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/constants.rs
When we removed the `Retry` middleware, we lost a built-in sleep mechanism. Some of the current bridge errors seems to be a result of "DOS protection". Re-introducing a manual sleep "should" help prevent this error from happening.
> fix(bridge): add sleep before request retry to fallback

- ethportal-api/src/types/content_value/history.rs
- ethportal-api/src/types/execution/header_with_proof.rs
- ethportal-api/src/types/history.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- trin-validation/src/accumulator.rs
The `BlockHeaderProof` enum must contain proofs for post-merge headers.
Add post-merge proof types to block header proof.
The logic for verification of the post-merge proofs will be added later because additional refactoring of the validation modules will be introduced in the following PRs.
We will add tests for SSZ encode/decode for the post-merge header with proof when the test vectors are available.
> feat: add post-merge proof variants to block header with proof type

- ethportal-api/src/types/cli.rs
- ethportal-api/src/types/execution/header_with_proof.rs
- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/bridge/utils.rs
- portal-bridge/src/main.rs
- src/bin/test_providers.rs
- src/lib.rs
- trin-history/src/validation.rs
- trin-state/src/validation/validator.rs
- trin-validation/src/accumulator.rs
- trin-validation/src/constants.rs
- trin-validation/src/oracle.rs
We will introduce two more accumulators for verifying pre-capella and post-capella headers and using "master" for the pre-merge accumulator is confusing and doesn't make sense anymore.
- Rename `master accumulator ` to `pre-merge accumulator`.
- Rename `AccumulatorProof` to `PreMergeAccumulatorProof`.
> refactor: rename master accumulator and accumulator proof

- portal-bridge/src/cli.rs
This is a bit of a **nitpick**, but imo requiring these cli flags is unnecessary, and while running the bridge locally, it clutters up the command line. These seem like reasonable values for local testing, and ofc in production / edge cases you can still use the cli flag to specify a different value.
Added default values for two cli flags in the bridge
> refactor(bridge): add default value for cli flags

- Cargo.lock
- docker/Dockerfile.bridge
- ethportal-api/src/types/state_trie/account_state.rs
- portal-bridge/Cargo.toml
- portal-bridge/resources/genesis/mainnet.json
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/mod.rs
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/gossip.rs
- portal-bridge/src/main.rs
- portal-bridge/src/types/era1.rs
- portal-bridge/src/types/mod.rs
- portal-bridge/src/types/state/block_reward.rs
- portal-bridge/src/types/state/content.rs
- portal-bridge/src/types/state/execution.rs
- portal-bridge/src/types/state/mod.rs
We didn't have a bridge for gossiping state data
By implementing the state bridge for the first 46146 blocks. These blocks didn't include transactions so they don't require the EVM. Most of the work in the PR is from Milos's work https://github.com/morph-dev/young-ethereum
We will be using Era/era1 as a data source
Going forward my plan for my next PR's is
- add evm and be able to execute transactions up to the merge
- store state on disk instead of in memory
- execute transaction in BlockBodyMerge
- execute transaction in BlockBodyShanghai
- execute non-finalized history. This isn't a solved problem yet as we haven't even fully solved it for history yet. I know Piper/Milos will probably do some reach on this. This is probably safe to avoid till we get there.
There is also that Recursive …
> feat: implement state bridge for the first 46146 blocks

- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/README.md
- portal-bridge/src/bridge/beacon.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/client_handles.rs
- portal-bridge/src/gossip.rs
- portal-bridge/src/main.rs
- portal-bridge/src/stats.rs
The bridge was initially architected to support gossip via multiple clients at once. This introduced some edge cases and unwieldy code which resulted in a feature that's not actually used / nor properly supported & tested. 
Taking into account that this general structure is not suitable for state network gossip (since a bridge should only gossip content that it's "near" to), I think it's a good idea to go ahead and remove this feature. 
Furthermore, it's likely that we'll introduce an alternative approach to "covering the keyspace" with multiple clients. via #1228 
Removed support for `--node-count` argument
> refactor(bridge): remove multiple client functionality

- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/cli.rs
- src/bin/test_providers.rs
This is a bit of an experimental pr. The "latest" bridge issues we're experiencing only occur after a significant time of bridge operation. It's possible that there's an error with our request construction / response handling for long-running `Client` objects, handling many requests. Imo, it's worth trying out this change to see if constructing a `Client` object for each request at least resolves the issue, then we can see about changing this back / fixing the long-running `Client` object if we feel like it's worthwhile.
- replaced a single-use `Client` object for a per-request `Client` object
> fix(bridge): use client object per request in bridge

- portal-bridge/src/cli.rs
When I was working on the state bridge. An incorrect executable-path took a lot of my time, cause their was no error, but the bridge kept trying to gossip content anyways
throw an error if the executable path doesn't lead to a file. This is a naive solution which doesn't handle all cases, but it handles most which would save people time if they entered the incorrect path.
> feat(bridge): throw error if invalid executable path was provided

- ethportal-api/src/types/cli.rs
- src/lib.rs
- trin-history/src/validation.rs
- trin-validation/src/accumulator.rs
- trin-validation/src/lib.rs
- trin-validation/src/oracle.rs
There is no real use case for loading a pre-merge accumulator from a user-provided path, because we embed the accumulator in Trin binary.
Remove the `pre_merge_acc_path` argument from Trin CLI.
> refactor: disable loading pre-merge accumulator from custom path

- Cargo.lock
- ethportal-peertest/src/scenarios/bridge.rs
- portal-bridge/src/main.rs
- src/lib.rs
- trin-history/src/validation.rs
- trin-state/src/validation/validator.rs
- trin-validation/Cargo.toml
- trin-validation/src/header_validator.rs
- trin-validation/src/oracle.rs
No logic was implemented for validating post-merge/pre-Capella execution headers.
- Implement the chain of proofs validation using the historical roots accumulator.
- move the build of the pre-merge accumulator inside `HeaderValidator`.
> feat(trin-validation): add validation logic for post-merge/pre-Capella headers

- portal-bridge/README.md
- portal-bridge/src/api/execution.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/main.rs
- portal-bridge/src/types/mode.rs
Added a four fours mode that accepts a sample size & threshold, will iter through all the epochs until it finds an epoch that's insufficiently available on the network according to the provided levels. Then it will gossip this epoch. For each individual piece of content within the epoch, it will perform an RFC lookup and will only gossip that piece of content if the RFC lookup fails.
added "hunter" mode to 4444s bridge
> feat(bridge): add four fours hunter mode

- trin-metrics/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/config.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
- trin-storage/src/versioned/id_indexed_v1/sql.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-storage/src/versioned/legacy_history/migration.rs
- trin-storage/src/versioned/sql.rs
- trin-storage/src/versioned/usage_stats.rs
The pruning strategy of `IdIndexedV1Store` (deleting ~5% of db) was taking too long on large databases (example: 40sec on 10GB db).
After trying several approaches and measuring performance, I refactored the pruning logic:
1. Don't use triggers and update usage stats manually
- Made **delete** queries return `content_size` to save few sql queries
2. Because of 1. no need for estimating how many entries to insert before pruning
- This also allowed removing `pruning_threshold` from the config
4. Prune up to 5%, but no more than 100 items at the time
I run this version on one of Kolby's machines and metrics look ok to me.
- Use `IdIndexedV1Store` for history network
- Delete `LegacyHistoryStore`
- Delete triggers (might be useful in the future, but don't like to have unused code seating …
> refactor: update pruning strategy

- ethportal-api/src/types/consensus/beacon_state.rs
- ethportal-api/src/types/consensus/historical_summaries.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/bridge/history.rs
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/types/full_header.rs
- portal-bridge/src/types/mode.rs
- src/bin/test_providers.rs
- trin-validation/src/accumulator.rs
- trin-validation/src/constants.rs
- trin-validation/src/header_validator.rs
Validation logic for post-Capella headers was missing.
- add validation logic for post-Capella headers.
- add tests using the test vectors [here](https://github.com/ethereum/portal-spec-tests/pull/12#pullrequestreview-2044988449).
> feat(trin-validation): add validation logic for post-Capella headers

- portalnet/src/config.rs
The `data_radius` of `PortalnetConfig` is not used.
I removed the field
> chore: remove unused PortalnetConfig::data_radius field

- trin-storage/src/versioned/id_indexed_v1/config.rs
- trin-storage/src/versioned/id_indexed_v1/mod.rs
- trin-storage/src/versioned/id_indexed_v1/pruning_strategy.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-storage/src/versioned/usage_stats.rs
Current pruning logic for `IdIndexedV1Store` is to delete up to 5% of storage, but no more than 100 elements. However, even 100 elements is too slow on big databases (e.g. 35GB that are currently used). It can take up to a second and sometimes even longer. This wouldn't be such a big problem if this wouldn't block other read/writes.
The idea is to have dynamic number of items that we delete. The `PruningConfig` allows us to set parameters, for this dynamic strategy:
- what is the optimal pruning duration - default 100-300 milliseconds
- by how much to increase/decrease number of items to prune when pruning is faster/slower than optimal - default 20%
Also added logic for handling the zero storage capacity to prune the db (if non-empty) and set radius to zero.
[//]: # (Stay ahead of things, …
> feat: implement dynamic pruning strategy

- ethportal-api/src/types/portal_wire.rs
- trin-metrics/src/labels.rs
we were
by matching them to the fix I did in my spec PR https://github.com/ethereum/portal-network-specs/pull/258
> fix: testnet protocol ids to matched spec proposal

- Cargo.lock
- trin-beacon/Cargo.toml
- trin-beacon/src/storage.rs
We don't store `HistoricalSummariesWithProof` in db.
- store the latest "HistoricalSummariesWithProof" version in the beacon cache storage
- add tests for beacon storage
> feat(beacon-storage): store `HistoricalSummariesWithProof` content and add beacon storage tests

- Cargo.lock
- ethportal-api/Cargo.toml
- portal-bridge/Cargo.toml
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/types/state/content.rs
- portal-bridge/src/types/state/execution.rs
- portal-bridge/src/types/state/mod.rs
- portal-bridge/src/types/state/trie_walker.rs
- trin-state/Cargo.toml
fixes https://github.com/ethereum/trin/issues/1292
Calling get proof on all changed accounts missing changed intermediate trie nodes
recursive gossip doesn't work so we have to gossip proofs for every intermediate try node
This PR gossips every intermediate node (as from the summit we discussed recursive gossip doesn't work)
This PR also makes it so we don't miss a changed node, by utilizing a Trie Diff
By getting the Trie diff from eth-trie.rs
Then by walking the diff building back traces then iterating over all the intermediate trie keys and building proofs to gossip
> fix: gossip state from trie diff and gossip every intermediate node

- Cargo.lock
- ethportal-api/src/types/content_value/beacon.rs
- trin-beacon/Cargo.toml
- trin-beacon/README.md
- trin-beacon/src/lib.rs
- trin-beacon/src/storage.rs
- trin-beacon/src/test_utils.rs
- trin-beacon/src/validation.rs
We don't validate the beacon content type before storing and gossiping.
- Add validations for the beacon content types.
- Extract a `test_utils` module for common usage in tests.
> feat(beacon-network): add content validation

- book/src/developers/architecture/README.md
- book/src/developers/contributing/build_instructions/linux.md
- book/src/developers/contributing/git/code_review.md
- book/src/developers/contributing/git/pull_requests.md
- book/src/developers/contributing/git/submodules.md
- book/src/developers/contributing/releases/deployment.md
This PR addresses several typographical errors across various files in the project. The changes improve readability and maintain the professional standard of the documentation and code comments.
Justification
Typographical errors, while minor, can detract from the overall quality of the project. Correcting these errors ensures clarity and professionalism, making the project more accessible and understandable for current and future contributors.
Hope it helps.
> docs: Rectify typographical inaccuracies

- ethportal-api/src/types/content_value/state.rs
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/types/state/config.rs
- portal-bridge/src/types/state/content.rs
- portal-bridge/src/types/state/execution.rs
- portal-bridge/src/types/state/mod.rs
- portal-bridge/src/types/state/storage/evm_db.rs
- portal-bridge/src/types/state/trie_walker.rs
- portal-bridge/src/types/state/types/mod.rs
- portal-bridge/src/types/state/types/trie_proof.rs
- portal-bridge/src/types/state/utils.rs
- portal-bridge/tests/state.rs
We weren't gossiping contract bytecode and storage, Milos really wanted me to do this before working on being able to execute to the front of the chain. It isn't really that big of a deal, so I am getting this done quick
By adding code to gossip the contract bytecode
For storage because the storage root is updated multiple times per a block, we maintain a cache of updated storage keys per an account.
This implementation is meant to be simple and work, I am aware of optimizations, but those are yet to be seen as needed so we will wait till be run into walls and go from there.
> feat(state bridge): gossip contract bytecode and storage

- ethportal-api/src/types/query_trace.rs
Including query-time radius information in any query trace analysis requires a property within `ethportal-api`'s `query_trace::NodeInfo` struct so that a node's radius data can be optionally recorded.
Adds the `radius: Option<B256>` to the `ethportal_api::query_trace::NodeInfo` for recording the radius. It's an `Option` because radius of most nodes won't be known by trin at query time, most will be filled in after the fact by Glados before displaying the trace.
> feat(ethportal-api): adds within-radius boolean to NodeInfo within QueryTrace

- trin-metrics/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
The `StorageMetricsReporter` doesn't return elapsed duration when `stop_process_timer` is called, which can be useful in some situations.
This is a followup from #1295.
Make `stop_process_timer` return elapsed duration and use it to simplify the logic for updating pruning strategy.
> refactor: make `stop_process_timer` return duration

- ethportal-api/src/types/content_key/history.rs
- portalnet/src/find/query_pool.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/storage.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/storage.rs
- trin-state/src/storage.rs
- trin-storage/src/lib.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
Preliminary work for gossiping dropped content. Spoke with @morph-dev offline and decided this was a good step, since I will soon update `prune()` to return content keys. Rather than having 4 separate fns on `IdIndexedStoreV1` using custom generics, better to make the entire struct generic over `OverlayContentKey`. This also helps simplify the upcoming implementation of `prune()` returning dropped content.
> refactor: make storage generic over content key trait

- book/src/developers/contributing/releases/deployment.md
To successfully cut a new release, starting from a fresh virtual environment also requires to install `docker` via pip.
- Added missing step to docs
> fix: add missing step to release docs

- ethportal-api/src/beacon.rs
- ethportal-api/src/history.rs
- ethportal-api/src/state.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- ethportal-peertest/src/scenarios/state.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- rpc/src/beacon_rpc.rs
- rpc/src/history_rpc.rs
- rpc/src/state_rpc.rs
- trin-beacon/src/jsonrpc.rs
- trin-execution/src/storage/evm_db.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
- To debug #1345 we need a jsonrpc endpoint that allows gossiping multiple pieces of data simultaneously (aka exactly how it's specified in the wire protocol)
- our current jsonrpc api is not [spec](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/portal-network-specs/assembled-spec/jsonrpc/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) compliant
- spec defines: `portal_historyOffer(enr, content_key, content_value)`
- we have `portal_historyOffer(enr, content_key, Option<content_value>)`
- this is not a great way of handling our offer endpoint...
- doesn't allow offering multiple content keys simultaneously
- the `Option` is awkward and can be …
> refactor: offer rpc endpoints

- Cargo.lock
- portalnet/src/discovery.rs
- portalnet/src/overlay/service.rs
- portalnet/tests/overlay.rs
- src/lib.rs
- trin-execution/src/storage/evm_db.rs
- trin-state/src/lib.rs
- trin-validation/Cargo.toml
- trin-validation/src/oracle.rs
- utp-testing/Cargo.toml
- utp-testing/src/lib.rs
In short this bug was caused by us only checking for `Enr`'s from our `node_addr_cache` which only contains new temporary connections. The fix was to also check our `kbuckets` and pending query caches
^ So I did implement a solution for this which checks each active sub-network as a as a fallback method.
GetEnr() json-rpc checks the kbuckets of the sub-network, but it doesn't check
This is only available in the OverlayService, not Overlay, so if in the future we still find a issue we can add it to the json-rpc GetEnr, but for now I think the solution is good enough.
I wish we wouldn't need to query every active sub-network as a backup option, but without a much bigger code change I think this is the best solution.
`enr_cache` should help reduce any locks on discv5 kbuckets or doing …
> fix: unable to find ENR for NodeId killing network perf

- portalnet/src/overlay/service.rs
```nim
2024-07-31T04:32:12.149516Z ERROR trin_history::events: Error processing portal history request, responding with empty TALKRESP error=Error while building accept message: unable to find ENR for NodeId request.discv5.id=75d0ab97e1527ba1
```
Which is still popping up just a lot less, I think this is due to a few different edge cases
Also it is annoying because we use the same log in 2 different functions
- making the same logs more distinct
- remove redundant `find_enr()` call
- add a few more possible cases to `find_enr()`
> fix: a few edge cases for find_enr() + distinction of same logs

- ethportal-api/src/types/jsonrpc/endpoints.rs
- src/lib.rs
- unnecessary newline in startup logs
- https://github.com/ethereum/trin/pull/1347#discussion_r1695388667
> refactor: fix comments and redundant newline in logs

- trin-execution/metrics/compose.yaml
- trin-execution/metrics/grafana/dashboards/trin-execution-main.json
- trin-execution/metrics/grafana/datasource.yml
- trin-execution/metrics/prometheus/prometheus.yml
- trin-execution/src/metrics.rs
Milos said I should try to take what I can from my big PR so I will do that, I will need a week to split .era2 PR more, but I will pull out anything that can be reviewed which can't break my database code for now
There wasn't enough metrics to understand things like transaction progress times, storage etc
By updating
- the dashboard
- adding new metrics to be used
> feat: add more metrics to trin execution

- ethportal-api/src/types/execution/transaction.rs
- trin-execution/src/execution.rs
- `get_transaction_sender_address` was returning the wrong address for typed transaction
- we were also detecting non-chain-id tx's wrong
- detect if chain id is present based off v size
- generate correct rlp for sender recovery
> fix: sender_recovery getting wrong address for typed tx's

- ethportal-api/src/types/cli.rs
- ethportal-peertest/src/scenarios/gossip.rs
- portalnet/src/config.rs
- portalnet/src/gossip.rs
- portalnet/src/overlay/config.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- tests/self_peertest.rs
- trin-beacon/src/network.rs
- trin-beacon/src/storage.rs
- trin-history/src/network.rs
- trin-history/src/storage.rs
- trin-state/src/network.rs
- trin-state/src/storage.rs
- trin-storage/src/lib.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
- trin-storage/src/versioned/id_indexed_v1/sql.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
fixes #981 
- add content that's dropped from local storage to propagation content vector
- limit offer message in propagation to 64 content keys (according to spec)
> Gossip pruned

- ethportal-api/src/types/execution/header_with_proof.rs
- trin-validation/src/header_validator.rs
Fixes #1358
- update post-merge header proofs to match the latest changes in this [PR](https://github.com/ethereum/portal-spec-tests/pull/20#event-13604146766)
- enable temporarily ignored tests
> fix: update post-merge header proofs to match latest changes

- e2store/src/era.rs
- ethportal-api/src/types/consensus/beacon_block.rs
`e2store/era` was hardcoded to only decode bellatrix, when I need to be able to decode all forks since execution payload was added
by doing a if else decode pattern like we do for decoding transactions
> feat: allow e2store/era to decode all forks not just bellatrix

- ethportal-api/src/eth.rs
- rpc/src/builder.rs
- rpc/src/eth_rpc.rs
We were missing `eth_getBalance`, `eth_getCode` and `eth_getStorageAt` JSON rpc endpoints.
Defined missing endpoints (using `todo!()` as implementation, for future PR).
We will need other endpoints in the near future (`eth_call` and `eth_estimateGass`), but they require more complicated type (`Transaction`), so I left them for future work.
> feat: define state related eth_* rpc endpoints

- ethportal-api/src/beacon.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- light-client/src/client.rs
- light-client/src/node.rs
- rpc/src/beacon_rpc.rs
- trin-beacon/src/jsonrpc.rs
To be able to validate `HistoricalSummariesWithProof`, we want to access the latest finalized beacon state root from the light client module.
The current design in HeaderOracle [relies on JSON-RPC](https://github.com/ethereum/trin/blob/8e36266c8a43d70fe81eb57d933058ea5d2f9c99/trin-validation/src/oracle.rs#L27) requests for accessing the data from the overlay networks.
This endpoint is required for fixing #1323.
Here is a [PR](https://github.com/ethereum/portal-network-specs/pull/331) to add the endpoint to beacon json-rpc specs as it will be useful for hive testing.
- implement `portal_beaconFinalizedStateRoot` json-rpc endpoint.
This endpoint was tested locally with beacon synced node.
> feat(beacon-network): add json-rpc method to get the latest finalized state root

- ethportal-api/src/types/jsonrpc/endpoints.rs
- ethportal-api/src/types/jsonrpc/request.rs
- rpc/src/beacon_rpc.rs
- rpc/src/errors.rs
- rpc/src/fetch.rs
- rpc/src/history_rpc.rs
- rpc/src/state_rpc.rs
We proxy the JSON rpc requests to the corresponding network. This required some duplicated logic for each subnetwork (and it wasn't consistent).
Introduced new type using generics and managed to create one functions that can proxy requests to each subnetwork.
While this is an improvement, I'm not completely satisfied with the current state because I believe that we still have some unnecessary json serialization / deserializaion. But that will be left for some potential future improvements.
> refactor: simplify json-rpc proxy logic

- ethportal-api/src/types/state_trie/mod.rs
- ethportal-api/src/types/state_trie/nibbles.rs
- ethportal-api/src/types/state_trie/trie_traversal.rs
- trin-state/src/validation/error.rs
- trin-state/src/validation/trie.rs
- trin-state/src/validation/validator.rs
The state validation could be improved after recursive gossip removal.
fixes: #1360 
- Improved trie node traversal logic and extract it to `ethportal-api`
- it was previously designed only with validation in mind
- now we can use it for other use cases as well (something we will need in order to support `eth_*` JSON rpc)
- moved and added new tests
- Removed no longer needed types
- Extracted common logic into separate functions
Run hive tests locally (trin + fluffy clients) and all tests are passing.
> refactor: state validation and trie node traversal improvements

- e2store/src/era.rs
When I was testing reading beacon blocks from era files when I compared the result of era 600 and era 601 their execution numbers didn't line up by 1 block, when I fixed this they lined up and I could linearly scan blocks from era files
I tested this for a few other sequential era files and the issues remained the same
change the 4 to a 3
> fix(e2store): era missing a beacon block off by 1 error

- Cargo.lock
- trin-beacon/Cargo.toml
- trin-beacon/src/lib.rs
- trin-beacon/src/storage.rs
- trin-beacon/src/test_utils.rs
- trin-beacon/src/validation.rs
- trin-validation/src/oracle.rs
Fixes #1323 
- add a method to get the latest finalized state root in `HeaderOracle`.
- implement validation methods in `BeaconValidator`.
Note: I had to use some creativity to write the unit tests for this validation because it is impossible to mock the jsno-rpc calls to the beacon overlay at this point.
This is why I split the validation into two methods and tested them individually, instead of one integration test of the `validate_content` method.
> feat(beacon-network): validate `HistoricalSummariesWithProof` against finalized state root

- portalnet/src/discovery.rs
Manually decoding the utp client type for every log you're interested in is a bit of a pain, much easier to display the already decoded client type in the log.
Added decoded client type to `UtpEnr` debug logs.
> refactor: display decoded client type in utp logs

- Cargo.lock
- e2store/Cargo.toml
- e2store/README.md
- e2store/src/e2store/memory.rs
- e2store/src/e2store/mod.rs
- e2store/src/e2store/stream.rs
- e2store/src/e2store/types.rs
- e2store/src/era.rs
- e2store/src/era1.rs
- e2store/src/lib.rs
We only had a memory mode for e2store files, for bigger era file types it isn't always possible to load everything into memory at once
By adding a streaming mode where you can stream entries from disk as you need them.
This is needed for `.era2` files as it is unreasonable to load everything into memory at once
> feat: add stream mode for e2store files

- portalnet/src/discovery.rs
Temporary solution to validate the theory that eth2 nodes are overflowing the `node_addr_cache` on mainnet. Once the theory is validated/invalidated, this solution will be replaced with a more sustainable solution, since this solution will result in the exact same issue once the total number of portal nodes on the network exceeds current cache size.
- only cache enrs that have a `"c"` enr key - indicating that they are participating in the portal network
> fix: temporarily skip caching non-portal nodes in discovery

- ethportal-api/src/types/jsonrpc/json_rpc_mock.rs
- ethportal-api/src/types/jsonrpc/mod.rs
There is no easy way to mock our json-rpc request/responses which makes unit test of certain parts of the codebase very challenging.
Created json-rpc mock builder, that is very customization.
See example of the real PR use case [here](https://github.com/ethereum/trin/blob/625839ee127798cdc6b1ffaa14a86366c1732503/trin-state/src/validation/validator.rs#L224C1-L229C24)
That case can be simplified even further (since it only cares about one response) in the following way:
```rust
let history_jsonrpc_tx = MockJsonRpcBuilder::new_builder().or_else(content_info);
```
For more complex logic, one can do something like this:
```rust
let history_jsonrpc_tx = MockJsonRpcBuilder::new_builder()
// respond to RecursiveFindContent with one respond
.with_response( …
```
> feat: create json-rpc mock builder

- ethportal-api/src/types/bootnodes.rs
I was wondering why I was continuously having problems connecting to fluffy bootnodes, turns out their ip addresses were updated recently and we never updated our hardcoded values.
- updated hardcoded fluffy enrs to match https://github.com/ethereum/portal-network-specs/blob/master/bootnodes.md
> fix: update fluffy bootnode enrs

- trin-execution/src/trie_walker.rs
the reverse logic for path was a little overly complex
by making the logic less complex
> refactor: simplify trie_walker get_proof code

- book/src/developers/contributing/releases/deployment.md
The existing documentation didn't include instructions for deploying to testnet nodes.
Added instructions, and slightly fixed formatting.
> docs: update deployment docs

- book/src/developers/contributing/releases/deployment.md
- book/src/developers/contributing/rotation/index.md
Some information on the Flamingo manual seems to be outdated, most notably the "notes".
While I don't have access to the [notes](https://notes.ethereum.org/YAiNsmc8SSq05TwYdk-8Eg) and [checklist](https://notes.ethereum.org/?nav=overview&template=b35733cd-b374-4b79-bc57-f2bb58ee651e), Kolby told me that we weren't really using them for the last couple of months.
Remove the references to the notes. If people think they were useful, should we consider restarting doing them? Should we consider alternatives?
I'm not sure what items are on the **checklist** (no access), but maybe we can put them on the Flamingo page directly? Can anybody share it with me?
> chore: update flamingo rotation manual

- portalnet/src/gossip.rs
There is a deadlock happening, mostly likely during gossip logic. See: #1390 
Adding more debug statements to narrow down where the deadlock is happening.
I also noticed that `calculate_interested_enrs` function can be improved and simplified.
> feat: add debug logging to gossip logic

- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/basic.rs
- src/lib.rs
- tests/self_peertest.rs
- trin-beacon/src/storage.rs
- trin-history/src/storage.rs
- trin-storage/src/config.rs
- trin-storage/src/lib.rs
- trin-storage/src/test_utils.rs
- trin-storage/src/versioned/id_indexed_v1/config.rs
Currently, we only have one flag to setting storage capacity that applies to each subnetwork separately. See #1387 for more info.
As discussed in the meeting, we will use predefined weight per subnetwork (for the short/medium term).
I put following weights as a placeholder. Let me know if you have other suggestions:
- history: 1
- state: 99
- beacon: 0 (beacon doesn't use capacity in any meaningful way (in only reports it to the metrics). 
> feat: use weight for setting storage capacity per network

- Cargo.lock
- ethportal-api/src/types/cli.rs
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/scenarios/state.rs
- ethportal-peertest/src/utils.rs
- portal-bridge/src/client_handles.rs
- trin-state/src/validation/error.rs
- trin-state/src/validation/trie.rs
- trin-state/src/validation/validator.rs
We currently don't anchor state content to the chain. We did this in the past as history network (and fetching block header) wasn't reliable, but we should start doing it.
Related issue: #1305 
Fetch the block header from the network and validate the content based on the `state_root`.
> feat(state): validate state content by anchoring it to the state root

- e2store/README.md
- e2store/src/era1.rs
- e2store/src/era2.rs
- e2store/src/lib.rs
- e2store/src/types.rs
- e2store/src/utils.rs
e2store doesn't support the `.era2` state snapshot format which will be used for bootstrapping state bridges or anything I guess
```nim
// <network-name>-<block-number>-<short-state-root>.era2
//
// era2 := Version | CompressedHeader | account*
// account :=  CompressedAccount | CompressedStorage*
// -----
// Version                     = { type: 0x3265, data: nil }
// CompressedHeader            = { type: 0x03,   data: snappyFramed(rlp(header)) }
// CompressedAccount           = { type: 0x08,   data: snappyFramed(rlp(address_hash, rlp(nonce, balance, storage_root, code_hash), raw_bytecode, storage_entry_count) } 
// CompressedStorage           = { type: 0x09,   data: snappyFramed(rlp(Vec<StorageItem { storage_index_hash, value }>)) }
// -----
// CompressedStorage can have a max of 10k …
```
> Add .era2 types

- Cargo.lock
- ethportal-api/Cargo.toml
- portal-bridge/Cargo.toml
- portal-bridge/src/bridge/state.rs
- trin-execution/Cargo.toml
- trin-execution/src/content.rs
- trin-execution/src/storage/account_db.rs
- trin-execution/src/storage/evm_db.rs
- trin-execution/src/trie_walker.rs
- trin-state/Cargo.toml
Storage trie changes weren't being gossiped due to fetching the storage trie diff code being incorrect.
There was also another problem apparently early on in Ethereum Storage could be modified well "creating" a new contract without changing the contracts code
- if the contract is empty don't skip gossiping storage trie changes
- correctly fetch storage trie nodes from the database
> fix(state-bridge): storage trie changes weren't being gossiped

- ethportal-api/src/types/consensus/beacon_state.rs
- ethportal-api/src/types/consensus/body.rs
- ethportal-api/src/types/consensus/participation_flags.rs
- portal-bridge/src/api/consensus.rs
- portal-bridge/src/bridge/beacon.rs
- portal-bridge/src/lib.rs
- portal-bridge/src/stats.rs
Fixes #1365.
1. Add logic to generate and gossip `HistoricalSummariesWithProof`  to the beacon network.
2. Refactor how we spawn the tokio tasks to generate the beacon content in every slot. An issue was blocking the main loop if some of the tasks took longer to complete.
3. Add some improvements to the BeaconState's deserializations from JSON strings. This was required to successfully deserialize the JSON responses from the pandaops node. Test asset was added to match the pandaops format.
4. Update main and fallback consensus API endpoints (We are bypassing the load balancer on the main endpoint because there are some issues with it).
> feat(portal-bridge(beacon)): generate and gossip `HistoricalSummariesWithProof` content

- trin-execution/src/trie_walker.rs
- trin-execution/tests/content_generation.rs
The `TrieWalker` can't assume that all provided nodes are useful and it shouldn't check for it.
Ideally, TrieWalker should be able to make such assumption, but not with the current implementation. Currently we write to db after every transaction, and cache all contract storage writes. When the same contact storage is updated in different transactions within the same block, this results in cache containing nodes that are no longer valid.
This can be solved by keeping all state changes in memory and writing them at the end of the block (instead of after every transaction). This was already planned improvement: #1333 .
As we are working on the proper fix (#1337), this PR disables the check.
Also adding test that executes and creates content key/value pairs up to a given block (disabled by …
> fix: trie_walker shouldn't assume that all nodes are useful

- trin-beacon/src/storage.rs
- trin-storage/src/sql.rs
- trin-storage/src/utils.rs
Fixes #1322 
- create a new `historical_summaries` table in the database on startup. This table will hold only one record.
- add insert and lookup queries
- cleanup unused cache code
> feat(beacon): store `HistoricalSummariesWithProof` into db instead of cache

- docker/docker-compose.yml
People want to run trin in docker images, but doing it with raw docker is complex for someone new to Trin
By making a good starter docker compose file which people can expand easily with what they want
> chore: add trin docker compose file

- Cargo.lock
- ethportal-api/src/eth.rs
- ethportal-api/src/types/state_trie/trie_traversal.rs
- rpc/Cargo.toml
- rpc/src/errors.rs
- rpc/src/eth_rpc.rs
- rpc/src/fetch.rs
- trin-state/src/validation/trie.rs
The `eth_getBalance`, `eth_getCode` and `eth_getStorageAt` weren't implemented.
Implemented them by fetching data from history (block header) and state network (traversing tries).
I also tested it locally by running trin myself and getting data from block 51208 (I knew that block was gossiped already).
All these requests support passing block as one of:
- block number
- block hash
- tag (i.e. latest / finalized / safe / earliest / pending)
Currently we only support block hash, but in the future we want to support block number as well (e.g. when we have block index network).
I think in the future we can support tags as well, but I would say that's the lowest of priorities at the moment.
> feat: implement eth_getBalance, eth_getCode and eth_getStorageAt

- Cargo.toml
- ethportal-api/Cargo.toml
- trin-validation/Cargo.toml
the tests I am trying to run locally are all failing, because we removed the `ssz` feature from alloy-primitives in the PR updating Cargo to properly use workplace 
so I got thousands of error's stating can't derive ssz for B256, ... 5 billion other errors etc. I was running tests in `block_body.rs`
depends
by adding the feature back which was removed
> fix: add `ssz` feature back for alloy-primitives to fix test compiling

- Cargo.toml
The `ssz` feature of `alloy-primitives` crate should be enabled for entire workspace (not just for the `trin` crate)
Updated workspace dependency.
> fix: alloy-primitives workspace dependency should include ssz feature

- trin-beacon/src/storage.rs
- trin-storage/src/sql.rs
- trin-storage/src/utils.rs
This PR stores `LightClientBootstrap` beacon content in a separate table in the database. This is required because:
1. To fix #1405, we need a way to get the latest stored block root from the latest bootstrap in the DB. This is solved by storing the block root as a primary key for the new bootstrap table. (content-id is not needed for the beacon network because the node radius does not apply to this overlay network).
2. We want to purge all bootstraps older than 4 months. We can do this by adding a slot column in the bootstrap table and periodically purging all content where slot number < 4 months old.
- create a new `lc_bootstrap` db table
- update insert and lookup queries
- update total beacon content size query
> feat(beacon): store `LightClientBootstrap` in separate db table

- trin-execution/src/era/beacon.rs
decoding beacon blocks, to processed blocks fails
So bloom is just a 256 bit number, it isn't encoded in RLP.
For transactions I used the wrong decode function for this use case
I tried to write some tests
```nim
#[cfg(test)]
mod tests {
use crate::era::manager::EraManager;
use super::*;
use rstest::rstest;
use serde_json::Value;
#[tokio::test]
async fn hi() {
let mut era_manager = EraManager::new(19000000).await.unwrap();
let block = era_manager.get_next_block().await.unwrap();
}
#[rstest]
#[case("bellatrix/SignedBeaconBlock/ssz_random/case_0")]
#[case("bellatrix/SignedBeaconBlock/ssz_random/case_1")]
#[case("capella/SignedBeaconBlock/ssz_random/case_0")]
#[case("capella/SignedBeaconBlock/ssz_random/case_1")]
#[case("deneb/SignedBeaconBlock/ssz_random/case_0")] …
```
> fix: process_beacon_block() doesn't decode all types properly

- Cargo.lock
- Cargo.toml
I think this is the last fix for https://github.com/ethereum/trin/issues/1419 ?
I de-forked the latest version of eth-trie.rs we were using, then moved it to the Ethereum org
I then made a release, following the common pattern we used then made this PR
https://github.com/ethereum/eth-trie.rs here is the repo
> chore: update cargo.toml to depend on eth-trie.rs in ethereum org

- .circleci/config.yml
When we updated cargo dependencies
https://github.com/ethereum/trin/pull/1411
https://github.com/ethereum/trin/pull/1414
failures to compile individual crates and this wasn't caught by CI
creating a parallel ci test which checks all workspace crates
https://doc.rust-lang.org/cargo/commands/cargo-check.html here is a link to check, it basically just ensures `cargo build` works, without doing all the work so it is good for CI applications
> chore: add a parallel ci test to ensure all workspace crates compile

- e2store/src/era.rs
- `get_block_slot_indexes()` apparently it is the 0ed offset, from the start of the slot_index not 0
implemented `get_block_slot_indexes()` to work based 0ed offset from the start of slot_index
> fix: era `get_block_slot_indexes()` not working

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/types/state_trie/account_state.rs
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/main.rs
- trin-execution/metrics/grafana/dashboards/trin-execution-main.json
- trin-execution/metrics/prometheus/prometheus.yml
- trin-execution/src/dao_fork.rs
- trin-execution/src/era/manager.rs
- trin-execution/src/evm/block_executor.rs
- trin-execution/src/evm/blocking.rs
- trin-execution/src/evm/execution_context.rs
- trin-execution/src/evm/mod.rs
- trin-execution/src/execution.rs
- trin-execution/src/lib.rs
- trin-execution/src/main.rs
- trin-execution/src/storage/account.rs
- trin-execution/src/storage/error.rs
- trin-execution/src/storage/evm_db.rs
- trin-execution/src/storage/execution_position.rs
- trin-execution/src/storage/utils.rs
- trin-execution/src/trie_walker.rs
- trin-execution/tests/content_generation.rs
fixes https://github.com/ethereum/trin/issues/1333
Execution started slowing down around block 2.34 million, to resolve this issue I add ``revm::db:State`` which is a middleware between the database interface and EVM. It makes it so whole blocks can be processed in memory. Instead of as before where we would commit per every transaction. This saves a lot of reads to the database. ``revm::db::State`` also gives us reverts as well which is cool
We also lacked some metrics, this PR will add some not all proposed metrics to add like
- transaction performance
- block height
add the ability to execute multiple blocks in memory, this makes execution a lot faster because then you don't need to call storage as much which is slow
> feat(trin-execution): execute multiple blocks in memory + able to execute to merge

- portalnet/src/overlay/service.rs
- portalnet/tests/overlay.rs
Trying and failing to configure UPnP causes a 10second delay during each test that tries it.
Some tests were slow locally (and presumably in CI).
Disable upnp during the test.
Comparing [this CI run](https://app.circleci.com/pipelines/github/ethereum/trin/6197/workflows/3f396eb1-4719-441b-8604-ca34fc03e013/jobs/24288) against [a recent test run](https://app.circleci.com/pipelines/github/ethereum/trin/6183/workflows/922467e0-508a-41b9-8c6b-316322470b4c/jobs/24195) shows a test speedup of 2 minutes and 21 seconds -- 8:42 vs 6:21.
> perf: speed up tests by disabling UPnP

- ethportal-api/src/types/cli.rs
- portalnet/src/config.rs
- trin-beacon/src/network.rs
- trin-beacon/src/storage.rs
- trin-beacon/src/sync.rs
- trin-storage/src/sql.rs
Fixes #1405.
- add logic to check for a recent trusted block root if not provided via CLI
- update `trusted_block_root` argument to `B256`.
- fix `lookup_lc_bootstrap_block_root` method
> feat(beacon): load trusted block root from database if not provided via CLI

- portalnet/src/overlay/protocol.rs
I'm open to pushback on this.. but in my opinion the error logs when starting up a node are too noisy... `error!` messages should be reserved for critical errors. It should just be a `warn!` log if we can't connect to a given bootnode in a subnetwork. And only display the `error!` if you're node was unable to connect to any bootnodes, therefore meaning your node was completely unable to connect to the network.
- changed log
> refactor: reduce noisy error logs

- Cargo.lock
- Cargo.toml
we use an old version
updating it to the newer version
> chore: bump uTP version to 14

- ethportal-api/src/types/content_key/beacon.rs
- ethportal-api/src/types/content_key/history.rs
- ethportal-api/src/types/content_key/overlay.rs
- ethportal-api/src/types/content_key/state.rs
- ethportal-api/src/types/portal.rs
- ethportal-api/src/types/portal_wire.rs
- portalnet/src/find/query_info.rs
- portalnet/src/gossip.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/storage.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-validation/src/header_validator.rs
`Vec<u8>` was being used to represent Raw Content Key.
See #1404 for details
Replaced it with `alloy_primites::Bytes`
> refactor: change RawContentKey to alloy_primites::Bytes

- ethportal-api/src/beacon.rs
- ethportal-api/src/types/consensus/light_client/bootstrap.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- rpc/src/beacon_rpc.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/validation.rs
- trin-validation/src/oracle.rs
Fixes part 1 of #1406.
- Add JSON-RPC endpoint to get the recently finalized beacon block header
- Compare the `LightClientBootstrap` header with the recently finalized beacon block header before gossiping and storing the content.
> feat(beacon): improve `LightClientBootstrap` validation

- Cargo.lock
- Cargo.toml
- ethportal-api/src/eth.rs
- rpc/Cargo.toml
- rpc/src/errors.rs
- rpc/src/eth_rpc.rs
- rpc/src/evm_state.rs
- rpc/src/lib.rs
- trin-execution/Cargo.toml
- trin-execution/src/evm/async_db.rs
- trin-execution/src/evm/tx_env_modifier.rs
Trin doesn't support eth_call requests.
- Refactored the rpc/src/eth_rpc.rs
- `EvmBlockState` now takes care of fetching all state related content for a specific block
- Using async evm execution from `trin-execution` crate
I tested it locally, with one simple transaction (token balance), and it works.
- Add caching to the `EvmBlockState`
- this will speed up transaction execution as we wouldn't have to traverse entire trie for every piece of data
- Add support for fetching block_hash by block number
- Until this is implemented in history network (https://github.com/ethereum/portal-network-specs/pull/334), we can fetch all blocks going backwards until we find the block that we need
- low priority until lookup by block number is added
- Extract some common logic from …
> feat: add basic support for eth_call

- ethportal-peertest/src/utils.rs
- light-client/src/consensus/consensus_client.rs
- light-client/src/consensus/utils.rs
- portalnet/src/find/iterators/findcontent.rs
- portalnet/src/overlay/service.rs
While working on #1395, a number of cleanups accumulated. But there's enough going on in that PR that it's nice to separate out the stuff that can be. This is a mashup of those changes, with more info in each commit.
Most prominent, and the only change in functionality, is that when content arrives twice, we ignore the 2nd to arrive (instead of ignoring the first to arrive). We would like to give credit to the fastest peer to return the content.
Just ignore additional content to come in. This of course continues to mean that if the first content to come in is invalid, then the whole query fails. #1395 is the next step toward improving that behavior.
Everything else is just:
- more logging lines, or info in the lines
- making Node ID loggable
- skip an unnecessary clone of content (which …
> Credit first peer to return content

- rpc/src/evm_state.rs
This is built on top of #1442, which should be merged before this one.
The `EvmBlockState` would traverse entire state trie for every piece of state data that it needs. This really affects the performance of the contract storage trie look ups (as we would have to traverse account trie first, in order to find storage root). Even account trie lookups could benefit from not looking the same trie nodes over and over again.
Added cash for every state network key-value lookup. This isn't a problem because EvmBlockState is short lived (just while serving specific `eth_*` json rpc).
Potential improvement in the future is to create global cache, that can be reused across multiple requests. It would have to be limited either by time or count of entries.
We also keep track of …
> feat(state): add cache to EvmBlockState

- trin-execution/src/evm/block_executor.rs
- trin-execution/src/execution.rs
- trin-execution/src/storage/execution_position.rs
- trin-execution/src/subcommands/era2/import.rs
- trin-execution/src/trie_walker.rs
- trin-execution/src/types/block_to_trace.rs
TrinExecution has quite of bit responsibility, which I feel it shouldn't have. It also has some functionality that is no longer used.
- "should commit early" is suited much better in BlockExecutor 
- proof generation is no longer used (removed)
- transaction tracing: I feel that this belongs in TrinExecution more than it does in BlockExecution
- BlockToTrace now creates folders and writer, if tracing is enabled
- BlockExecution accepts function that creates optional tracer
> refactor: simplify TrinExecution

- trin-execution/src/execution.rs
- trin-execution/src/main.rs
Using Ctrl+C to stop trin_execution can take a lot of time, partially due to committing to db (which can't be avoided), and partially because execution doesn't stop until next checkpoint (which can take another 30 min).
Refactor how TrinExecution executes blocks (built on top of #1450).
Instead of executing until the first commit (which can come early), it will now execute all the way to the provided block but it accepts `stop_signal` receiver. When stop signal is received, it will commit and return.
Note: Tested it locally (around block 6'000'000).
We can speed up the shutdown by abandoning changes that are in memory (by not committing anything), but we would have the same problem that is described in #1440.
Even if implemented, it's questionable if this is desired behavior, so maybe we …
> feat(trin-execution): allow ctrl+c to immediately stop execution

- .circleci/config.yml
- README.md
resolve concern gave here https://github.com/ethereum/trin/pull/1426#issuecomment-2333431869
TL:DR, `cargo check` doesn't fully verify an application can be compiled 
Change Window's CI from doing `cargo check` to `cargo build` the reason for this is `cargo check` doesn't verify there isn't any linker error's
> chore: update windows  ci from `cargo check` -> `cargo build`

- Cargo.lock
- Cargo.toml
- e2store/Cargo.toml
- e2store/src/utils.rs
- ethportal-api/src/types/execution/block_body.rs
- ethportal-peertest/Cargo.toml
- light-client/Cargo.toml
- portal-bridge/Cargo.toml
- portal-bridge/src/api/consensus.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/stats.rs
- src/bin/historical_batch.rs
- src/bin/test_providers.rs
- trin-beacon/src/validation.rs
- trin-execution/Cargo.toml
- trin-execution/src/era/binary_search.rs
- trin-execution/src/era/manager.rs
- trin-execution/src/era/utils.rs
fixes https://github.com/ethereum/trin/issues/1446 surf has been unmaintained for over 2 years now, it is also using a old version of packages which prevents us from compiling Trin to Risc-v https://github.com/ethereum/trin/issues/1444
Just convert `surf` -> `reqwest` equivalents, which was pretty straight forward
> refactor: remove unmaintained surf for reqwest

- ethportal-api/src/beacon.rs
- ethportal-api/src/types/consensus/light_client/mod.rs
- ethportal-api/src/types/consensus/light_client/store.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- light-client/src/client.rs
- light-client/src/consensus/consensus_client.rs
- light-client/src/node.rs
- rpc/src/beacon_rpc.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/network.rs
- trin-beacon/src/validation.rs
- trin-validation/src/oracle.rs
Fixes  #1406
This PR adds full light client content validation for `LightlClientUpdate`, `LightClientOptimisticUpdate`, and `LightClientFinalityUpdate` content on a protocol level. (before storing and gossiping the content to peers).
- Add a new JSON-RPC endpoint to get the current `LIghtClientStore`  data.
- Refactor and expose the validation method as a public from the light client module. This allows us to use the same validation in` BeaconValidator` as the light client sync protocol.
- Add the validation steps in `BeaconValidator`.
> feat(beacon): add full validation for light client updates

- Cargo.lock
- Cargo.toml
- src/bin/poll_latest.rs
- src/bin/sample_range.rs
- tests/rpc_server.rs
- tests/utils/mod.rs
`ethers.rs` is deprecated https://github.com/gakonst/ethers-rs/issues/2667 because of this they are using outdated packages, which are blocking Risc-v complication support https://github.com/ethereum/trin/issues/1444 of Trin (Risc-V is a open source IPA, or competitor to Arm and x86 cpu architectures) 
By switching it to use alloy which is the replace of `ether's.rs`
> refactor: remove deprecated ethers.rs and replace it with alloy

- ethportal-api/src/types/content_key/history.rs
- ethportal-peertest/src/scenarios/basic.rs
- ethportal-peertest/src/scenarios/paginate.rs
- ethportal-peertest/src/scenarios/state.rs
- ethportal-peertest/src/scenarios/validation.rs
- portal-bridge/src/api/execution.rs
- portal-bridge/src/bridge/era1.rs
- rpc/src/eth_rpc.rs
- src/bin/poll_latest.rs
- src/bin/sample_range.rs
- tests/rpc_server.rs
- trin-history/src/validation.rs
- trin-state/src/validation/validator.rs
- trin-validation/src/oracle.rs
Minor refactor to content keys
Added `From` trait to simplify construction
> refactor: add from bytes trait to content key

- Cargo.lock
- ethportal-api/src/types/query_trace.rs
- portalnet/Cargo.toml
- portalnet/src/find/iterators/findcontent.rs
- portalnet/src/find/iterators/findnodes.rs
- portalnet/src/find/iterators/query.rs
- portalnet/src/find/query_pool.rs
- portalnet/src/overlay/service.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
Work toward #1383 
This PR *will* delay completion of RFC until data is validated, but will *not* continue the search with other peers. I decided it was getting too big. I will do the follow-up work in another PR.
There are quite a few moving parts here, so the goal was to minimize the
number of functional changes in this refactor.
Overall: add a new query state for while the content is being validated.
Don't exit the query until validation is complete.
Some other changes along the way:
Note that when handling the FindContentQueryResponse::ConnectionId in
findcontent.rs, we don't do the bigendian conversion anymore. That has
been moved to earlier in the process, when handling the Content message,
to reduce the number of places that the conversion needs to be handled.
The received_from …
> Continue the RecursiveFindContent query until the uTP transfer is complete and the content is validated

- Cargo.lock
- Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-api/src/eth.rs
- ethportal-api/src/types/execution/header.rs
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/scenarios/paginate.rs
- rpc/Cargo.toml
- rpc/src/eth_rpc.rs
- trin-execution/Cargo.toml
- trin-execution/src/engine/mod.rs
- trin-execution/src/engine/rpc.rs
- trin-execution/src/evm/tx_env_modifier.rs
- trin-execution/src/lib.rs
We don't implement the engine api. The first step to do this is by adding the jsonrpcee trait outline.
The engine api, exposes the `engine` namespace and also a subset of the `eth` namespace, both under JWT authentication.
I made a PR first just adding the trait to make the changes easier to review, my follow up PR's will be implementing the rest of the Engine API I am not sure how many PR's it will end up being, but I will try to make them all easily review-able sizes
Implementing the jsonrpcee trait which outlines both the `engine` and `eth` (subset) namespaces which is required to support the engine API
> feat(trin-execution): add JSON-RPC trait's required for the Engine API

- Cargo.lock
- ethportal-api/src/types/cli.rs
- ethportal-api/src/types/portal_wire.rs
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/handle.rs
- portalnet/Cargo.toml
- portalnet/src/discovery.rs
- portalnet/src/overlay/service.rs
- portalnet/src/utils/db.rs
- portalnet/tests/overlay.rs
- rpc/src/rpc_server.rs
- src/bin/purge_invalid_history_content.rs
- src/lib.rs
- trin-execution/Cargo.toml
- trin-execution/src/cli.rs
- trin-execution/src/execution.rs
- trin-execution/src/main.rs
- trin-execution/src/storage/account_db.rs
- trin-execution/src/storage/utils.rs
- trin-execution/src/trie_walker.rs
- trin-execution/src/types/block_to_trace.rs
- trin-execution/tests/content_generation.rs
- trin-utils/Cargo.toml
- trin-utils/src/dir.rs
- trin-utils/src/lib.rs
- utp-testing/src/lib.rs
Currently, `trin-execution` binary doesn't support setting custom directory and `trin` supports it only via env variable. Also the code initializes directory is split.
Added `data-dir` command line flag to both `trin` and `trin-execution`, and extracted common logic into `trin-utils` crate.
- if neither `data-dir` nor `ephemeral` flags are set, we use OS's default local data directory (same as now)
- if only `data-dir` is set, we use that folder instead
- if only `ephemeral` is set, we use OS's temporary directory, and create `trin`/`trin-execution` subfolder inside (same as now)
- if both flags are set, it behaves the same as with `ephemeral`, but it uses provided directory instead of OS's temp directory
In the case of trin, I left an option for env variable (`TRIN_DATA_PATH`) to be …
> feat: unify data directory cli

- docker/Dockerfile
- docker/Dockerfile.bridge
I forgot to add `trin-evm` to docker files (should have been part of #1470)
I added `trin-evm` and sorted folders by name.
> fix(docker): add trin-evm directory to docker

- portalnet/src/overlay/service.rs
The locks on the query pool are unnecessary. Locks suck. Remove them wherever possible.
Moving the query pool into a future::poll seems to be the only place that clone was required. It is relatively straightforward to route around that.
> Remove query pool locks

- trin-execution/src/evm/post_block_beneficiaries.rs
- trin-execution/src/main.rs
When executing 17034871 we are generating the wrong state root
I found the issue was we had to convert the amount in the withdrawal to the amount in the denomination of WEI. We do the same thing for block rewards.
With this fix we can now execute to Cancun
> fix: unable to execute to Cancun due to bug in post_block_beneficiaries

- trin-execution/tests/content_generation.rs
The `trin-execution/tests/content_generation.rs` is not logging any useful information at the moment.
Adding stats for:
- count of content
- size of content that would be gossiped
- size of content that would be stored
These stats are both per block and combined.
Also added env variable (`BLOCKS`) that controls how many blocks to execute.
---
Using this PR, I found that for the first 1 million blocks, we have a total of:
- 15.3 million content key/value pairs
- 26.8 GB of data to gossip (with proofs)
- 7 GB of data to store (without proofs)
Running this took ~1.5 h.
> feat: add stats logging to trin-execution/tests/content_generation.rs

- Cargo.lock
- Cargo.toml
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/gossip.rs
- portal-bridge/src/gossip.rs
- portal-bridge/src/stats.rs
- rpc/Cargo.toml
- rpc/src/cors.rs
- rpc/src/errors.rs
- rpc/src/rpc_server.rs
The jsonrpsee version we are using is more than a year old. Some other dependencies already updated theirs (e.g. reth-rpc-types).
I also removed direct dependency on hyper.
Updated the dependencies and refactor the code where needed.
> chore(deps): update jsonrpsee dependency

- ethportal-api/src/types/bootnodes.rs
- ethportal-api/src/types/cli.rs
- portalnet/src/config.rs
- portalnet/src/discovery.rs
- trin-beacon/src/lib.rs
- trin-beacon/src/network.rs
- trin-history/src/lib.rs
- trin-history/src/network.rs
- trin-state/src/lib.rs
- trin-state/src/network.rs
fixes #1460
Added angelfood bootnodes and logic to handle the correct bootnodes depending on what network's selected.
> fix: use default angelfood bootnodes if network is selected

- portalnet/src/find/iterators/findcontent.rs
- portalnet/src/overlay/service.rs
Fix #1383 
- send a new message back to the query when the transfer fails, or the validation fails
- resume the search for content when the new message arrives
- expand the existing test to verify that content is eventually found, even if it sometimes is invalid
> Continue searching for content when an earlier transfer of content fails, or is invalidated

- portalnet/src/gossip.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
The gossip logic holds kbuckets lock for non-trivial amount of code-lines, which makes my improvements regarding kbuckets lock somewhat hard. So I want to refactor this logic upfront.
Extracted logic that uses locks into separate functions: `interested_enrs` and `batch_interested_enrs`. These functions will be moved into separate structure in the next PR so they shouldn't contain gossip specific functionality (e.g. calling `select_gossip_recipients`).
> refactor: refactor gossip usage of kbuckets

- ethportal-api/src/types/discv5.rs
- ethportal-peertest/src/scenarios/basic.rs
- portalnet/src/discovery.rs
- portalnet/src/overlay/protocol.rs
We are using String to represent NodeId in json types.
I believe this isn't necessary as NodeId serialization is the same as what we are using (hex string prefixed with "0x").
This is not a big deal, but something I encounter while refactoring kbuckets.
Changed String to NodeId as type.
> refactor: use NodeId instead of String for discv5 json types

- ethportal-api/src/types/portal.rs
- ethportal-api/src/types/portal_wire.rs
Fix #1484 
Increase the size of the Accept Bitlist
> fix: accept up to 64 content items, not just 8

- ethportal-api/src/beacon.rs
- ethportal-api/src/history.rs
- ethportal-api/src/state.rs
- ethportal-api/src/types/portal_wire.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- portal-bridge/src/bridge/state.rs
- portalnet/src/gossip.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- rpc/src/beacon_rpc.rs
- rpc/src/history_rpc.rs
- rpc/src/state_rpc.rs
Updated `trace_offer` to return more detail about what happened during the `Offer`, specifically to identify between cases where the offered key was rejected, or the transfer failed, which is helpful to know inside the state bridge.
- added `OfferTrace` type to capture more information about failed `trace_offer` requests
> Add detailed info to offer trace

- portal-bridge/src/bridge/state.rs
- portal-bridge/src/census.rs
2 defaults that come to mind which could be influencing the speed of the state bridge are...
- the rate at which we perform a liveness check on a peer in the census
- the # of enrs we offer each piece of content
I'm not quite sure how to test that these will actually improve the speed, but they seem to be likely candidates imo.
It might also be worth updating these values to be set via cli, so that we can experiment with different values on different bridges? LMK if you think this is worthwhile and I'll update
I also added a log for a "global" state bridge offer report to understand how the bridge is performing overall.
Updated default values.
> fix: update slow state bridge defaults

- ethportal-api/src/types/query_trace.rs
- portalnet/src/find/query_pool.rs
- portalnet/src/overlay/service.rs
There is no way to acknowledge and track whether a peer experiences a variety of failures during a query, and how long that took.
Add a new tracking HashMap in the QueryTrace object, to track utp and validation errors.
Still need to actually use the new QueryTrace API in the overlay service.
> Add peer failures to query traces

- book/src/developers/contributing/releases/deployment.md
Deployment docs don't include information that state bridges should most likely not be updated, and it doesn't provide instructions how to deploy other state network nodes.
Updated docs.
> docs: add note about state bridges to deployment docs

- trin-beacon/src/validation.rs
When the beacon light client is not synced, we can't process a `HistoricalSummariesWithProof` content to a `FindContent` request. 
Validate `HistoricalSummariesWithProof` against the state root if the light client finalized root is available.
> feat(beacon): validate `HistoricalSummariesWithProof` if finalized state root is available

- trin-execution/src/cli.rs
- trin-execution/src/main.rs
It's not possible to configure trin-execution to stop early (it will execute all blocks up to Cancun fork or until stopped).
Added optional command line flag to support early stop.
> feat: add "last-block" command line flag to trin execution

- portal-bridge/README.md
- portal-bridge/src/bridge/state.rs
State Bridge only supports gossiping blocks starting from 0.
We know that content from first ~500'000 blocks are saturated, and we might want to skip them to speed up the process.
Add support for range gossip.
We will still execute blocks starting from zero, but we will gossip only blocks from the range.
Specifying single block would imply gossiping all blocks starting from zero and ending with provided block.
This was left unmodified for backward compatibility, until we upgrade deployment scripts.
In my opinion, single block should gossip entire state trie at the specified block (but this requires more work).
> feat(state-bridge): add support for gossiping blocks from a range

- portal-bridge/src/census/mod.rs
- portal-bridge/src/census/network.rs
Currently all census logic is in one file. This makes any future changes harder to review (as more files will be created and history might not be preserved).
This PR has 3 small commits:
- move `Network` and `Subnetwork` into separate file
- remove `Subnetwork` type and use similar one from `ethportal-api` crate
- select peers randomly
- I believe that current implementation always selects the same peers (at least until `peers` collection is updated, which isn't frequent)
> refactor(census): split census into multiple files and remove "Subnetwork"

- Cargo.lock
- portalnet/Cargo.toml
- portalnet/src/gossip.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- portalnet/src/types/kbucket.rs
- portalnet/src/types/mod.rs
The `kbuckets` are widely used and they are wrapped in `Arc<RwLock<>>` for asynchronous access.
This can be dangerous combination as it's easy to hold the `kbuckets` lock and try to acquire some other lock or do `.await`. This was the root problem of the #1390 .
I wrapped `Arc<RwLock<KBucketsTable<NodeId, Node>>>` in a structure (that I named `SharedKBucketsTable`).
Every time lock is acquired, it's held only for the minimum amount of time, during one function call.
This approached is recommended in https://draft.ryhl.io/blog/shared-mutable-state/ , which is referenced from: https://tokio.rs/tokio/tutorial/shared-state#restructure-your-code-to-not-hold-the-lock-across-an-await
I tried to minimize functionality changes. Here are highlights:
- `interested_enrs` and `batch_interested_enrs` …
> refactor: extract kbuckets into separate structure

- trin-execution/src/cli.rs
- trin-execution/src/main.rs
- trin-execution/src/storage/execution_position.rs
- trin-execution/src/subcommands/era2/export.rs
- trin-execution/src/subcommands/era2/import.rs
- trin-execution/tests/export_import.rs
The import/export state in `trin-execution` don't need TrinExecution. They only need `EvmDb` and `ExecutionPosition`.
No tests that test import/export end to end.
Refactor how Importer/Exporter are initialized.
Also added test that:
- executes fist 1000 blocks
- exports state to era2 file
- imports state from era2 file (into new directory)
- executes another 1000 blocks
> refactor(trin-execution): state import/export don't need TrinExecution

- portal-bridge/src/bridge/state.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/main.rs
- src/bin/test_providers.rs
Pretty simple approach to "horizontally scaling" our state bridge nodes. Introduced a `bridge_id` flag, which calculates whether or not an individual bridge is responsible for gossiping a piece of content.
- using a simple id is easier than managing a bridge's node id and using that to calculate distance to the content
- downsides...
- this approach requires every bridge to iterate over every node in the trie/diff to figure out whether or not it's responsible for gossiping that content. A smarter solution will be needed for gossiping an imported era2 file, or if there's a better solution for chunking the diff, lmk and I'll implement it here.
- there's no redundancy built in, unless you adjust the `bridge_id` accordingly. aka if we have four bridges, use a `bridge_total` of 2
- added …
> feat(bridge): add bridge id cli flag for state bridges

- portal-bridge/src/bridge/state.rs
- trin-execution/src/storage/evm_db.rs
- trin-execution/tests/content_generation.rs
The state bridge is not gossiping contract storage content.
After some debugging, I figured out that the issue is that `EvmDB` is cloned, but `storage_cache` is not behind `Arc`.
Because of that, the `TrinExecution.database.storage_cache` is never updated (instead, only `BlockExecutor.evm.db_mut().database` is).
Wrapped `storage_cache` in `Arc<Mutex<_>>`.
Added additional metric to `test_we_can_generate_content_key_values_up_to_x` to confirm that issue was fixed and measure the difference.
Also tested locally and can confirm that state bridge now gossips contract storage content.
> fix(state bridge): gossip contract storage tries

- book/src/developers/contributing/releases/deployment.md
I dealt with `docker_compose_v2` error on my Linux and Mac machines when running ansible for Glados.
Add a step in the book with a command to fix the issue.
> chore(book): add a note about resolving `docker_compose_v2` error in ansible

- trin-storage/src/sql.rs
Deploying beacon on testnet bootnodes and state regular nodes, causes Trin to fail because of an implemented db column change without a proper migration. This change was introduced [here](https://github.com/ethereum/trin/pull/1413/files#diff-d79c9290a61b26e8d078e761fe5397feb9ace5b8a73ef8694b7fb74dbe4b905cR57).
I planned to modify the testnet databases with a bash script and ansible, but I had issues connecting to the running docker containers sqlite files and went into a rabbit hole.
Revert the column name change causing the issue back to the original.
This is a quick and dirty?! fix to deploy beacon on testnet without db issues until we implement a proper migration for the beacon db.
> fix(beacon): revert column name change to `historical_summaries` db table

- Cargo.lock
- e2store/Cargo.toml
- e2store/README.md
- e2store/src/e2store/stream.rs
- e2store/src/era2.rs
- trin-execution/src/subcommands/era2/export.rs
- trin-execution/src/subcommands/era2/import.rs
The `E2StoreStream` uses `File` structure for reading/writing into file. This can be more optimized by using `BufReader`/`BufWriter`.
I split `E2StoreStream` into `E2StoreStreamReader` and `E2StoreStreamWriter` that use `BufReader`/`BufWriter`. I also had to split `Era2` into `Era2Reader` and `Era2Writer`.
In my opinion, this split makes more sense as it would most likely be wrong to read and write into the same file at the same time.
To measure if this actually improves performance as I expect, I did the following:
0. generated era2 files for blocks 3 million, 4 million and 5 million
1. built release version of `trin-execution` binary at both `master` and this `pr`
2. for both builds (master/pr), imported each era2 state into clean directory
3. exported era2 from directory from step2 …
> feat: split E2StoreStream into reader and writer

- ethportal-api/src/beacon.rs
- ethportal-api/src/history.rs
- ethportal-api/src/state.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/scenarios/gossip.rs
- ethportal-peertest/src/scenarios/offer_accept.rs
- ethportal-peertest/src/scenarios/state.rs
- portalnet/src/gossip.rs
- portalnet/src/overlay/protocol.rs
- rpc/src/beacon_rpc.rs
- rpc/src/history_rpc.rs
- rpc/src/state_rpc.rs
- tests/self_peertest.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
updates Trin to match proposed spec changes https://github.com/ethereum/portal-network-specs/pull/342
updating our code to match the spec
> feat: update `portal_*Offer` to handle multiple pieces of content

- portal-bridge/src/bridge/state.rs
- portal-bridge/src/census/mod.rs
- portal-bridge/src/census/network.rs
- portal-bridge/src/census/peers.rs
- portal-bridge/src/main.rs
It's difficult to add features (e.g. #1501) to the Census in its current form.
Also, getting peers to gossip content to doesn't have to be asynchronous and as such, doesn't have to go over separate channel.
Split the census into multiple components, each responsible for small part:
- `Peers` - contains all peers (behind RwLock) 
- responsible for deciding when they should be pinged for liveness
- in the future, it will also be responsible for holding additional information about peers (e.g. success/failure of other non-ping requests), and scoring peers according to those information
- `Network` - contains and propagates calls to `Peers`
- responsible for pinging and discovering other peers
- 'Census' - the only entry point for users of Census (i.e. state bridge)
- responsible for …
> refactor: split census into multiple types

- Cargo.lock
- e2store/Cargo.toml
- e2store/README.md
- e2store/src/bin/era2-stats.rs
Adding binary that reads era2 file and prints most basic stats.
I used it to measure performance improvements of #1509, but I think it can't hurt to merge it as well (as it can easily be modified to do more complex analysis).
> feat: add binary for simple era2 analysis

- Cargo.lock
- ethportal-peertest/Cargo.toml
- ethportal-peertest/src/scenarios/offer_accept.rs
- ethportal-peertest/src/utils.rs
- tests/self_peertest.rs
Added a test to make sure that trin will always manage at least the default # of concurrent utp txs. The test/constant can also easily be increased to test trin's real tx capacity (currently somewhere around 100 from what I've seen, but still working to see if this can be improved)
Added the test
> test: add test for default utp concurrency limit

- portal-bridge/src/bridge/beacon.rs
Requesting a beacon state over JSON causes the Pandaops nodes to run OOM.
Disable temporary  `HistoricalSummariesWithProof` until we implement an option for ssz requests or a new debug endpoint is implemented in Nimbus, which will not require a download the full beacon state.
> fix(portal-bridge): Temporarily disable `HistoricalSummariesWithProof` gossip

- Cargo.lock
- Cargo.toml
- src/bin/poll_latest.rs
- src/bin/sample_range.rs
- tests/rpc_server.rs
- trin-evm/src/tx_env_modifier.rs
- trin-execution/Cargo.toml
- trin-execution/src/engine/rpc.rs
- trin-execution/src/storage/evm_db.rs
Automatic `cargo update` failed (see #1496 and #1508).
- manually updated "alloy-*" and "revm-*" dependencies
- updated dependencies in `trin-execution/src/storage/evm_db.rs`
- we now use `alloy_primitives::map::FbHashMap` which is optimized when keys are fixed byte arrays
- removed dependency on `alloy` and added dependency only on crates that we use (`alloy` just exports other crates)
-  alternatively, we can use `alloy` everywhere and only enable features that we need, where we need them
Note: first commit is automated `cargo update` (#1508), second one is my fix.
> chore: automatic cargo update + manual alloy-* and revm-* update

- trin-beacon/src/validation.rs
We were incorrectly validating the `LightClientFinalityUpdate` content key against the value.
Update the comparison because the portal beacon protocol is designed always to return the latest finality update with finalized slot that is bigger or equal to the requested content key.
> fix(trin-beacon): fix light client finality update validation

- ethportal-peertest/src/utils.rs
- trin-beacon/src/validation.rs
> fix: revert changed const in peertest utils and fix light client update validation test

- ethportal-api/src/types/execution/block_body.rs
- portal-bridge/src/types/full_header.rs
- trin-execution/src/era/utils.rs
- trin-history/src/validation.rs
Some `BlockBody`'s functions return `anyhow::Result` type when then don't need to, and they clone objects, instead of returning references.
Changed function signature to return `&[T]` instead.
**Note:** I think that `calculate_merkle_patricia_root` (used `transactions_root` and `withdrawals_root`) should return `B256` (instead of `anyhow::Result<B256>`).
The api that we use (`eth-trie`) can fail, but it shouldn't in this case (we create new trie and use in-memory db), so I'm in favor of panicing instead of returning `Result`.
I didn't add it in this PR in order not to complicate things, but I'm willing to add it if that's direction we want to go with.
> refactor: block body fn: transactions(), uncles() and withdrawals()

- ethportal-api/src/eth.rs
- rpc/Cargo.toml
- rpc/src/eth_rpc.rs
- tests/rpc_server.rs
Trin currently doesn't support eth_getBlockByNumber or eth_call with block specified as number.
Added support for `eth_*` JSON rpc request for fetching block by number.
> feat: add support for eth_getBlockByNumber

- portalnet/src/utp_controller.rs
Shrink the idle timeout from the default of 60 seconds to 10. This comes up most often in failed connections, which are perpetually idle, and keep trying until the timeout expires.
During a find-content call, if a uTP transfer is initiated and the remote peer fails to connect, the default timeout waits for 60 seconds. The problem is that 60s is also our entire query timeout. So if the utp connection fails by timeout, then there is no time to attempt downloads from alternate peers.
By shrinking the timeout to 10 seconds, we leave plenty of room for contacting other peers for the same content. It still allows us to make a few attempts at connection (after 1s, then another 1.5s, then another 2.25s, then another 3.375s).
This timeout was previously 32 seconds, then increased to 60s: …
> feat: shorter utp timeout, for more reliable query

- book/src/developers/protocols/json_rpc.md
- book/src/users/use/portal_network_data.md
- ethportal-api/src/beacon.rs
- ethportal-api/src/history.rs
- ethportal-api/src/state.rs
- ethportal-api/src/types/jsonrpc/endpoints.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/gossip.rs
- ethportal-peertest/src/scenarios/utp.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/gossip.rs
- rpc/src/beacon_rpc.rs
- rpc/src/eth_rpc.rs
- rpc/src/evm_state.rs
- rpc/src/history_rpc.rs
- rpc/src/state_rpc.rs
- src/bin/poll_latest.rs
- src/bin/sample_range.rs
- tests/self_peertest.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
- trin-state/src/validation/validator.rs
- trin-validation/src/oracle.rs
updates our codebase to match spec https://github.com/ethereum/portal-network-specs/pull/344
by renaming `portal_*RecursiveFindContent` to `portal_*GetContent`
> refactor: update jsonrpc endpoint from *RecursiveFindContent to *GetContent

- ethportal-peertest/src/scenarios/basic.rs
- portalnet/src/discovery.rs
- portalnet/src/overlay/service.rs
- portalnet/tests/overlay.rs
- rpc/src/rpc_server.rs
- src/lib.rs
- utp-testing/src/lib.rs
last year I attempted to fix a bug where every time trin booted our sequence number was always default (0 or something) which was bad because that meant that peers would think our Enr we were sending  was outdated as they would have an enr of our node already with a higher sequence https://github.com/ethereum/trin/pull/937
The issue with this solution was sigp/discv5 would sometimes update the Enr and incremeant the sequence because this is done on the sigp/discv5 level we wouldn't save the sequence number to a file to restore on reboot so the same bug could occur which I tried to fix before.
sigp/discv5 sometimes updates the IP of the node which is good because most households have dynamic IP address or what if Trin is running on a laptop we need to be able to handle IP changes.
By …
> fix: set Enr sequence to current epoch timestamp

- tests/self_peertest.rs
Master turned red, `peertest_offer_concurrent_utp_transfer_limit` is failing sporadically. #1529 seemed to uncover an issue of flakiness in the `peertest_offer_concurrent_utp_transfer_limit` test.
Ignore the test, until we can identify the problem with the test. This should get master reliably passing CI again.
Also had to remove the `#[serial]` attribute.
> test: ignore flaky utp concurrency limit test

- ethportal-api/src/types/execution/header.rs
- ethportal-api/src/types/execution/withdrawal.rs
- rpc/src/eth_rpc.rs
- tests/rpc_server.rs
The eth_getBlockByNumber and eth_getBlockByHash don't populate uncles and withdrawals fields of the response (but we have data available).
Populate required fields.
**Note:** I don't know how `size` field should be calculated. Let me know if you do.
> fix: add uncles and withdrawals to eth_getBlockByNumber and eth_getBlockByHash

- portal-bridge/src/bridge/state.rs
- trin-metrics/src/bridge.rs
There is no metric on how state bridge is performing (only timer that measures how long it takes).
Added metric that counts total number of offer requests and their result (success, rejected, failed).
> feat: add offer metric to state bridge

- book/src/users/use/ethereum_data.md
When trying to use `eth_blockNumber` as recommended in the docs, it failed. It probably should work, especially when enabling beacon, but that's a problem for another day.
- Replace eth_blockNumber with eth_getBlockByNumber example
- Add an eth_call example to show off state access
- Remind people why they want to use a web3-like tool
> docs: examples for eth_* RPC calls

- ethportal-api/src/beacon.rs
- ethportal-api/src/history.rs
- ethportal-api/src/state.rs
- ethportal-api/src/types/portal.rs
- ethportal-peertest/src/scenarios/find.rs
- ethportal-peertest/src/scenarios/utp.rs
- ethportal-peertest/src/scenarios/validation.rs
- portal-bridge/src/bridge/era1.rs
- portal-bridge/src/gossip.rs
- rpc/src/beacon_rpc.rs
- rpc/src/eth_rpc.rs
- rpc/src/evm_state.rs
- rpc/src/history_rpc.rs
- rpc/src/state_rpc.rs
- src/bin/poll_latest.rs
- trin-beacon/src/jsonrpc.rs
- trin-history/src/jsonrpc.rs
- trin-state/src/jsonrpc.rs
- trin-state/src/validation/validator.rs
- trin-validation/src/oracle.rs
fixes https://github.com/ethereum/trin/pull/1526#discussion_r1799174704
Basically the `ContentInfo` type we were using for our `FindContent` and `GetContent` RPC endpoints were leaking information implementation details not related to the endpoints
Split `ContentInfo` into 
- `FindContentInfo`
- `GetContentInfo`
and only expose the datatypes specified in the `portal-network-specs` json-rpc specification
> refactor! clean up ContentInfo type, remove unexpected paths

- ethportal-api/src/types/execution/block_body.rs
- ethportal-api/src/types/execution/transaction.rs
- rpc/src/eth_rpc.rs
- tests/rpc_server.rs
An alternative approach to #1536. Now that I see both of them, I think I prefer this one a bit more.
Transaction can be rlp encoded/decoded with (less common) or without (most common) additional rlp header.
Currently, we have to deal with less common case manually, which isn't great. As of now, we have two use cases for it: inside BlockBody and as block size inside eth_getBlockBy* calls (which is not implemented).
Added separate type `TransactionWithRlpHeader` that is just a wrapper around `Transaction` with different `Encodable`/`Decodable` implementation.
> refactor: transaction rlp encoding

- rpc/src/eth_rpc.rs
- tests/rpc_server.rs
The `eth_getBlockBy*` JSON rpc calls didn't return `size` field.
The #1541 added support for calculating `size` field easily, so we are using it here.
Tested it locally by trying dozens of blocks (both recent and pre-merge) and comparing size field with the ones returned by: https://sandbox.alchemy.com/?method=eth_getBlockByNumber
> feat: support "size" in eth_getBlockBy*

- ethportal-api/src/types/content_key/overlay.rs
- ethportal-api/src/types/content_value/mod.rs
- ethportal-api/src/types/portal.rs
The `RawContentKey` and `RawContentValue` were lacking documentation and explanations.
See #1404 for details.
Added more detailed docs.
> docs: update RawContentKey and RawContentValue docs

- .gitignore
- book/mermaid-init.js
- book/src/SUMMARY.md
- book/src/concepts/README.md
- book/src/introduction/README.md
- book/src/introduction/portal_network.md
- book/src/introduction/quickstart.md
There was no Quickstart to get a user quickly using trin.
- Simplified the intro page
- Added a new Quickstart page immediately after the intro
- Moved Portal Network concepts to a new Concepts chapter
- Switch mermaid diagrams to use dark theme, which better matches the book theme (it was hard to see diagram arrows)
- Cleaned up a content network search diagram that incorrectly added a network hop
Unrelated: ignore ctags created by rusty-tags
> docs: add quickstart, dark mermaid theme, etc

- ethportal-api/src/types/content_key/beacon.rs
- ethportal-api/src/types/content_key/history.rs
- ethportal-api/src/types/content_key/overlay.rs
- ethportal-api/src/types/content_key/state.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- trin-beacon/src/storage.rs
- trin-history/src/storage.rs
- trin-state/src/storage.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-validation/src/header_validator.rs
Conversion from byte array into content key isn't flexible enough.
Currently, `OverlayContentKey` has to implement `TryFrom<RawContentKey>`, while sometimes it would be easier if we wouldn't have to convert other byte array  types (e.g. `Vec<u8>`) into `RawContentKey` (even though performance wise, it might not make big difference).
Instead of `OverlayContentKey` extending `TryFrom<RawContentKey>` it now has `try_from_bytes` function that has to be called explicitly. This goes nicely with `to_bytes` function.
The `from_hex` function was renamed to `try_from_hex` function in order to have same naming scheme.
Additional smaller refactoring is done in beacon, history and state content key implementations:
- `to_bytes` implementation is now identical
- instead of using `Vec<u8>` we use …
> refactor!: make content key decoding more flexible

- e2store/src/utils.rs
- trin-execution/src/execution.rs
- trin-execution/src/trie_walker.rs
- trin-execution/tests/export_import.rs
We had tests which would fail due to missing data on a website, some tests still fail too due to this, but we want those tests so I set them to ignore
removing the tests or ignore them. Trin Execution will still exit on start with the errors if any era files are missing so we are good
> chore: remove/ignore tests which download from a remote server

- Cargo.lock
- trin-state/Cargo.toml
- trin-state/src/lib.rs
Related to #1545 -- to start we at least want to measure CPU usage. However we decide to respond to it, it is a thing we will want to respond to. So this is an experiment to see how well the library works at observing usage, to lay the groundwork for later steps.
Add `cpu_time` to track the amount of cpu usage that trin has. It's a bit hacky to put it in the `trin-state` report, because it's just measuring everything happening in the process. But since state is not stabilizing (and seems to be the culprit for high usage currently), it seems like a good place to add the log.
It's already been a convenient way to watch my machine react as I experiment with the CPU effect of various changes.
Example log:
```
2024-10-24T04:53:32.129663Z  INFO trin_state: reports~ data: radius=12% …
```
> feat: log cpu utilization in state network report

- e2store/src/bin/era2-stats.rs
The "era2-stats" binary doesn't check validity of the file.
Added validation. The only thing missing is checking that state data actually results in the canonical state trie, but that is covered by `import-state` subcommand of the trin-execution.
> feat: add format validation to era2-stats binary

- portal-bridge/src/census/network.rs
- portal-bridge/src/census/peers.rs
During regular liveness check, census can detect that ENR sequence increased, but will not fetch new ENR.
If ENR sequence received in Pong is higher than the one we know, sends FindNodes request (with distance `0`).
If either Ping of FindNodes fails, liveness check is considered failure.
> fix: census should update ENR on liveness check

- portal-bridge/src/bridge/state.rs
- trin-execution/src/config.rs
- trin-execution/src/storage/evm_db.rs
- trin-execution/tests/content_generation.rs
We would always bridge contracts, which isn't good because the contract should already be gossiped on the network. This takes up a lot of bridge bandwidth, which is redundant as the contracts should already be on the network.
By using a `cache` to store newly created contracts like we do for `storage_trie` diffs.
> feat: only bridge newly created contracts

- ethportal-api/src/types/cli.rs
1GB seems like a reasonable default number. Big enough to help the network, small enough to not be a nuisance on most setups.
---
For context: this PR used to be about turning on state by default. Now it's just about the storage size default.
> feat: set default storage size to 1GB

- ethportal-api/src/types/bootnodes.rs
- ethportal-api/src/types/cli.rs
- ethportal-peertest/src/lib.rs
- ethportal-peertest/src/scenarios/gossip.rs
- tests/rpc_server.rs
- tests/self_peertest.rs
#1558 changed argument of `TrinConfig::new_from` from `Iterator<T>` to `IntoIterator<T>`.
This left many places unnecessarily using `.iter()` when calling it.
Removed `.iter()`.
> chore: simplify TrinConfig::new_from usage

- trin-storage/src/config.rs
_I don't have strong feelings about what the new ratio should be. I just picked one, mostly to kick off discussion. Now, we have more information than we did at the 99:1 ratio selection._
The new ratio is still a loose guess. But it is based on some recently acquired state data, specifically:
A recent average amount of new state generated is about 1.75MB / block or ~375 GB per month. Let's make room for 10 years of intremental state at that rate, which gives us a network size of: ~45 TB.
The typical history node can fill up 35GB of storage with a ~2% radius, implying a network size of: ~1.75 TB.
45 TB / 1.75 TB ~= 25:1 ratio
Inspired by conversation and data collection here: https://discord.com/channels/890617081744220180/1089234065816821860/1300370058366947370
> feat: update state:history storage to 1:1

- trin-storage/src/config.rs
#1558 added a new test for the storage ratios, #1561 updated the storage ratio, but CI ran before 1558 was merged. So the new tests started failing on master after 1561 was merged.
> test: update test for history:state storage ratio

- Cargo.lock
- Cargo.toml
- e2store/Cargo.toml
- ethportal-api/Cargo.toml
- ethportal-peertest/Cargo.toml
- light-client/Cargo.toml
- portal-bridge/Cargo.toml
- portalnet/Cargo.toml
- rpc/Cargo.toml
- trin-beacon/Cargo.toml
- trin-evm/Cargo.toml
- trin-execution/Cargo.toml
- trin-history/Cargo.toml
- trin-metrics/Cargo.toml
- trin-state/Cargo.toml
- trin-storage/Cargo.toml
- trin-utils/Cargo.toml
- trin-validation/Cargo.toml
- utp-testing/Cargo.toml
Closes #878 
The printed version from `trin --version` is the one from the trin-utils package. This change makes the trin-utils version always track the workspace version.
While I was at it, I also set a bunch of other properties to track the matching workspace properties.
Would be nice to get this fix in before the upcoming stable release of trin.
> fix: show workspace version from trin --version

- Cargo.lock
- Cargo.toml
we were using `eth-trie.rs` from a git instead of crates.io which prevented us from publishing `ethportal-api` to creates.io
publish `eth-trie.rs` then bump our dependency here
> chore: bump `eth-trie.rs` version

- book/src/developers/contributing/releases/deployment.md
Updating deployment documentation for rebooting unresponsive nodes.
> docs: update node reboot instructions

- portal-bridge/src/bridge/state.rs
- portal-bridge/src/census/mod.rs
- portal-bridge/src/census/network.rs
- portal-bridge/src/census/peer.rs
- portal-bridge/src/census/peers.rs
Census doesn't keep track of previous offer requests, their success, duration, etc.
Needed for #1501 
Added recording information of those events. They will be used in followup PR for peer scoring.
> feat(census): keep track of offer requests and their status

- portal-bridge/src/bridge/state.rs
- portal-bridge/src/census/mod.rs
- portal-bridge/src/census/network.rs
- portal-bridge/src/census/peer.rs
- portal-bridge/src/census/peers.rs
- portal-bridge/src/census/scoring.rs
Census doesn't use information about previous successful/failed requests when selecting peers (instead, it selects them randomly). 
Previous PRs made this information available.
Part of #1501
Added `Weight` trait that can be used to calculate peers weights, and `PeerSelector` that picks peers based on weights.
Current implementation of `Weight` is based on [Piper's suggestion](https://github.com/ethereum/trin/issues/1501#issuecomment-2386493645):
- starting weight is 200
- we keep track of up to 255 latest requests per peer
- each successful request in the last 15 min increases weight by 5
- each failed request in the last 15 min decreases weight by 10
- final weight is restricted to [0, 400] range
In the future, we can implement multiple versions of `Weight`, make them configurable via …
> feat(census): add peer scoring

- ethportal-api/src/types/query_trace.rs
- ethportal-peertest/src/scenarios/find.rs
fixes the second part of https://github.com/ethereum/portal-network-specs/issues/352
We were exposing the implementation details of `SystemTime` for the `started_at_ms` when encoding the `QueryTrace` object. This doesn't comply with our Json-RPC spec.
As `started_at_ms` is supposed to be encoded as a milisecond timestamp.
Json only allows for u64's which will last us for millions of years.
for example this is what we are currently returning before this fix
```rust
"startedAtMs": {
"secs_since_epoch": 1730857625,
"nanos_since_epoch": 447534202
}
```
but the result is supposed to be like
```rust
"startedAtMs": 1730857625000,
```
- updating the returned type for `started_at_ms` to a u64
- adding a test to make sure things don't break in the future
> fix: properly encode/decode `started_at_ms` in QueryTrace object

- ethportal-api/src/types/portal_wire.rs
- portalnet/src/discovery.rs
- portalnet/src/find/iterators/findcontent.rs
- portalnet/src/find/query_info.rs
- portalnet/src/gossip.rs
- portalnet/src/overlay/protocol.rs
- portalnet/src/overlay/service.rs
- portalnet/src/utils/portal_wire.rs
- portalnet/src/utp_controller.rs
- portalnet/tests/overlay.rs
- trin-beacon/src/jsonrpc.rs
- trin-beacon/src/storage.rs
- trin-history/src/jsonrpc.rs
- trin-history/src/storage.rs
- trin-state/src/jsonrpc.rs
- trin-state/src/storage.rs
- trin-storage/src/lib.rs
- trin-storage/src/versioned/id_indexed_v1/migration.rs
- trin-storage/src/versioned/id_indexed_v1/store.rs
- trin-validation/src/validator.rs
Replace Vec<u8> with alloy::Bytes or bytes::Bytes based on usage
Replace intermediary usage of Vec<u8> in some places
> feat: alloy bytes conversion

- Cargo.lock
- Cargo.toml
- e2store/Cargo.toml
- e2store/src/utils.rs
- portal-bridge/Cargo.toml
- portal-bridge/README.md
- portal-bridge/src/bridge/state.rs
- portal-bridge/src/cli.rs
- portal-bridge/src/main.rs
- portal-bridge/src/types/mode.rs
- trin-execution/Cargo.toml
- trin-execution/src/subcommands/era2/export.rs
- trin-execution/src/subcommands/era2/import.rs
- trin-execution/src/subcommands/era2/mod.rs
- trin-execution/src/subcommands/era2/utils.rs
- trin-execution/src/trie_walker/db.rs
We didn't have code to gossip a state snapshot from an Era2 file
implementing a era2 snapshot bridging mode
- add a feature to only gossip a portion of the snapshot so that bridging the snapshot can be horizontally scaled
Currently Trin Execution is used as a dependency for `portal-bridge`.
Since `Trin-Execution` will bridge latest diffs by default, and will also eventually run Trin as a library by default. I think I am going to move the State Bridge code into Trin Execution.
So `Trin Execution` will then depend on the `portal-bridge` crate then. Bridging state depends on Trin Execution heavily, whereas the History and Beacon bridge use a JSON-RPC provider. Currently only `portal-bridge` beacon and history can be ran together whereas state must be ran alone regardless.
It is important to …
> feat: add state snapshot bridge

- portalnet/src/overlay/service.rs
It seems that `OverlayService::find_enr` sometimes finds wrong Enr.
See https://github.com/ethereum/trin/issues/1596#issuecomment-2525302159 for more details
This isn't a fix. I'm just adding extra logging to confirm my suspicious and try to find out the root cause of the problem.
> fix: add debug logs to OverlayService::find_enr

- rpc/src/fetch.rs
The error message of failed JSON response can contain `"Unable to locate content on the network"` text, but error itself is not `ContentNotFound` error.
This can happen if `ContentNotFound` error is nested inside some other message.
Currently, returned response doesn't contain details of the original failure (instead it tells us why parsing failed, in not so useful way).
If parsing `ContentNotFoundJsonError` fails, fallback to generic error message instead.
> fix: fallback to custom error if we can't parse ContentNotFound error

- portal-bridge/src/census/mod.rs
It takes 1,200 days to gossip a state snapshot
By lowering `ENR_OFFER_LIMIT` it would drop our time to gossip a state snapshot from 1,200 days to 600 days.
The trade offs of this approach is
- we are gossipping it to less nodes, so there is a lower chance of the gossip succeeding, but this isn't an issue because our new Census/enr choosing mechanism will statistically pick the most optimal nodes. So gossiping to less shouldn't have that big of an impact.
I would say this solution makes sense due to `Neighborhood gossip` https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md#neighborhood-gossip so since we now have a higher likely hood of gossiping the data that nodes that do want it, we can rely on `Neighborhood gossip` to do the rest of the work.
I choose 2 …
> feat: lower ENR_OFFER_LIMIT from 4 to 2

- Cargo.lock
- portal-bridge/src/bridge/state.rs
- trin-execution/Cargo.toml
- trin-execution/src/trie_walker/filter.rs
- trin-execution/src/trie_walker/mod.rs
- trin-execution/src/utils.rs
Walking a whole state trie is very time consuming
By making it so you can filter the trie to only walk a slice of it, this PR will be used in my followup PR, which adds a random walking state snapshot mode.
This mode will be useful for the random slice state snapshot bridge mode I will be adding
> feat: add Filter to TrieWalker

- ethportal-api/Cargo.toml
The only change is the new beacon endpoints merged in e18427e8db833259b8af8238fc6453b4fb7b152a
via
https://github.com/ethereum/trin/pull/1604
> chore: bump ethportal-api to v0.4.0

- .circleci/config.yml
- .dockerignore
- docker/Dockerfile
- docker/Dockerfile.bridge
@njgheorghita brought up a concern that https://github.com/ethereum/trin/pull/1615#discussion_r1904266409 with my PR to update how we get the client info, to use vergen instead of shadow-rs https://github.com/ethereum/trin/pull/1615 that our docker images would no longer get the right git commitment.
He brought up a very good point! The way our dockerfiles were setup vergen wouldn't work properly. 
Remove the requirement to pass `GITHASH` to the docker build, by copying the whole working directory, since then the working directory has access to the .git folder, we no longer need to pass it in.
Another thing is now we don't need to update our dockerfile everytime we add a new crate, which will improve maintainability.
Because we are now copying the whole workspace, to not lose caching …
> refactor: update docker images to use cargo-chef

- .circleci/config.yml
When we merged a PR our docker build CI would only build on master
This has lead to CI on master failing a few times in 2024 after we update crates
When something like this fails, it is a good sign we should update our systems to prevent it.
So I enabled running the docker build CI on PR's which will prevent this from happening again in the future
> chore(ci): enable docker build ci on PR's

- Cargo.lock
- ethportal-api/Cargo.toml
- ethportal-api/src/types/jsonrpc/request.rs
A transitive dependency (`idna`) via [`validator`](https://crates.io/crates/validator) was causing [Cargo Audit](https://crates.io/crates/cargo-audit) to show a security vulnerability.
Bumped `validator` to its most recent released version, making a slight syntax change caused by a breaking change to that crate.
> chore(ethportal-api): bump validator to 0.19.0 (#1612)

- light-client/src/consensus/consensus_client.rs
Well I was reviewing our light-client code I notice a spelling mistake
corrected it
> chore: fix spelling mistake perriod -> period

- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/dependencies.yml
- .github/workflows/release.yml
CI is failing with https://github.com/ethereum/trin/actions/runs/12695272279/job/35386819592?pr=1624
```rust
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
updating the version from v3 to v4
> chore(ci): fix CI from failing by updating actions versions

- Cargo.toml
I'm chasing down a bug in hive, and noticed that trin doesn't have the latest version of `portal-spec-tests`
On another note, I think we lost a lot of test coverage (at the very least `ethportal-peertest` doesn't seem to be running) with the recent refactor in #1624 ... but I'm still chasing that down and will address it in a future pr. 
- Updated submodule
- Added missing workspace member
> fix: update submodule and missing workspace member

- crates/portalnet/src/find/query_info.rs
- crates/portalnet/src/overlay/service.rs
- crates/subnetworks/beacon/src/jsonrpc.rs
- crates/subnetworks/history/src/jsonrpc.rs
- crates/subnetworks/state/src/jsonrpc.rs
Fixes #1329 
This feature is needed to more efficiently perform beacon sync inside hive tests.
- Perform local store content lookup at `OverlayService` level rather than at `JsonRpc` level.
> refactor: perform local db content lookup at OverlayService level

- Cargo.lock
- Cargo.toml
- bin/portal-bridge/src/cli.rs
- crates/ethportal-api/Cargo.toml
- crates/ethportal-api/src/types/enr.rs
- crates/ethportal-api/src/types/portal_wire.rs
- crates/portalnet/src/discovery.rs
- crates/validation/Cargo.toml
We are using a fairly old version of discv5 0.4.1 there has been quote a few improvements
- Automatic Firewall/NAT Detection
- Increase default vote duration to 2 minutes
- Respond to requests from peers with invalid ENRs
- Remove unused event EnrAdded
- Prevent storing non-contactable ENRs
by bumping the version and updating what is required
sigp/discv5 had a regression when updating from 0.4.1 to 0.5.0 when upgrading from parity rlp to alloy_rlp. I made a fix here, https://github.com/sigp/discv5/pull/276 I have set the cargo.toml to point to my PR for now, we can update to a release when it is merge in. These improvements seem pretty big so I think they are worth getting in
> chore: bump discv5 to 0.9 includes NAT fixes + other improvements

- Cargo.lock
- crates/ethportal-api/Cargo.toml
- crates/ethportal-api/build.rs
- crates/ethportal-api/src/version.rs
There was a bug in https://github.com/ethereum/trin/pull/1615 which caused https://github.com/ethereum/trin/actions/runs/12834319209/job/35791388762 release ci to fail, on trying to build.
I removed const_format cause it wasn't needed and also fixed some indexing
I tested on my forked github repo and it works
release: https://github.com/KolbyML/trin/releases
release branch: https://github.com/KolbyML/trin/tree/fix-cross-build
ci working: https://github.com/KolbyML/trin/actions/runs/12835484962/job/35796339052
I tested the binary built locally
and the short commit matches
> fix: cross build ci required for releases + remove const_format

- crates/metrics/src/overlay.rs
- crates/portalnet/src/lib.rs
- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/overlay/request.rs
- crates/portalnet/src/overlay/service.rs
- crates/portalnet/src/put_content.rs
- crates/portalnet/src/utp/controller.rs
- crates/portalnet/src/utp/mod.rs
- crates/portalnet/src/utp/timed_semaphore.rs
For the most part we have no idea into how uTP is performing, are things working right? Idk lets add some metrics
add a timer attached to the semaphore. This metric won't include uTP transfers initiated over json-rpc, but I am not really concerned with the uTP transfers over json-rpc
> feat: add uTP duration metrics

- bin/trin-execution/src/evm/block_executor.rs
- docker/Dockerfile.bridge
Milos noticed that the 1M state bridges weren't running after the refactor
Stop reading the genesis file and use `include_str!` I am using this upstream for trin-execution and it is also common practice in reth for the genesis file.
Just to point out we can't use a const I believe, `include_str` errored saying we must use a string literal
> fix: docker portal-bridge can't find genesis.json

- crates/rpc/src/eth_rpc.rs
- crates/rpc/src/evm_state.rs
We can't execute transaction post EIP-1559 without setting gas price. And gas price has to be at least base fee.
If unset, set the gas price to base fee.
Also added `debug` logging for easier debugging eth_call requests.
> fix: set gas_price when handling eth_call

- Cargo.lock
- Cargo.toml
our depend ci updated crunchy and the latest release breaks cross building the windows binary https://github.com/eira-fransham/crunchy/issues/13
temporarily pin crunchy to a working version
> fix: temporarily pin crunchy

- Cargo.lock
- Cargo.toml
fixes https://github.com/ethereum/trin/issues/1642
switch it back now that the fix is merged and published in a release
> chore: switch discv5 to pull from crates.io again

- crates/ethportal-api/src/types/enr.rs
`generate_random_remote_enr` was generating Multicast ips, we use `generate_random_remote_enr()` in Hive tests and most clients don't allow Multicast IP's to be used
Only generate IP's before the Multicast range and after 0.0.0.0
> fix: stop `generate_random_remote_enr` from generating multicast ip's

- crates/ethportal-api/src/types/ping_extensions/extensions/type_65535.rs
The default derived Debug implementation printed the message as bytes
Implement Debug manually to decode the Ping Message, there is no point in decoding it unless we print it so I think this strikes a pretty good balance.
> feat: implement Debug for PingError so messages display

- book/src/developers/contributing/releases/deployment.md
In todays Trin meeting it was agreed to take State nodes out of the standard release process for the time being.
The reason for this is the State Network is not ready for production and being able to iterate quicker should help us launch quicker as we will know if there is an issue quick and hence fix them quicker
Comment out the state network code, if someone wants I can remove it, but I thought to keep it as one day the state nodes will join the standard deployment process again
> chore: remove state nodes from standard release process

- bin/trin/src/cli.rs
- bin/trin/src/lib.rs
- crates/storage/src/config.rs
- crates/storage/src/test_utils.rs
- crates/storage/src/versioned/id_indexed_v1/config.rs
- crates/storage/src/versioned/id_indexed_v1/pruning_strategy.rs
- crates/storage/src/versioned/id_indexed_v1/store.rs
- crates/utils/src/cli.rs
- testing/ethportal-peertest/src/lib.rs
- testing/ethportal-peertest/src/scenarios/put_content.rs
- testing/ethportal-peertest/tests/rpc_server.rs
- testing/ethportal-peertest/tests/self_peertest.rs
For a larger description of the problem can be viewed here https://github.com/ethereum/trin/issues/1574
The TL:DR is currently we start at 100 percent radius when the node will end up at 1-3%. This means we download and purge content our node won't end up storing which wastes a lot of CPU cycles, but also takes our uTP transfer limit which could be used for content within our final 1-3% final radius.
This is a big issue as on the state network, currently we are trying to bridge latest state, but our nodes uTP limit is always full so often `trin-execution` offer's of state diffs are declined as all State nodes are at transfer capacity.
^ here is a picture I took awhile ago, at the bottom you can see we successfully offered to 0 peers and the content was declined 8 times. This is due to the …
> feat: add max-radius param with 5% default

- Cargo.lock
- Cargo.toml
- crates/portalnet/src/discovery.rs
- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/overlay/service/manager.rs
- crates/portalnet/src/utp/controller.rs
- crates/subnetworks/beacon/src/lib.rs
- crates/subnetworks/beacon/src/network.rs
- crates/subnetworks/history/src/lib.rs
- crates/subnetworks/history/src/network.rs
- crates/subnetworks/state/src/lib.rs
- crates/subnetworks/state/src/network.rs
- testing/utp/src/lib.rs
It's possible for wrong Enr to be passed to utp library if it was changed recently.
See #1596 for more details.
The utp-rs library is updated (see https://github.com/ethereum/utp/pull/136) so only peer id (NodeId) is required when receiving the utp packet, while entire peer (Enr) is passed when calling `accept_with_cid`.
The biggest change is in `crates/portalnet/src/discovery.rs`, where we now call `find_enr` only if Enr is unknown when we have to send them packet (which should rarely happen), instead of every time we receive packet.
Worth highlighting that due to the nature of #1596, we can't easily verify that this actually fixes it until it's deployed to the servers. I did some manual testing and I'm confident that this should fix it (but I plan to verify once this is merged and …
> feat: update utp-rs dependency

- crates/storage/src/sql.rs
- crates/storage/src/utils.rs
I ran https://github.com/ethereum/trin/pull/1660 without profiling
Before using WAL
`INFO trin_bench: Finished gossiping blocks in 16m 11s, with 270336 offers`
After enabling WAL
`INFO trin_bench: Finished gossiping blocks in 11m 40s, with 270336 offers`
I am testing with era1 files 1000 to 1010
So after enabling WAL the benchmark finish 1.39 times faster or enabling WAL resulted in approximately a 27.91% reduction in time
> feat: enable WAL mode on sqlite 1.39-1.9xing Trin performance

- Cargo.lock
- Cargo.toml
tempfile 3.16.0 uses getrandom 3 which is a breaking change, which was breaking our deployment script
fix tempfile to 3.15
> chore: fix tempfile and uuid version due to including breaking change in getrandom

- Cargo.lock
- Cargo.toml
Windows build is failing: https://github.com/ethereum/trin/actions/runs/13189513029/job/36819458339
Pin crunchy for all dependencies
> chore: pin crunchy for Windows compatibility

- crates/ethportal-api/src/types/portal.rs
The `ethportal_api::types::portal::Distance` type is not used.
My auto complete confuses it frequently with `ethportal_api::types::distance::Distance` (the actual type that we use).
Removed the type.
> refactor: remove unused Distance type

- Cargo.lock
- Cargo.toml
- bin/trin-execution/src/engine/rpc.rs
- crates/ethportal-api/src/types/execution/header.rs
- crates/rpc/src/eth_rpc.rs
- testing/ethportal-peertest/tests/rpc_server.rs
We are using an old version of alloy 0.4.1 and I need to use newer features for my followup PR's
bumping the version and updating the code as needed to comply with the changes
> chore: bump alloy to 0.11.1

- .github/workflows/ci.yml
Recently, cross was not working because of a dependency conflict. See #1670 
We only found out at the moment of release, which caused a bunch of downstream issues. For example:
- Either way that you try to trigger the follow-up release will cause
the Release Draft to be missing all the real changes (Tried repushing
the tag, and skipping the version into the next one)
- There's no other good way to test if whatever was broken the first
time is fixed. You don't want to test your change by pushing to
master.
- It makes a messy list of commits on master.
This change tests cross compiles at every PR, to reduce the chances of a similar issue happening again.
~I don't know a good way to test this locally. Any suggestions besides merging and finding out?~ Ah, great, it runs immediately in this …
> chore: add cross-compile checks to every PR

- Cargo.lock
- crates/light-client/Cargo.toml
- crates/light-client/src/consensus/consensus_client.rs
- crates/light-client/src/consensus/utils.rs
- crates/light-client/src/lib.rs
- crates/light-client/src/types.rs
- crates/light-client/src/utils.rs
FIxes #1417 
light-client crate used ssz-rs crate for SSZ handling instead of ethereum-ssz crate
This PR removes the ssz-rs dependency and uses ethereum-ssz instead 
> chore: remove ssz_rs dependency

- crates/storage/src/versioned/id_indexed_v1/pruning_strategy.rs
- crates/storage/src/versioned/id_indexed_v1/store.rs
- crates/storage/src/versioned/usage_stats.rs
We underestimate the disk usage. See #1653 for details.
Based on the analysis in #1653, I added fixed number of bytes per content item that should be used when estimating disk usage (together with already counted number of bytes for content_id, content_key and content_value).
This way, the data that is actually store in the db (`content_size = content_id.len() + content_key.len() + content_value.len()`) doesn't have to change and we can easily update our estimate in the future if we need to.
I had local trin client that was running for some time (~20h) last week. Storage was configured to use 1GB of data, and all 3 subnetworks are enabled (state and history had 500MB capacity each). The actual size of the DB was 1447 MB (45% than desired).
Starting trin client with this PR would trigger …
> feat: improve estimated disk usage

- Cargo.lock
- crates/storage/src/versioned/id_indexed_v1/store.rs
- crates/storage/src/versioned/mod.rs
- crates/subnetworks/history/Cargo.toml
- crates/subnetworks/history/src/lib.rs
- crates/subnetworks/history/src/storage_migration.rs
We need logic for history content migration. See #1666 for details.
Created new `ContentType`s that will be used for new content types.
This way, we can use the same implementation of content store, because new type will correspond to the new sql table.
This also makes the migration simple: we have to delete content from original table, and either discard or insert into new table.
The migration function is not used at the moment, so this PR can be merged as is.
The followup work, that can be done either as part of this PR or as a followup PR (depending on the review status of this PR and when I finish it):
- Add tests for migration
- Add migration metrics/stats that can be printed periodically
- Decide what we do regarding post-merge bodies and receipts
> feat: create fn for history content migration

- .github/workflows/dependencies.yml
Currently every time our CI dependencies bot runs it commits under a user account, instead of github actions bot.
This PR and commit isn't being made by a user, it is being made by github actions bot account, so we probably shouldn't be comitting it under a user's account
I tested this locally on my fork https://github.com/KolbyML/trin/pull/5
Now it commits the update dependencies commit under the bots account
> fix(ci): make dependencies update bot commit under github-actions account instead of users

- crates/storage/src/sql.rs
- crates/subnetworks/beacon/src/network.rs
- crates/subnetworks/beacon/src/storage.rs
The beacon node keeps all the light client bootstrap data in the DB, but we want to serve and retain only bootstraps that are within the weak subjectivity period ~= 4 months old.
Add a pruning task for light client bootstrap data that runs on every start, and once a day when the client is running.
> feat(beacon): enable pruning for outdated light client bootstrap data

- Cargo.lock
- crates/ethportal-api/Cargo.toml
Bump `ethportal-api` version as part of the release process.
> chore: bump ethportal-api version to v0.4.2

- Cargo.lock
- crates/ethportal-api/Cargo.toml
Bump ethportal-api version as part of the release process.
> chore: bump ethportal-api version to v0.5.0

- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/overlay/service/manager.rs
- crates/portalnet/src/overlay/service/mod.rs
- crates/portalnet/tests/overlay.rs
- crates/subnetworks/beacon/src/jsonrpc.rs
- crates/subnetworks/beacon/src/lib.rs
- crates/subnetworks/beacon/src/network.rs
- crates/subnetworks/history/src/jsonrpc.rs
- crates/subnetworks/history/src/lib.rs
- crates/subnetworks/history/src/network.rs
- crates/subnetworks/state/src/jsonrpc.rs
- crates/subnetworks/state/src/lib.rs
- crates/subnetworks/state/src/network.rs
Currently the performance of Trin is very poor as in we can only handle around 2-5 Megabits per second. This is insanely low, inorder to get the state network live we need to massively increase performance of Trin hopefully by at least 10-100x more ideally. Ideally Trin can saturate a computers network card. To put 2-5 megabits into prospective that isn't even 1 megabyte per a second, Trin is insanely slow, and due to this slowness Trin has a high error rate, especially under under small load. Last I checked only 90% of Trin Execution state diff bridges made it onto the network. The state is massive, having an error rate that high makes it hard to have a reliable network.
In short
- trin performance is bad
- trin performance isn't good enough to onboard users, the network would die under …
> perf: switch store from RwLock to Mutex 1.74x performance increase ~98.8% error rate decrease

- .github/workflows/monthly_block_root_update.yml
We must regularly update the trusted block root embedded into Trin to keep it within the weak subjectivity period.
Add GitHub action that gets the latest finalized block root and auto opens a PR updating the trusted block root file.
This workflow runs on the 1st of every month.
This action has been tested, and this is the example [PR](https://github.com/ethereum/trin/pull/1696) that will be open every month.
> chore: add github action to monthly update trusted block root

- crates/ethportal-api/src/types/ping_extensions/decode.rs
- crates/portalnet/src/overlay/service/ping/mod.rs
We have `process_ping` in the `process_pong` function log, also it is a little hard to debug decode failures if the hex isn't included
fixed the error message and added the hex(payload) if decode fails
> chore: improve ping extension decode errors

- README.md
- the readme says unix only, but this is no longer true (we want it to work with windows and would gladly take issues now)
- I think the experimental messaging is out dated now and counter productive. We expect people Trin is ready to use, but then the readme tells me to not use it, it is counter productive
Removing the 2 issues from the readme.
Programs change overtime for example sigp/discv5 and ethereum/go-ethereum change over time but don't have this kind of messaging in the readme.
If we verbally say we are ready for other's to take us seriously, I think messaging and this PR is the first step.
Same goes for window's support
> chore: experimental messaging from readme

- book/src/developers/contributing/releases/deployment.md
- book/src/developers/contributing/releases/release_checklist.md
- book/src/developers/contributing/rotation/index.md
Frankly, I don't know what changed since --no-verify was required. It works without the flag now, so we should definitely not use it. Verification seems good.
> docs: release ethportal using verification

- docker/docker-compose.yml
the environment variable section is now be declared according to array syntax described in [docker docs](https://docs.docker.com/reference/compose-file/services/#environment).
the orginal declaration
```yaml
environment:
- RUST_LOG: info
```
is giving this syntax error
```bash
➜  docker compose up
services.trin.environment.[0]: unexpected type map[string]interface {}
```
> chore: update docker compose environment variable syntax

- crates/storage/src/versioned/id_indexed_v1/store.rs
- crates/storage/src/versioned/mod.rs
- crates/storage/src/versioned/utils.rs
The old history content type (`ContentType::History`) used for storage is no longer needed.
Instead, we should use either `ContentType::HistoryEternal` or `ContentType::HistoryEphemeral`.
Removed no longer used type.
> feat: remove old store ContentType::History

- crates/e2store/src/e2ss.rs
- crates/e2store/src/e2store/memory.rs
- crates/e2store/src/e2store/types.rs
- crates/e2store/src/entry_types.rs
- crates/e2store/src/era.rs
- crates/e2store/src/era1.rs
- crates/e2store/src/lib.rs
- crates/e2store/src/types.rs
I am creating a repo to formalize all of the e2store formats and to avoid duplicate types with @arnetheduck and @advaita-saha https://github.com/eth-clients/e2store-format-specs
Anyways currently we are reading the type as little endian which doesn't make sense.
For example the type for the `VersionEntry` is a vector [65, 32] which in ascii is `e2`, but we are reading it backwards as `2e`.
Our code is ends up working to the same result, but it is fairly unidle as we also have 0x3265 in our documentation when it should be 0x6532 or [65, 32]
use be and update numbers.
> refactor: read e2store header type as big endian

- crates/storage/src/versioned/ephemeral_v1/config.rs
- crates/storage/src/versioned/ephemeral_v1/mod.rs
- crates/storage/src/versioned/ephemeral_v1/sql.rs
- crates/storage/src/versioned/ephemeral_v1/store.rs
- crates/storage/src/versioned/mod.rs
We need storage for the ephemeral headers, bodies, and receipts.
This is the first iteration of the ephemeral storage implementation. 
I will add a pruning strategy and some updates in a separate PR.
> feat: add ephemeral store

- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/writer.rs
- crates/e2store/src/e2hs.rs
- crates/e2store/src/e2ss.rs
- crates/e2store/src/e2store/stream.rs
- crates/e2store/src/e2store/types.rs
- crates/e2store/src/era.rs
- crates/e2store/src/era1.rs
- crates/e2store/src/types.rs
Addressed some remaining comments from #1727 related to ownership patterns we use in `e2store`
- removed some clones & updated ownership in conversion traits
> refactor: ownership/from traits in e2store

- Cargo.lock
- Cargo.toml
Fix #1610
By pulling in the uTP version with the fix
> chore: upgrade utp-rs to v0.1.0-alpha.17

- crates/portalnet/src/overlay/service/manager.rs
The Samba team has spent days trying to debug why there `put_content` implementation isn't working, Trin wasn't printing any logs so they had no way to tell why Trin was failing to accept their offer
If these functions return error's print them on the debug log
> refactor: print debug logs for silent errors in `handle_offer()`

- bin/e2hs-writer/src/writer.rs
The [spec](https://github.com/eth-clients/e2store-format-specs/pull/6) for `e2hs` was just updated to to use the final block header hash in a file (as opposed to the first) to be used in the file path. 
- updated the `e2hs-writer`
> fix: update short hash used in e2hs file path

- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/writer.rs
- bin/portal-bridge/README.md
- bin/portal-bridge/src/bridge/e2hs.rs
- bin/portal-bridge/src/bridge/era1.rs
- bin/portal-bridge/src/bridge/mod.rs
- bin/portal-bridge/src/cli.rs
- bin/portal-bridge/src/main.rs
- bin/portal-bridge/src/types/mod.rs
- bin/portal-bridge/src/types/mode.rs
- bin/portal-bridge/src/types/range.rs
With the introduction of the new [e2hs](https://github.com/eth-clients/e2store-format-specs/pull/6) file format, we need a bridge mode to support these files.
This is a very basic bridge mode, that won't really work unless you have all necessary `e2hs` files in a local `test-e2hs` dir, inside the root level of the trin dir. But the intention is that this will be updated to use a centralized server that hosts all `e2hs` files, once they are generated and made available. 
The existing `BridgeMode` type has turned into a bit of a frankenstein, as a result of us trying to push too much into a single cli arg. After this new bridge mode matures, I expect a fair amount of legacy bridge code to be deleted, that's why I decided to create new, isolated cli args for the `e2hs` mode to use, rather …
> feature: add e2hs mode to portal-bridge

- Cargo.lock
- crates/e2store/Cargo.toml
- crates/ethportal-api/Cargo.toml
Glados needs a release of `ethportal-api`. Since there was a breaking change we are bumping the minor release
bumping `ethportal-api` and `e2store` crates
> chore: bump ethportal-api & e2store minor version

- bin/trin/src/cli.rs
- bin/trin/src/lib.rs
- crates/portalnet/src/config.rs
- crates/portalnet/src/discovery.rs
- crates/portalnet/src/overlay/service/manager.rs
- crates/portalnet/tests/overlay.rs
- testing/utp/src/lib.rs
Discv5 uses an timed LRU cache for all of its sessions. In the past we had bugs where a discv5 session was established, we would try and send a message to the node but it wouldn't be in our ENR cache. From talking to Milos on our call today. The `Discv5.session_capacity` should be less than or equal to our `NodeAddrCache` capacity, to prevent this bug.
- I manually set `session_cache_capacity()` well initializing Discv5, to ensure both of our caches use the same value. I also added a comment for context why we are doing this.
- I updated the `NODE_ADDR_CACHE_CAPACITY` const from 512 Enr's to 1000, to be consistent with Discv5's session capacity default, if we want to save RAM I think it is fine to leave it at 512, but I think matching Discv5's default is a better story then, `32 full …
> fix: ensure our ENR cache has enough room for max sessions

- Cargo.lock
- crates/light-client/src/client.rs
- crates/light-client/src/rpc.rs
Clippy check fails on the automatic weekly cargo update action: https://github.com/ethereum/trin/pull/1737
- Run `cargo update` manually
- Fix clippy warnings
> chore: fix clippy warnings on cargo update

- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/overlay/service/find_content.rs
- crates/portalnet/src/overlay/service/find_nodes.rs
- crates/portalnet/src/overlay/service/manager.rs
- crates/portalnet/src/overlay/service/mod.rs
- crates/portalnet/src/overlay/service/offer.rs
- crates/portalnet/src/overlay/service/utils.rs
- crates/portalnet/src/utils/portal_wire.rs
- crates/portalnet/src/utp/controller.rs
our OverlayService code in `manager.rs` is massive and feels unorganized and is a little hard to go through. I was talking to @morph-dev a month ago and he said he would prefer large refactors like this should be in a separate PR from PR's trying to make logic changes.
I was implementing https://github.com/ethereum/portal-network-specs/pull/383 I wanted to refactor the calls for `find_content` like I did when I refactored the `ping` functions out of `manager.rs` when I implemented `ping extensions`.
I am now doing it for the 3 other content messages I didn't refactor out, since `manager.rs` is super big and it is hard to look through when I am trying to search through the functions for a specific message domain e.x.
- ping
- offer
- find content
- find node
Move the functions which belong …
> refactor: move out offer/find_content/find_nodes functions from manager.rs

- crates/ethportal-api/src/types/mod.rs
- crates/ethportal-api/src/types/portal_wire.rs
- crates/ethportal-api/src/types/protocol_versions.rs
- crates/portalnet/src/discovery.rs
We don't support Protocol versioning https://github.com/ethereum/portal-network-specs/pull/379
By implementing the specification change. Currently Trin on Mainnet is only set to support `v0`. I set Angelfood to `v0, v1` just because, no body uses AngelFood, but this allows us to easily test changes for V1 in Hive potentially. In the future we could probably just pass a custom `NetworkSpec` through the CLI for testing this kind of stuff in hive
`v1` should be added to the `NetworkSpec.supported_protocol_versions` once we support it and want to enable it on the network.
This PR doesn't implement the `V1`
`V1` will be 2 changes
- https://github.com/ethereum/trin/pull/1720 I will rebase this PR and modify it to exist in the `Protocol Versions` context
- …
> feat: add Protocol Version support

- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/overlay/service/find_content.rs
- crates/portalnet/src/overlay/service/offer.rs
- crates/portalnet/src/utils/portal_wire.rs
- testing/ethportal-peertest/tests/self_peertest.rs
We don't support portal wire version 1 yet. This PR implements https://github.com/ethereum/portal-network-specs/pull/383 the new varint encoding on find_content uTP transfers
Implementing it.
I also ended up setting some ethportal-peertests to test it as well, by making them run under angelfood which has v1 enabled already
> feat: implement protocol version 1 findcontent utp varint encoding

- Cargo.lock
- crates/ethportal-api/Cargo.toml
ethportal-api needs a version bump for release
> chore: bump ethportal-api version

- crates/ethportal-api/src/types/portal.rs
- crates/subnetworks/beacon/src/jsonrpc.rs
- crates/subnetworks/history/src/jsonrpc.rs
- crates/subnetworks/state/src/jsonrpc.rs
- testing/ethportal-peertest/src/scenarios/offer_accept.rs
This problem was reported by both Shisui and fluffy today https://discordapp.com/channels/890617081744220180/1115672797046394890/1360071808966987806
Basically the spec
specifies offer to just return a hex string, but we are instead returning ``{ "content_keys": hex_string }``
This bug has been present for over 2 years at least. But it wasn't detected due to us not handling the Offers result in hive well testing till today, where I decided to handle the result.
converting
```rust
/// Response for Offer endpoint
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AcceptInfo {
#[serde(with = "accept_code_hex")]
pub content_keys: AcceptCodeList,
}
```
to 
```rust
pub struct AcceptInfo(#[serde(with = "accept_code_hex")] pub AcceptCodeList); …
```
> fix: offer JsonRPC result was using wrong format for last 2 years

- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/reader.rs
- crates/e2store/src/e2hs.rs
- crates/e2store/src/era1.rs
We where deserializing the Era1 file every time for every block retrieved from the Era1 file. So we were deserializing the Era1 file 8192 times. 
Before time: 8m27.011s
After my fix: 0m11.451s
^ these results came from generating E2HS file 1655
I removed `get_tuple_by_index()` as the function is just not good and encourages bad patterns. Instead of using `get_tuple_by_index` I decoded the Era1 file once, then parsed the `block_tuple` out when needed
> perf: make e2hs writer 44x faster for generating E2HS files from Era1 files

- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/writer.rs
When I tried to generate E2HS 1896 which is the E2HS file which includes the merge boundary. So we use both ERA and ERA1 files in generating this E2HS file unlike all the other files. But when I attempted to build E2HS file 1896 it failed. This was due to E2HS 1896 requiring access to ERA1 1896 and ERA 574&575 to get all the blocks required to build E2HS 1896.
I made it so the provider code could optionally download a 3rd Era file, only if e2hs-writer is building the E2hs file 1896
> fix: e2hs-writer can't generate merge transition e2hs file

- Cargo.lock
- bin/e2hs-writer/Cargo.toml
- bin/e2hs-writer/src/main.rs
- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/utils.rs
- bin/e2hs-writer/src/writer.rs
- bin/portal-bridge/src/api/execution.rs
- bin/portal-bridge/src/bridge/history.rs
When I was testing generating post-merge E2HS files it was extremely slow taking 60+ minutes. My first thought was it was so slow because for every block we would call the Ethereum JSON-RPC to fetch the receipts. And after trying my fix in this PR I was right.
- I implemented batch downloading for receipts while initializing the e2hs-reader instead of fetching the receipts on demand which was very slow
- downloading ERA files are super slow so I made it so `downloading the era files` and `downloading the receipts` are done in parallel and it saved around 2 minutes from my testing.
So my initial run on master took
60+ minutes and I was using the JSON-RPC provider `https://geth-lighthouse.mainnet.eu1.ethpandaops.io/ `
I then tested a bunch of different EL's and regions to see which one …
> perf: make e2hs writer 6.35x faster for processing Era files

- bin/portal-bridge/README.md
- bin/portal-bridge/src/bridge/e2hs.rs
- bin/portal-bridge/src/main.rs
- bin/trin-execution/src/era/binary_search.rs
- bin/trin-execution/src/era/manager.rs
- bin/trin-execution/src/era/utils.rs
- bin/trin-execution/src/execution.rs
- crates/e2store/src/e2hs.rs
- crates/e2store/src/era.rs
- crates/e2store/src/era1.rs
- crates/e2store/src/utils.rs
- testing/ethportal-peertest/src/scenarios/offer_accept.rs
We didn't have an HTTP endpoint hosting E2HS files so we temporarily used a local directory system
By using `https://e2hs.ethportal.net/` in the same way we used to use `https://era1.ethportal.net/` for our ERA1 bridge. Currently `https://e2hs.ethportal.net/` is broken because all of the links point to the index page, but that should be fixed tomorrow. The PR itself is good to go
> feat: make E2HS bridge fetch from http endpoint, instead of using local directory

- crates/ethportal-api/src/beacon.rs
- crates/ethportal-api/src/history.rs
- crates/ethportal-api/src/state.rs
- crates/ethportal-api/src/types/jsonrpc/endpoints.rs
- crates/ethportal-api/src/types/portal.rs
- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/put_content.rs
- crates/rpc/src/beacon_rpc.rs
- crates/rpc/src/history_rpc.rs
- crates/rpc/src/state_rpc.rs
- crates/subnetworks/beacon/src/jsonrpc.rs
- crates/subnetworks/history/src/jsonrpc.rs
- crates/subnetworks/state/src/jsonrpc.rs
- testing/ethportal-peertest/src/scenarios/put_content.rs
- testing/ethportal-peertest/tests/self_peertest.rs
This PR should be reviewed first https://github.com/ethereum/trin/pull/1760
`TracePutContent` or originally `TraceGossip` was an endpoint created so that we could build better bridges. In terms of knowing what happened and rate limiting the bridge. It was a time when we were still trying to reach 100% on Glados. `TracePutContent` was superseded by `TraceOffer` which ended up being the superior solution to our original effort.
I removed it
> refactor: remove `TracePutContent` json-rpc endpoint

- bin/e2hs-writer/src/cli.rs
- bin/e2hs-writer/src/main.rs
- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/writer.rs
- bin/portal-bridge/src/api/execution.rs
- bin/portal-bridge/src/bridge/e2hs.rs
- bin/trin-execution/src/era/binary_search.rs
- bin/trin-execution/src/era/manager.rs
- bin/trin-execution/src/era/utils.rs
- bin/trin-execution/src/execution.rs
- crates/e2store/src/e2hs.rs
- crates/e2store/src/era.rs
- crates/e2store/src/era1.rs
My computer is freezing because my computer is running out of memory. I have seen instances where `e2hs-writer` would use over 35GB's of ram.
- Reducing the memory usage caused by downloading receipts. I think there used to be a memory leak as well, which I fixed.
- Reducing the memory usage caused by downloading Era files, we were doing a lot of redownloading&re-deserialization as well, which was slowing things down. I think there was a memory leak here as well as for some reason memory wasn't being cleared when large structures went out of scope.
- I changed the batch_limit to 10 as I was getting rate limited on generating quite a few e2hs files. I tried 20/30 and it didn't work, we can work on a more specification solution in the future, but this is good enough for the time being.
- …
> feat: reduce e2hs-writer memory usage by 5.48x for era to e2hs files

- bin/portal-bridge/src/bridge/e2hs.rs
- crates/ethportal-api/src/types/content_key/history.rs
- crates/ethportal-api/src/types/content_value/history.rs
- crates/ethportal-api/src/types/execution/ephermeral_header.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
- crates/ethportal-api/src/types/execution/mod.rs
- crates/ethportal-api/src/types/execution/ssz_header.rs
- crates/subnetworks/history/src/validation.rs
We don't implement the Ephemeral Header Content Types https://github.com/ethereum/portal-network-specs/pull/387
Implementing them and adding tests https://github.com/ethereum/portal-network-specs/pull/390
> feat: implement Ephemeral Header Content Types

- Cargo.lock
- crates/e2store/Cargo.toml
- crates/e2store/src/utils.rs
`https://e2hs.ethportal.net/` doesn't work it was broken and I could download any files
Devops removed the redirect role and now we need to use this url `https://e2hs.ethportal.net/index.html`, I tried to download a file and it download a file now
> fix: update E2HS URL to fixed one by devops

- .github/workflows/monthly_block_root_update.yml
A PR was made on portal-network-specs saying that `Artifact Actions v3 will be deprecated by January 30, 2025` https://github.com/ethereum/portal-network-specs/pull/392 all of our CI's are using v4 of checkout except this one
I did this for other CI's in the past context can be found here https://github.com/ethereum/trin/pull/1628
bump it
> chore(ci): bump deprecated actions/checkout version

- bin/portal-bridge/src/census/mod.rs
- bin/portal-bridge/src/cli.rs
- testing/ethportal-peertest/src/scenarios/bridge.rs
Today in the call I said I would add the granular offer code I wrote for the StateBridge to the E2HS bridge, but after thinking about that I think that would be completely overkill, expessially when the History Network has 100-1000x less content for us to offer.
- Census code was originally added with a offer limit of 8 https://github.com/ethereum/trin/pull/1422
- Offer limit lowered to 4 https://github.com/ethereum/trin/pull/1490
- Offer limit lowered to 2 https://github.com/ethereum/trin/pull/1597
Because long term the state bridge won't be apart of `portal-bridge` and I am already running the 4 E2HS bridges I am running with `--enr-offer-limit=8` with good results. I think just increasing the default is good enough for the E2HS bridge
changed the default limit from 2 to 8. It isn't …
> feat: change EnrOfferLimit from 2 to 8

- bin/trin/src/cli.rs
- bin/trin/src/lib.rs
- crates/subnetworks/history/src/lib.rs
- crates/subnetworks/history/src/network.rs
- crates/subnetworks/history/src/storage.rs
- crates/validation/src/header_validator.rs
Our nodes had a flag which was temporarily added called `--disable-history-storage`. This was a temporary step which was supposed to be removed after we upgraded our proof format
remove it
> feat: remove `disable_history_storage`

- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/utils.rs
- bin/trin-execution/src/era/binary_search.rs
- crates/e2store/src/era.rs
- crates/ethportal-api/src/types/consensus/beacon_block.rs
- crates/ethportal-api/src/types/consensus/beacon_state.rs
- crates/ethportal-api/src/types/consensus/body.rs
- crates/ethportal-api/src/types/consensus/constants.rs
- crates/ethportal-api/src/types/consensus/execution_payload.rs
- crates/ethportal-api/src/types/consensus/mod.rs
- crates/ethportal-api/src/types/consensus/proof.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
- testing/ef-tests/tests/build_proofs.rs
This is first PR that simplifies existing logic before I start adding changes from: #1779
The code for generating historical_roots and historical_summaries proof  is duplicated in a few places.
Some of the utility functions could also be more specific
- simplify proof generation logic in `headers_with_proof` and improve tests a bit
- moved the logic for generating `execution_block_proof` into `BeaconBlock`
- removed similar, no longer needed, logic from `BlockBody`
- removed block generation logic from bin/e2hs-writer/src/reader.rs (it was identical with the one in headers_with_proof)
- also removed the tests, because they were also identical
- added tests for verifying that decoded `HeaderWithProof::proof` matches expected value
- make `build_merkle_proof_for_index` generic
[//]: # (Stay …
> refactor: simplify header proof generation

- bin/e2hs-writer/src/main.rs
- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/writer.rs
- crates/ethportal-api/src/types/execution/block_body.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
- crates/validation/src/header_validator.rs
- testing/ethportal-peertest/src/scenarios/state.rs
This is a followup of #1782 , which ~should be reviewed and merged first~ is now merged.
Next PR will add Deneb types
The `ExecutionBlockProof` format change from List to Vector in https://github.com/ethereum/portal-network-specs/pull/396
- Updated our format and naming to be consistent with spec
- Updated `portal-spec-tests` submodule
- Updated header validation logic (but didn't enable it yet)
I also noticed that several functions in `e2hs-writer` crate are async without a reason so I simplified logic there a bit as well.
> feat: change ExecutionBlockProof from list to vector

- bin/portal-bridge/src/census/scoring.rs
After I implemented AcceptCodes I found we had a bug in our Bridge. We should never offer content to Nodes if we know it outside of their radius, as this is just wasted resources, which for a bridge resources are limited. https://github.com/ethereum/trin/pull/1773
I was just testing the bridge and I noticed it again.
```rust
2025-04-29T05:35:17.146519Z  INFO portal_bridge::bridge::offer_report: Successfully offered to 0/8 peers. Content key: 0x00b60bfc414b961eb745736cd6ee0f8284b0c0c0549bb4ba9c7e68b6bda346f29b. Decline reasons: AlreadyStored:[Trin] | Declined:[Ultralight,Ultralight] | NotWithinRadius:[Unknown(None),Trin,Trin,Unknown(None),Unknown(None)]. Failed: 0.
```
By adding a filter to only include nodes with a weight over 0. `choose_multiple_weighted()` will include peers with 0 …
> fix: stop bridging content to nodes outside their radius

- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/utils.rs
- crates/ethportal-api/src/types/consensus/beacon_block.rs
- crates/ethportal-api/src/types/consensus/beacon_state.rs
- crates/ethportal-api/src/types/consensus/body.rs
- crates/ethportal-api/src/types/consensus/execution_payload.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
- crates/validation/src/header_validator.rs
We don't have Deneb header proof, generation and validation.
I created Deneb header proof type and generation code.
I also added support for it in e2hs binary.
> feat: add Deneb header proof type and generation

- Cargo.lock
- Cargo.toml
- bin/portal-bridge/src/bridge/state.rs
- bin/trin-execution/Cargo.toml
- bin/trin-execution/src/content.rs
- bin/trin-execution/src/era/binary_search.rs
- bin/trin-execution/src/era/types.rs
- bin/trin-execution/src/evm/block_executor.rs
- bin/trin-execution/src/evm/post_block_beneficiaries.rs
- bin/trin-execution/src/evm/pre_block_contracts.rs
- bin/trin-execution/src/execution.rs
- bin/trin-execution/src/storage/error.rs
- bin/trin-execution/src/storage/evm_db.rs
- crates/e2store/src/utils.rs
- crates/ethportal-api/Cargo.toml
- crates/ethportal-api/src/types/accept_code.rs
- crates/evm/src/async_db.rs
- crates/evm/src/lib.rs
- crates/evm/src/spec_id.rs
- crates/evm/src/tx_env_modifier.rs
- crates/rpc/src/eth_rpc.rs
- crates/rpc/src/evm_state.rs
- testing/ethportal-peertest/tests/rpc_server.rs
- We want to avoid importing multiple versions of alloy crates
- I want to use alloy-hardforks a crate which was made 3 months ago, which implements all the Ethereum Fork stuff
- We use a quite old version of alloy and revm, and ssz, all of which is required to be upgraded as they depend on each other
Bumping the versions of
- alloy
- revm
- ssz
- ckzg
I also had to update some code to match the upstream changes
> chore: bump alloy/revm/ssz

- crates/ethportal-api/src/test_utils/mod.rs
- crates/ethportal-api/src/test_utils/types.rs
- crates/ethportal-api/src/types/content_key/state.rs
- crates/ethportal-api/src/types/content_value/beacon.rs
- crates/ethportal-api/src/types/content_value/state.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
- crates/validation/src/header_validator.rs
We were missing test vectors around fork boundaries. These were added to portal-spec-tests in ethereum/portal-spec-tests#49
Updated portal-spec-tests submodule, and simplified/refactored some tests in ehtportal-api crate.
> feat: update portal-spec-tests and refactor reading from test files

- Cargo.lock
- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/reader.rs
- bin/portal-bridge/src/bridge/e2hs.rs
- bin/portal-bridge/src/types/range.rs
- bin/trin/src/run.rs
- crates/subnetworks/history/src/validation.rs
- crates/validation/Cargo.toml
- crates/validation/src/accumulator.rs
- crates/validation/src/constants.rs
- crates/validation/src/header_validator.rs
- crates/validation/src/historical_summaries_provider.rs
- crates/validation/src/lib.rs
- crates/validation/src/oracle.rs
HistoricalSummary HeaderWithProof validation wasn't enabled
Enabled it, the E2HS bridge has no way to verify post-capella HeaderWithProofs as it doesn't have access to a provider and we don't want to give it access to one. So the assumption is the the E2HS bridge is downloading the files from a trusted source.
For this to work, it requires the BeaconNetwork or validation will fail
> feat: enable post-capella HistoricalSummary Header validation

- Cargo.lock
- Cargo.toml
- crates/ethportal-api/Cargo.toml
Bumping:
- ethportal-api version to release breaking changes
- trin version to match release
> chore: bump trin & ethportal-api versions

- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/utils.rs
- crates/ethportal-api/src/types/consensus/beacon_block.rs
- crates/ethportal-api/src/types/consensus/body.rs
- crates/ethportal-api/src/types/consensus/execution_payload.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
This is a followup of #1799
We are missing logic for creating header proof using `BeaconBlockElectra`.
Added function for creating proof.
Note that we don't have any test vectors to verify if this works as intended.
> feat: create header proof using BeaconBlockElectra

- bin/trin/src/cli.rs
- crates/portalnet/src/bootnodes.rs
Our bootnodes are outdated and they contain v0 protocol version.
This would usually not be a problem, but they store beacon content and they are the first one that we contact during light-client sync (because we start light-client syncing before everything else, so they are the only one we know about at that point), and we assume protocol v0 version and fail to decode the content.
Technically, this shouldn't happen even with this setup, as we should get new Enr when discv5 session is established.
I didn't investigate but I suspect that "Request" object still has old Enr and that's what it uses to decode the response.
Updated bootnode Enrs according to glados.
> fix: update bootnodes

- bin/portal-bridge/src/api/consensus/mod.rs
- bin/portal-bridge/src/bridge/beacon.rs
- crates/ethportal-api/src/types/content_value/beacon.rs
This is a followup of https://github.com/ethereum/trin/pull/1801
Beacon Bridge will stop working after Pectra fork.
Update our types to be Pectra instead of Deneb.
NOTE: We don't have a way to test these endpoints until the fork, as they would fail (except in some cases when format didn't change).
Ideally, we should be able to decode/deserialize correct version and it's something I will work on. But I don't have time to do it until the fork.
This code can/should be deployed as soon as the fork happens on mainnet.
> feat: make beacon bridge use Electra variants

- bin/e2hs-writer/src/main.rs
- bin/e2hs-writer/src/provider.rs
- bin/e2hs-writer/src/reader.rs
- bin/e2hs-writer/src/writer.rs
Building E2HS files is time consuming. There isn't a good way for the bridge to validate post-capella headers due to the E2HS bridge not having access to a provider. We want to know sooner then later if a E2HS file is valid or not.
Validate the block, use the latest HistoricalSummaries if avaliable, if HistoricalSummaries aren't avaliable there are no post capella headers to prove so there is no issue.
> feat: validate blocks while building E2HS file

- crates/light-client/src/config/networks.rs
- crates/light-client/src/consensus/consensus_client.rs
The light-client only uses `network_spec()` for calculating slot's timestamp.
Since it already has its own config and which uses for most calculations, it should use it for this as well.
Added `slot_timestamp` function in light-client.
Also added Sepolia testnet configuration, which I used to test this (I left it as others might fine it useful as well).
> feat: light-client should use its config for slot_timestamp

- .circleci/config.yml
- docker/Dockerfile.trin-execution
This PR replaces https://github.com/ethereum/trin/pull/1586
- I want to be able to deploy Trin Execution with docker to our infrastructure 
- I want to test Trin Execution using Hive, which requires a docker image
By adding a docker image for Trin Execution and the respective CI code
> feat: add docker image for trin-execution

- bin/portal-bridge/README.md
- bin/portal-bridge/src/bridge/e2hs.rs
- bin/portal-bridge/src/cli.rs
I am setting up E2HS bridges but a problem that occurs is there are always new e2hs files being added. We want to deploy bridges which cover ranges of the block space so for example if I have 5 bridges
And the total block range is roughly 0 to 21 million
- 0 to 5_000_000
- 5_000_001 to 10_000_000
- 10_000_001 to 15_000_00
- 15_000_001 to 20_000_00
- 20_000_001 to latest
^ I would probably want to deploy the bridges something like this where. Everytime the 5th bridge does a cycle it checks what is the latest E2HS file I can gossip, then includes that moving window in its range.
adding a latest option which can be specified as the end of the range.
At the initialization of the bridge check what is the latest E2HS file we can bridge
> feat: add latest end of block range option for e2hs bridge

- Cargo.lock
- Cargo.toml
- crates/ethportal-api/Cargo.toml
Update crates version as preparation for upcoming release.
> chore: bump trin (0.3.1) & ethportal-api versions (0.10.1)

- .circleci/config.yml
The recently updated circleci config to build and publish docker images is not triggering on tag.
This is not something that I was able to test, but I'm pretty confident that this will solve the problem.
Now I only use `<< pipeline.git.tag >>` as a `when` config for a `docker-master-tag` workflow.
I also removed the duplication of invoking all jobs manually, and I'm using [matrix jobs](https://circleci.com/docs/configuration-reference/#matrix).
> ci: fix workflow triggering on tag + matrix parameters

- .circleci/config.yml
The naming of the jobs across workflows wasn't very consistent and nice.
Renamed jobs so it's clear what is their trigger.
> ci: fix job names across workflows

- bin/e2hs-writer/src/subcommands/head_generator/e2hs_builder.rs
- bin/e2hs-writer/src/subcommands/head_generator/ethereum_api.rs
- bin/e2hs-writer/src/subcommands/head_generator/mod.rs
- bin/e2hs-writer/src/subcommands/single_generator/provider.rs
- bin/portal-bridge/src/bridge/beacon.rs
- bin/portal-bridge/src/types/range.rs
- bin/trin-execution/src/era/binary_search.rs
- crates/e2store/src/era.rs
- crates/ethportal-api/src/types/consensus/constants.rs
- crates/ethportal-api/src/types/consensus/historical_summaries.rs
- crates/ethportal-api/src/types/execution/header_with_proof.rs
- crates/light-client/src/config/client_config.rs
- crates/validation/src/accumulator.rs
- crates/validation/src/constants.rs
- crates/validation/src/header_validator.rs
- crates/validation/src/historical_summaries_provider.rs
While working on handling the head of the chain data, I realized that I would have to duplicate some of the logic that exists in other places and that some constants (SLOTS_PER_EPOCH, SLOTS_PER_HISTORICAL_ROOT, CAPELLA_FORK_EPOCH) should be defined in ethportal-api.
Moved constants into: `crates/ethportal-api/src/types/consensus/constants.rs`
Moved `historical_summary_index` calculations into `crates/ethportal-api/src/types/consensus/historical_summaries.rs`
> refactor: move consensus related constants into ethportal-api

- crates/storage/src/sql.rs
- crates/storage/src/utils.rs
This SQL Query is no longer needed
removing it
> feat: remove no longer used DROP_USAGE_STATS_DB sql query

- .circleci/config.yml
- Cargo.toml
- crates/rpc/src/rpc_server.rs
- rust-toolchain.toml
- testing/utp/docker/Dockerfile
There is a new stable release
bump it. I noticed the newest reth-ipc requires a newer stable version, I didn't end up bumping that crate to to other issues with reth-ipc/jsonrpcee as jsonrpcee privated members, reth-ipc needed to work or something
> chore: bump rust version to 1.87

- bin/trin/src/run.rs
- crates/ethportal-api/src/types/consensus/light_client/update.rs
- crates/light-client/src/client.rs
- crates/light-client/src/consensus/consensus_client.rs
- crates/light-client/src/lib.rs
- crates/light-client/src/watch.rs
- crates/subnetworks/beacon/src/lib.rs
- crates/subnetworks/beacon/src/network.rs
- crates/subnetworks/beacon/src/storage.rs
- crates/validation/src/chain_head/mod.rs
- crates/validation/src/chain_head/store.rs
The ChainHead wasn't being updated
Now we update the ChainHead whenever:
- We store related beacon content (OptimisticUpdate, FinalityUpdate, HistoricalSummaries)
- LightClient applies updates to its Store
- This wasn't as easy because we don't have access to updates that LightClient is using.
- I added support for broadcasting applied updates using [tokio::sync::watch::channel](https://docs.rs/tokio/latest/tokio/sync/watch/fn.channel.html)
- First commit adds this support. I'm fine with moving it into separate PR if that's desired
Future work:
- Start using ChainHead for validating content
- Start adding ephemeral content
> feat: update chain_head

- crates/ethportal-api/src/types/content_key/beacon.rs
- crates/ethportal-api/src/types/content_key/history.rs
- crates/ethportal-api/src/types/content_key/overlay.rs
- crates/ethportal-api/src/types/content_key/state.rs
We currently have no way to differentiate between content that:
- is affected by distance from node_id (i.e. non-ephemeral history + state)
- is not affected by distance from node_id (i.e. ephemeral history + beacon)
This affects how we:
- decide whether to accept and store content
- select peers to ask for content (during find_content)
- select peers to gossip content to (both during gossip and poke)
- we don't do random content correctly at the moment
Added `affected_by_radius` function on `OverlayContentKey` trait.
This PR sets up ground work for implementing most missing functionality, which can be split into 3 main categories that will be done in a followup PR:
- storage should be flexible enough to handle this case (PR ready: #1840 )
- bridge's census should respect this when …
> feat: add affected_by_radius to content key

- crates/storage/src/lib.rs
- crates/storage/src/versioned/id_indexed_v1/store.rs
- crates/subnetworks/history/src/storage.rs
- crates/subnetworks/state/src/storage.rs
Followup to #1839
When implementing `is_key_within_radius_and_unavailable` function, content store should take into consideration whether content key is affected by radius or not.
See #1839 for more details.
Implemented missing functionality.
More work will follow regarding this as ephemeral content will not be stored in the current storage object.
> feat: subnetwork stores should use affected_by_radius

- docker/Dockerfile.e2hs-writer
e2hs-writer is failing to read the s3 bucket due to not having access to `ca-certificates`
Install them, I tested this change and it works
> fix: failed to read s3 bucket in dockerfile install ca-certificates

- bin/portal-bridge/src/bridge/beacon.rs
- bin/portal-bridge/src/bridge/e2hs.rs
- bin/portal-bridge/src/bridge/state.rs
- bin/portal-bridge/src/census/mod.rs
- bin/portal-bridge/src/census/network.rs
- bin/portal-bridge/src/census/peer.rs
- bin/portal-bridge/src/census/peers.rs
- bin/portal-bridge/src/census/scoring.rs
Followup to #1839
The census should use distance and radius when selecting peers only if that's relevant for the provided content. 
Added logic that uses `affected_by_radius` function
> feat(bridge): census should use affected_by_radius

- crates/ethereum-rpc-client/src/constants.rs
- crates/ethereum-rpc-client/src/execution.rs
This PR is a requirement for
- https://github.com/ethereum/trin/pull/1846
There is a delay for when receipts become available, as the EL has to generate them. I add something similar to this code because we needed it to make the latest bridge reliable. Due to the aforementioned issue above. I removed this logic in this PR https://github.com/ethereum/trin/pull/1757 well optimizing the Single-E2HS-Writer, because we no longer used this functionality.
Added the retry mechanism back, but only for `get_receipts()`, because it isn't needed in `get_receipts_range` as that function doesn't really have a reason to be used at the head of the chain.
I choose 5, because as I have seen delays of 3 seconds
> feat: add retry to get_receipts

- Cargo.lock
- Cargo.toml
- crates/ethportal-api/Cargo.toml
Update trin & `ethportal-api` crate versions for release
> chore: bump trin (0.3.2) & ethportal-api versions (0.10.2)

- bin/trin-execution/src/e2hs/manager.rs
There was some confusion on a confusing comment https://github.com/ethereum/trin/pull/1855#discussion_r2106156634
Updating the comment to be more accuate
> chore: fix confusing comment in E2HSManager

- bin/trin-execution/src/e2hs/beacon.rs
- bin/trin-execution/src/e2hs/utils.rs
We updated from alloy-consensus 1.0.3 to 1.0.7 the behavior changed though which broke Trin Execution executing blocks
Update `recover_signer` to `recover_signer_unchecked` which matched the functionality of the 1.0.3 version
> fix: regression on recoverying transaction address after version update

- crates/ethportal-api/build.rs
The trin's [client version graph](https://glados.ethdevops.io/clients?network=History) in Glados indicates that majority of our nodes are running version "0.1.0".
After some debugging I found that there was a regression introduced in #1834 
The `vergen` crate was significantly refactored and the order of parameters changed between original [`EmitBuilder::git_describe`](https://docs.rs/vergen/8.3.2/vergen/struct.EmitBuilder.html#method.git_describe) and new [`Git2Builder::describe`](https://docs.rs/vergen-git2/1.0.7/vergen_git2/struct.Git2Builder.html#method.describe).
> fix: trin version is incorrect

- Cargo.lock
- Cargo.toml
- crates/ethportal-api/Cargo.toml
Update crates version as preparation for upcoming release.
> chore: bump trin (0.3.3) & ethportal-api versions (0.10.3)

- bin/trin/src/cli.rs
- book/src/users/cli.md
Also, regenerate the help in the trin book, using the longer format.
The flag `--mb` is used pretty liberally in the trin book. It is not mentioned anywhere what it is.
Having the flag mentioned in the long CLI help seems like the least we can do.
> docs: mention the --mb alias in the CLI

- Cargo.lock
- crates/portalnet/src/overlay/protocol.rs
- crates/portalnet/src/overlay/service/find_content.rs
- crates/portalnet/src/overlay/service/offer.rs
- crates/storage/src/lib.rs
- crates/subnetworks/beacon/src/storage.rs
- crates/subnetworks/beacon/src/validation.rs
- crates/subnetworks/history/src/storage.rs
- crates/subnetworks/history/src/validation.rs
- crates/subnetworks/state/src/storage.rs
- crates/subnetworks/state/src/validation/validator.rs
- crates/validation/Cargo.toml
- crates/validation/src/validator.rs
This was extracted from #1868
`Validator` is currently able to validate only one content at the time. This is not enough for ephemeral headers.
Similar for `Store` when answering whether content is/should be stored.
Rename `ContentStore::is_key_within_radius_and_unavailable` to `ContentStore::should_we_store` and add `Store::should_we_store_batch` (for multiple items.
Add `Validator::validate_content_batch` for validating multiple content items.
Refactor `ValidationResult`:
- removed `additional_content_to_propagate` from ValidationResult (it's not used)
- made ValidationResult an enum
- enum type works better as a result of `validate_content_batch`, because it is `Vec<ValidationResult>` instead of `Vec<Result<ValidationResult>>`
- we can consider in the future changing `Invalid(String)` …
> refactor: add batch content validation

- crates/portalnet/src/overlay/service/offer.rs
This is followup for #1869, which should be reviewed and merged first.
When we are offered multiple content, the overlay service does all of the following on per-content basis:
- checks whether they should be accepted
- validates them
- stores them
This doesn't work for EphemeralHeaders, which we have to process together (at least checking which content to accept and validating). This PR uses batch functions added in #1869.
The `OverlayService::handle_offer` now uses these `batch` functions to process all accepted content together.
We would still do a fallback fetching if request fails or received content is not valid.
I would have to think more whether this is desired for EphemeralContent, and if not, how exactly to distinguish/handle this case.
Modify history Store and Validator to …
> feat: use batch validation

- README.md
- crates/ethportal-api/README.md
Trin is no longer actively maintained and we should add clear warning in README files.
Added warning.
> docs: add "no longer supported" warning to readme

- crates/ethportal-api/src/history.rs
- crates/ethportal-api/src/lib.rs
- crates/ethportal-api/src/types/content_key/content_id.rs
- crates/ethportal-api/src/types/content_key/history.rs
- crates/ethportal-api/src/types/content_key/mod.rs
- crates/ethportal-api/src/types/content_value/history.rs
- crates/ethportal-api/src/types/content_value/mod.rs
- crates/ethportal-api/src/types/network.rs
- crates/ethportal-api/src/types/network_spec.rs
- crates/ethportal-api/src/types/ping_extensions/consts.rs
- testing/ethportal-peertest/src/utils.rs
We are missing type definition for the new history network.
See https://github.com/ethereum/portal-network-specs/pull/407 for details.
Created most of the new types.
Content value to be added in the next PR once I have test vectors.
> feat: add new history network types

- crates/ethportal-api/src/types/content_value/history.rs
The content value for the history subnetwork wasn't implemented (we couldn't encode, decode, validate).
Added definition for new types (including new receipt encoding), and all useful functions.
> feat: implement HistoryContentValue
